
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  Profile: 'Profile',
  LocationNode: 'LocationNode',
  Photo: 'Photo',
  ProfileVideo: 'ProfileVideo',
  Reel: 'Reel',
  ReelView: 'ReelView',
  Wallet: 'Wallet',
  CoinTransaction: 'CoinTransaction',
  CoinPackage: 'CoinPackage',
  VipPlan: 'VipPlan',
  VipSubscription: 'VipSubscription',
  Order: 'Order',
  Gift: 'Gift',
  GiftTransaction: 'GiftTransaction',
  Conversation: 'Conversation',
  ConversationTag: 'ConversationTag',
  Message: 'Message',
  Block: 'Block',
  Interaction: 'Interaction',
  ProfileVisit: 'ProfileVisit',
  SavedSearch: 'SavedSearch',
  Report: 'Report',
  Verification: 'Verification',
  AdminAction: 'AdminAction',
  Ad: 'Ad',
  AdImpression: 'AdImpression',
  PlanSetting: 'PlanSetting',
  ModerationRule: 'ModerationRule',
  AppSetting: 'AppSetting',
  PasswordResetToken: 'PasswordResetToken',
  EmailVerificationCode: 'EmailVerificationCode',
  SupportRequest: 'SupportRequest'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  passwordHash: 'passwordHash',
  name: 'name',
  role: 'role',
  status: 'status',
  emailVerified: 'emailVerified',
  membership: 'membership',
  trustScore: 'trustScore',
  shadowRestricted: 'shadowRestricted',
  ipFlagged: 'ipFlagged',
  suspendedAt: 'suspendedAt',
  suspensionReason: 'suspensionReason',
  ipCountry: 'ipCountry',
  vpnSuspected: 'vpnSuspected',
  lastActiveAt: 'lastActiveAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const ProfileScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  displayName: 'displayName',
  headline: 'headline',
  bio: 'bio',
  dateOfBirth: 'dateOfBirth',
  age: 'age',
  gender: 'gender',
  seeking: 'seeking',
  intent: 'intent',
  heightCm: 'heightCm',
  bodyType: 'bodyType',
  children: 'children',
  wantChildren: 'wantChildren',
  smoking: 'smoking',
  drinking: 'drinking',
  religion: 'religion',
  education: 'education',
  profession: 'profession',
  exercise: 'exercise',
  relocate: 'relocate',
  languages: 'languages',
  interests: 'interests',
  goals: 'goals',
  icebreakers: 'icebreakers',
  preferences: 'preferences',
  stealthMode: 'stealthMode',
  locationText: 'locationText',
  countryCode: 'countryCode',
  locationNodeId: 'locationNodeId',
  completion: 'completion',
  tier: 'tier',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ProfileScalarFieldEnum = (typeof ProfileScalarFieldEnum)[keyof typeof ProfileScalarFieldEnum]


export const LocationNodeScalarFieldEnum = {
  id: 'id',
  type: 'type',
  name: 'name',
  countryCode: 'countryCode',
  parentId: 'parentId'
} as const

export type LocationNodeScalarFieldEnum = (typeof LocationNodeScalarFieldEnum)[keyof typeof LocationNodeScalarFieldEnum]


export const PhotoScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  url: 'url',
  isPrimary: 'isPrimary',
  position: 'position',
  moderation: 'moderation',
  createdAt: 'createdAt'
} as const

export type PhotoScalarFieldEnum = (typeof PhotoScalarFieldEnum)[keyof typeof PhotoScalarFieldEnum]


export const ProfileVideoScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  url: 'url',
  durationSec: 'durationSec',
  position: 'position',
  moderation: 'moderation',
  createdAt: 'createdAt'
} as const

export type ProfileVideoScalarFieldEnum = (typeof ProfileVideoScalarFieldEnum)[keyof typeof ProfileVideoScalarFieldEnum]


export const ReelScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  mediaUrl: 'mediaUrl',
  mediaType: 'mediaType',
  thumbnailUrl: 'thumbnailUrl',
  caption: 'caption',
  status: 'status',
  moderation: 'moderation',
  viewsCount: 'viewsCount',
  createdAt: 'createdAt',
  expiresAt: 'expiresAt'
} as const

export type ReelScalarFieldEnum = (typeof ReelScalarFieldEnum)[keyof typeof ReelScalarFieldEnum]


export const ReelViewScalarFieldEnum = {
  id: 'id',
  reelId: 'reelId',
  viewerId: 'viewerId',
  createdAt: 'createdAt'
} as const

export type ReelViewScalarFieldEnum = (typeof ReelViewScalarFieldEnum)[keyof typeof ReelViewScalarFieldEnum]


export const WalletScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  coinBalance: 'coinBalance',
  updatedAt: 'updatedAt'
} as const

export type WalletScalarFieldEnum = (typeof WalletScalarFieldEnum)[keyof typeof WalletScalarFieldEnum]


export const CoinTransactionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  amount: 'amount',
  type: 'type',
  balanceAfter: 'balanceAfter',
  reference: 'reference',
  note: 'note',
  createdAt: 'createdAt'
} as const

export type CoinTransactionScalarFieldEnum = (typeof CoinTransactionScalarFieldEnum)[keyof typeof CoinTransactionScalarFieldEnum]


export const CoinPackageScalarFieldEnum = {
  id: 'id',
  label: 'label',
  coins: 'coins',
  priceGBP: 'priceGBP',
  bonus: 'bonus',
  active: 'active',
  sortOrder: 'sortOrder'
} as const

export type CoinPackageScalarFieldEnum = (typeof CoinPackageScalarFieldEnum)[keyof typeof CoinPackageScalarFieldEnum]


export const VipPlanScalarFieldEnum = {
  id: 'id',
  label: 'label',
  durationDays: 'durationDays',
  priceGBP: 'priceGBP',
  costCoins: 'costCoins',
  bonusCoins: 'bonusCoins',
  active: 'active',
  sortOrder: 'sortOrder'
} as const

export type VipPlanScalarFieldEnum = (typeof VipPlanScalarFieldEnum)[keyof typeof VipPlanScalarFieldEnum]


export const VipSubscriptionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  planId: 'planId',
  startedAt: 'startedAt',
  expiresAt: 'expiresAt',
  active: 'active',
  source: 'source',
  createdAt: 'createdAt'
} as const

export type VipSubscriptionScalarFieldEnum = (typeof VipSubscriptionScalarFieldEnum)[keyof typeof VipSubscriptionScalarFieldEnum]


export const OrderScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  kind: 'kind',
  reference: 'reference',
  amountGBP: 'amountGBP',
  coins: 'coins',
  status: 'status',
  provider: 'provider',
  providerRef: 'providerRef',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type OrderScalarFieldEnum = (typeof OrderScalarFieldEnum)[keyof typeof OrderScalarFieldEnum]


export const GiftScalarFieldEnum = {
  id: 'id',
  name: 'name',
  icon: 'icon',
  costCoins: 'costCoins',
  active: 'active',
  sortOrder: 'sortOrder'
} as const

export type GiftScalarFieldEnum = (typeof GiftScalarFieldEnum)[keyof typeof GiftScalarFieldEnum]


export const GiftTransactionScalarFieldEnum = {
  id: 'id',
  giftId: 'giftId',
  senderId: 'senderId',
  receiverId: 'receiverId',
  coinsSpent: 'coinsSpent',
  message: 'message',
  createdAt: 'createdAt'
} as const

export type GiftTransactionScalarFieldEnum = (typeof GiftTransactionScalarFieldEnum)[keyof typeof GiftTransactionScalarFieldEnum]


export const ConversationScalarFieldEnum = {
  id: 'id',
  participantAId: 'participantAId',
  participantBId: 'participantBId',
  lastMessageAt: 'lastMessageAt',
  createdAt: 'createdAt'
} as const

export type ConversationScalarFieldEnum = (typeof ConversationScalarFieldEnum)[keyof typeof ConversationScalarFieldEnum]


export const ConversationTagScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  conversationId: 'conversationId',
  label: 'label',
  favourite: 'favourite',
  archived: 'archived',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ConversationTagScalarFieldEnum = (typeof ConversationTagScalarFieldEnum)[keyof typeof ConversationTagScalarFieldEnum]


export const MessageScalarFieldEnum = {
  id: 'id',
  conversationId: 'conversationId',
  senderId: 'senderId',
  type: 'type',
  body: 'body',
  mediaUrl: 'mediaUrl',
  read: 'read',
  readAt: 'readAt',
  flagged: 'flagged',
  createdAt: 'createdAt'
} as const

export type MessageScalarFieldEnum = (typeof MessageScalarFieldEnum)[keyof typeof MessageScalarFieldEnum]


export const BlockScalarFieldEnum = {
  id: 'id',
  blockerId: 'blockerId',
  blockedId: 'blockedId',
  createdAt: 'createdAt'
} as const

export type BlockScalarFieldEnum = (typeof BlockScalarFieldEnum)[keyof typeof BlockScalarFieldEnum]


export const InteractionScalarFieldEnum = {
  id: 'id',
  fromId: 'fromId',
  toId: 'toId',
  type: 'type',
  createdAt: 'createdAt'
} as const

export type InteractionScalarFieldEnum = (typeof InteractionScalarFieldEnum)[keyof typeof InteractionScalarFieldEnum]


export const ProfileVisitScalarFieldEnum = {
  id: 'id',
  visitorId: 'visitorId',
  profileId: 'profileId',
  createdAt: 'createdAt'
} as const

export type ProfileVisitScalarFieldEnum = (typeof ProfileVisitScalarFieldEnum)[keyof typeof ProfileVisitScalarFieldEnum]


export const SavedSearchScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  name: 'name',
  filters: 'filters',
  createdAt: 'createdAt'
} as const

export type SavedSearchScalarFieldEnum = (typeof SavedSearchScalarFieldEnum)[keyof typeof SavedSearchScalarFieldEnum]


export const ReportScalarFieldEnum = {
  id: 'id',
  reporterId: 'reporterId',
  reportedUserId: 'reportedUserId',
  conversationId: 'conversationId',
  reelId: 'reelId',
  photoId: 'photoId',
  category: 'category',
  note: 'note',
  status: 'status',
  decision: 'decision',
  createdAt: 'createdAt',
  resolvedAt: 'resolvedAt'
} as const

export type ReportScalarFieldEnum = (typeof ReportScalarFieldEnum)[keyof typeof ReportScalarFieldEnum]


export const VerificationScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  status: 'status',
  evidenceUrl: 'evidenceUrl',
  note: 'note',
  submittedAt: 'submittedAt',
  reviewedAt: 'reviewedAt',
  reviewerId: 'reviewerId'
} as const

export type VerificationScalarFieldEnum = (typeof VerificationScalarFieldEnum)[keyof typeof VerificationScalarFieldEnum]


export const AdminActionScalarFieldEnum = {
  id: 'id',
  adminId: 'adminId',
  action: 'action',
  targetType: 'targetType',
  targetId: 'targetId',
  detail: 'detail',
  createdAt: 'createdAt'
} as const

export type AdminActionScalarFieldEnum = (typeof AdminActionScalarFieldEnum)[keyof typeof AdminActionScalarFieldEnum]


export const AdScalarFieldEnum = {
  id: 'id',
  title: 'title',
  imageUrl: 'imageUrl',
  targetUrl: 'targetUrl',
  placement: 'placement',
  active: 'active',
  weight: 'weight',
  advertiser: 'advertiser',
  createdAt: 'createdAt'
} as const

export type AdScalarFieldEnum = (typeof AdScalarFieldEnum)[keyof typeof AdScalarFieldEnum]


export const AdImpressionScalarFieldEnum = {
  id: 'id',
  adId: 'adId',
  userId: 'userId',
  createdAt: 'createdAt'
} as const

export type AdImpressionScalarFieldEnum = (typeof AdImpressionScalarFieldEnum)[keyof typeof AdImpressionScalarFieldEnum]


export const PlanSettingScalarFieldEnum = {
  id: 'id',
  tier: 'tier',
  maxPhotos: 'maxPhotos',
  maxVideos: 'maxVideos',
  videoMaxSeconds: 'videoMaxSeconds',
  updatedAt: 'updatedAt'
} as const

export type PlanSettingScalarFieldEnum = (typeof PlanSettingScalarFieldEnum)[keyof typeof PlanSettingScalarFieldEnum]


export const ModerationRuleScalarFieldEnum = {
  id: 'id',
  kind: 'kind',
  pattern: 'pattern',
  action: 'action',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ModerationRuleScalarFieldEnum = (typeof ModerationRuleScalarFieldEnum)[keyof typeof ModerationRuleScalarFieldEnum]


export const AppSettingScalarFieldEnum = {
  id: 'id',
  launchMode: 'launchMode',
  comingSoonImageUrl: 'comingSoonImageUrl',
  headline: 'headline',
  subtext: 'subtext',
  updatedAt: 'updatedAt'
} as const

export type AppSettingScalarFieldEnum = (typeof AppSettingScalarFieldEnum)[keyof typeof AppSettingScalarFieldEnum]


export const PasswordResetTokenScalarFieldEnum = {
  id: 'id',
  token: 'token',
  userId: 'userId',
  expiresAt: 'expiresAt',
  used: 'used',
  createdAt: 'createdAt'
} as const

export type PasswordResetTokenScalarFieldEnum = (typeof PasswordResetTokenScalarFieldEnum)[keyof typeof PasswordResetTokenScalarFieldEnum]


export const EmailVerificationCodeScalarFieldEnum = {
  id: 'id',
  sessionId: 'sessionId',
  email: 'email',
  userName: 'userName',
  codeHash: 'codeHash',
  expiresAt: 'expiresAt',
  attempts: 'attempts',
  consumed: 'consumed',
  createdAt: 'createdAt'
} as const

export type EmailVerificationCodeScalarFieldEnum = (typeof EmailVerificationCodeScalarFieldEnum)[keyof typeof EmailVerificationCodeScalarFieldEnum]


export const SupportRequestScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  userName: 'userName',
  email: 'email',
  subject: 'subject',
  message: 'message',
  type: 'type',
  status: 'status',
  replyNote: 'replyNote',
  canReceiveMessageReply: 'canReceiveMessageReply',
  repliedToMessagesAt: 'repliedToMessagesAt',
  createdAt: 'createdAt'
} as const

export type SupportRequestScalarFieldEnum = (typeof SupportRequestScalarFieldEnum)[keyof typeof SupportRequestScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const UserOrderByRelevanceFieldEnum = {
  id: 'id',
  email: 'email',
  passwordHash: 'passwordHash',
  name: 'name',
  suspensionReason: 'suspensionReason',
  ipCountry: 'ipCountry'
} as const

export type UserOrderByRelevanceFieldEnum = (typeof UserOrderByRelevanceFieldEnum)[keyof typeof UserOrderByRelevanceFieldEnum]


export const ProfileOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  displayName: 'displayName',
  headline: 'headline',
  bio: 'bio',
  intent: 'intent',
  bodyType: 'bodyType',
  children: 'children',
  wantChildren: 'wantChildren',
  smoking: 'smoking',
  drinking: 'drinking',
  religion: 'religion',
  education: 'education',
  profession: 'profession',
  exercise: 'exercise',
  relocate: 'relocate',
  languages: 'languages',
  interests: 'interests',
  goals: 'goals',
  icebreakers: 'icebreakers',
  preferences: 'preferences',
  locationText: 'locationText',
  countryCode: 'countryCode',
  locationNodeId: 'locationNodeId'
} as const

export type ProfileOrderByRelevanceFieldEnum = (typeof ProfileOrderByRelevanceFieldEnum)[keyof typeof ProfileOrderByRelevanceFieldEnum]


export const LocationNodeOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  countryCode: 'countryCode',
  parentId: 'parentId'
} as const

export type LocationNodeOrderByRelevanceFieldEnum = (typeof LocationNodeOrderByRelevanceFieldEnum)[keyof typeof LocationNodeOrderByRelevanceFieldEnum]


export const PhotoOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  url: 'url'
} as const

export type PhotoOrderByRelevanceFieldEnum = (typeof PhotoOrderByRelevanceFieldEnum)[keyof typeof PhotoOrderByRelevanceFieldEnum]


export const ProfileVideoOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  url: 'url'
} as const

export type ProfileVideoOrderByRelevanceFieldEnum = (typeof ProfileVideoOrderByRelevanceFieldEnum)[keyof typeof ProfileVideoOrderByRelevanceFieldEnum]


export const ReelOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  mediaUrl: 'mediaUrl',
  thumbnailUrl: 'thumbnailUrl',
  caption: 'caption'
} as const

export type ReelOrderByRelevanceFieldEnum = (typeof ReelOrderByRelevanceFieldEnum)[keyof typeof ReelOrderByRelevanceFieldEnum]


export const ReelViewOrderByRelevanceFieldEnum = {
  id: 'id',
  reelId: 'reelId',
  viewerId: 'viewerId'
} as const

export type ReelViewOrderByRelevanceFieldEnum = (typeof ReelViewOrderByRelevanceFieldEnum)[keyof typeof ReelViewOrderByRelevanceFieldEnum]


export const WalletOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId'
} as const

export type WalletOrderByRelevanceFieldEnum = (typeof WalletOrderByRelevanceFieldEnum)[keyof typeof WalletOrderByRelevanceFieldEnum]


export const CoinTransactionOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  reference: 'reference',
  note: 'note'
} as const

export type CoinTransactionOrderByRelevanceFieldEnum = (typeof CoinTransactionOrderByRelevanceFieldEnum)[keyof typeof CoinTransactionOrderByRelevanceFieldEnum]


export const CoinPackageOrderByRelevanceFieldEnum = {
  id: 'id',
  label: 'label'
} as const

export type CoinPackageOrderByRelevanceFieldEnum = (typeof CoinPackageOrderByRelevanceFieldEnum)[keyof typeof CoinPackageOrderByRelevanceFieldEnum]


export const VipPlanOrderByRelevanceFieldEnum = {
  id: 'id',
  label: 'label'
} as const

export type VipPlanOrderByRelevanceFieldEnum = (typeof VipPlanOrderByRelevanceFieldEnum)[keyof typeof VipPlanOrderByRelevanceFieldEnum]


export const VipSubscriptionOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  planId: 'planId',
  source: 'source'
} as const

export type VipSubscriptionOrderByRelevanceFieldEnum = (typeof VipSubscriptionOrderByRelevanceFieldEnum)[keyof typeof VipSubscriptionOrderByRelevanceFieldEnum]


export const OrderOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  reference: 'reference',
  provider: 'provider',
  providerRef: 'providerRef'
} as const

export type OrderOrderByRelevanceFieldEnum = (typeof OrderOrderByRelevanceFieldEnum)[keyof typeof OrderOrderByRelevanceFieldEnum]


export const GiftOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  icon: 'icon'
} as const

export type GiftOrderByRelevanceFieldEnum = (typeof GiftOrderByRelevanceFieldEnum)[keyof typeof GiftOrderByRelevanceFieldEnum]


export const GiftTransactionOrderByRelevanceFieldEnum = {
  id: 'id',
  giftId: 'giftId',
  senderId: 'senderId',
  receiverId: 'receiverId',
  message: 'message'
} as const

export type GiftTransactionOrderByRelevanceFieldEnum = (typeof GiftTransactionOrderByRelevanceFieldEnum)[keyof typeof GiftTransactionOrderByRelevanceFieldEnum]


export const ConversationOrderByRelevanceFieldEnum = {
  id: 'id',
  participantAId: 'participantAId',
  participantBId: 'participantBId'
} as const

export type ConversationOrderByRelevanceFieldEnum = (typeof ConversationOrderByRelevanceFieldEnum)[keyof typeof ConversationOrderByRelevanceFieldEnum]


export const ConversationTagOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  conversationId: 'conversationId',
  label: 'label'
} as const

export type ConversationTagOrderByRelevanceFieldEnum = (typeof ConversationTagOrderByRelevanceFieldEnum)[keyof typeof ConversationTagOrderByRelevanceFieldEnum]


export const MessageOrderByRelevanceFieldEnum = {
  id: 'id',
  conversationId: 'conversationId',
  senderId: 'senderId',
  body: 'body',
  mediaUrl: 'mediaUrl'
} as const

export type MessageOrderByRelevanceFieldEnum = (typeof MessageOrderByRelevanceFieldEnum)[keyof typeof MessageOrderByRelevanceFieldEnum]


export const BlockOrderByRelevanceFieldEnum = {
  id: 'id',
  blockerId: 'blockerId',
  blockedId: 'blockedId'
} as const

export type BlockOrderByRelevanceFieldEnum = (typeof BlockOrderByRelevanceFieldEnum)[keyof typeof BlockOrderByRelevanceFieldEnum]


export const InteractionOrderByRelevanceFieldEnum = {
  id: 'id',
  fromId: 'fromId',
  toId: 'toId'
} as const

export type InteractionOrderByRelevanceFieldEnum = (typeof InteractionOrderByRelevanceFieldEnum)[keyof typeof InteractionOrderByRelevanceFieldEnum]


export const ProfileVisitOrderByRelevanceFieldEnum = {
  id: 'id',
  visitorId: 'visitorId',
  profileId: 'profileId'
} as const

export type ProfileVisitOrderByRelevanceFieldEnum = (typeof ProfileVisitOrderByRelevanceFieldEnum)[keyof typeof ProfileVisitOrderByRelevanceFieldEnum]


export const SavedSearchOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  name: 'name',
  filters: 'filters'
} as const

export type SavedSearchOrderByRelevanceFieldEnum = (typeof SavedSearchOrderByRelevanceFieldEnum)[keyof typeof SavedSearchOrderByRelevanceFieldEnum]


export const ReportOrderByRelevanceFieldEnum = {
  id: 'id',
  reporterId: 'reporterId',
  reportedUserId: 'reportedUserId',
  conversationId: 'conversationId',
  reelId: 'reelId',
  photoId: 'photoId',
  note: 'note',
  decision: 'decision'
} as const

export type ReportOrderByRelevanceFieldEnum = (typeof ReportOrderByRelevanceFieldEnum)[keyof typeof ReportOrderByRelevanceFieldEnum]


export const VerificationOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  evidenceUrl: 'evidenceUrl',
  note: 'note',
  reviewerId: 'reviewerId'
} as const

export type VerificationOrderByRelevanceFieldEnum = (typeof VerificationOrderByRelevanceFieldEnum)[keyof typeof VerificationOrderByRelevanceFieldEnum]


export const AdminActionOrderByRelevanceFieldEnum = {
  id: 'id',
  adminId: 'adminId',
  action: 'action',
  targetType: 'targetType',
  targetId: 'targetId',
  detail: 'detail'
} as const

export type AdminActionOrderByRelevanceFieldEnum = (typeof AdminActionOrderByRelevanceFieldEnum)[keyof typeof AdminActionOrderByRelevanceFieldEnum]


export const AdOrderByRelevanceFieldEnum = {
  id: 'id',
  title: 'title',
  imageUrl: 'imageUrl',
  targetUrl: 'targetUrl',
  advertiser: 'advertiser'
} as const

export type AdOrderByRelevanceFieldEnum = (typeof AdOrderByRelevanceFieldEnum)[keyof typeof AdOrderByRelevanceFieldEnum]


export const AdImpressionOrderByRelevanceFieldEnum = {
  id: 'id',
  adId: 'adId',
  userId: 'userId'
} as const

export type AdImpressionOrderByRelevanceFieldEnum = (typeof AdImpressionOrderByRelevanceFieldEnum)[keyof typeof AdImpressionOrderByRelevanceFieldEnum]


export const PlanSettingOrderByRelevanceFieldEnum = {
  id: 'id'
} as const

export type PlanSettingOrderByRelevanceFieldEnum = (typeof PlanSettingOrderByRelevanceFieldEnum)[keyof typeof PlanSettingOrderByRelevanceFieldEnum]


export const ModerationRuleOrderByRelevanceFieldEnum = {
  id: 'id',
  pattern: 'pattern'
} as const

export type ModerationRuleOrderByRelevanceFieldEnum = (typeof ModerationRuleOrderByRelevanceFieldEnum)[keyof typeof ModerationRuleOrderByRelevanceFieldEnum]


export const AppSettingOrderByRelevanceFieldEnum = {
  id: 'id',
  comingSoonImageUrl: 'comingSoonImageUrl',
  headline: 'headline',
  subtext: 'subtext'
} as const

export type AppSettingOrderByRelevanceFieldEnum = (typeof AppSettingOrderByRelevanceFieldEnum)[keyof typeof AppSettingOrderByRelevanceFieldEnum]


export const PasswordResetTokenOrderByRelevanceFieldEnum = {
  id: 'id',
  token: 'token',
  userId: 'userId'
} as const

export type PasswordResetTokenOrderByRelevanceFieldEnum = (typeof PasswordResetTokenOrderByRelevanceFieldEnum)[keyof typeof PasswordResetTokenOrderByRelevanceFieldEnum]


export const EmailVerificationCodeOrderByRelevanceFieldEnum = {
  id: 'id',
  sessionId: 'sessionId',
  email: 'email',
  userName: 'userName',
  codeHash: 'codeHash'
} as const

export type EmailVerificationCodeOrderByRelevanceFieldEnum = (typeof EmailVerificationCodeOrderByRelevanceFieldEnum)[keyof typeof EmailVerificationCodeOrderByRelevanceFieldEnum]


export const SupportRequestOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  userName: 'userName',
  email: 'email',
  subject: 'subject',
  message: 'message',
  replyNote: 'replyNote'
} as const

export type SupportRequestOrderByRelevanceFieldEnum = (typeof SupportRequestOrderByRelevanceFieldEnum)[keyof typeof SupportRequestOrderByRelevanceFieldEnum]

