
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 *
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
globalThis['__dirname'] = path.dirname(fileURLToPath(import.meta.url))

import * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums"
import * as $Class from "./internal/class"
import * as Prisma from "./internal/prismaNamespace"

export * as $Enums from './enums'
export * from "./enums"
/**
 * ## Prisma Client
 *
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient({
 *   adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL })
 * })
 * // Fetch zero or more Users
 * const users = await prisma.user.findMany()
 * ```
 *
 * Read more in our [docs](https://pris.ly/d/client).
 */
export const PrismaClient = $Class.getPrismaClientClass()
export type PrismaClient<LogOpts extends Prisma.LogLevel = never, OmitOpts extends Prisma.PrismaClientOptions["omit"] = Prisma.PrismaClientOptions["omit"], ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>
export { Prisma }

/**
 * Model User
 *
 */
export type User = Prisma.UserModel
/**
 * Model Profile
 *
 */
export type Profile = Prisma.ProfileModel
/**
 * Model LocationNode
 *
 */
export type LocationNode = Prisma.LocationNodeModel
/**
 * Model Photo
 *
 */
export type Photo = Prisma.PhotoModel
/**
 * Model ProfileVideo
 *
 */
export type ProfileVideo = Prisma.ProfileVideoModel
/**
 * Model Reel
 *
 */
export type Reel = Prisma.ReelModel
/**
 * Model ReelView
 *
 */
export type ReelView = Prisma.ReelViewModel
/**
 * Model Wallet
 *
 */
export type Wallet = Prisma.WalletModel
/**
 * Model CoinTransaction
 *
 */
export type CoinTransaction = Prisma.CoinTransactionModel
/**
 * Model CoinPackage
 *
 */
export type CoinPackage = Prisma.CoinPackageModel
/**
 * Model VipPlan
 *
 */
export type VipPlan = Prisma.VipPlanModel
/**
 * Model VipSubscription
 *
 */
export type VipSubscription = Prisma.VipSubscriptionModel
/**
 * Model Order
 *
 */
export type Order = Prisma.OrderModel
/**
 * Model Gift
 *
 */
export type Gift = Prisma.GiftModel
/**
 * Model GiftTransaction
 *
 */
export type GiftTransaction = Prisma.GiftTransactionModel
/**
 * Model Conversation
 *
 */
export type Conversation = Prisma.ConversationModel
/**
 * Model ConversationTag
 *
 */
export type ConversationTag = Prisma.ConversationTagModel
/**
 * Model Message
 *
 */
export type Message = Prisma.MessageModel
/**
 * Model Block
 *
 */
export type Block = Prisma.BlockModel
/**
 * Model Interaction
 *
 */
export type Interaction = Prisma.InteractionModel
/**
 * Model ProfileVisit
 *
 */
export type ProfileVisit = Prisma.ProfileVisitModel
/**
 * Model SavedSearch
 *
 */
export type SavedSearch = Prisma.SavedSearchModel
/**
 * Model Report
 *
 */
export type Report = Prisma.ReportModel
/**
 * Model Verification
 *
 */
export type Verification = Prisma.VerificationModel
/**
 * Model AdminAction
 *
 */
export type AdminAction = Prisma.AdminActionModel
/**
 * Model Ad
 *
 */
export type Ad = Prisma.AdModel
/**
 * Model AdImpression
 *
 */
export type AdImpression = Prisma.AdImpressionModel
/**
 * Model PlanSetting
 *
 */
export type PlanSetting = Prisma.PlanSettingModel
/**
 * Model ModerationRule
 *
 */
export type ModerationRule = Prisma.ModerationRuleModel
/**
 * Model AppSetting
 *
 */
export type AppSetting = Prisma.AppSettingModel
/**
 * Model PasswordResetToken
 *
 */
export type PasswordResetToken = Prisma.PasswordResetTokenModel
/**
 * Model EmailVerificationCode
 *
 */
export type EmailVerificationCode = Prisma.EmailVerificationCodeModel
/**
 * Model SupportRequest
 *
 */
export type SupportRequest = Prisma.SupportRequestModel
