
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports various common sort, input & filter types that are not directly linked to a particular model.
 *
 * 🟢 You can import this file directly.
 */

import type * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums"
import type * as Prisma from "./internal/prismaNamespace"


export type StringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[]
  notIn?: string[]
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  search?: string
  not?: Prisma.NestedStringFilter<$PrismaModel> | string
}

export type StringNullableFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | null
  notIn?: string[] | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  search?: string
  not?: Prisma.NestedStringNullableFilter<$PrismaModel> | string | null
}

export type EnumUserRoleFilter<$PrismaModel = never> = {
  equals?: $Enums.UserRole | Prisma.EnumUserRoleFieldRefInput<$PrismaModel>
  in?: $Enums.UserRole[]
  notIn?: $Enums.UserRole[]
  not?: Prisma.NestedEnumUserRoleFilter<$PrismaModel> | $Enums.UserRole
}

export type EnumAccountStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.AccountStatus | Prisma.EnumAccountStatusFieldRefInput<$PrismaModel>
  in?: $Enums.AccountStatus[]
  notIn?: $Enums.AccountStatus[]
  not?: Prisma.NestedEnumAccountStatusFilter<$PrismaModel> | $Enums.AccountStatus
}

export type DateTimeNullableFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | null
  notIn?: Date[] | string[] | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableFilter<$PrismaModel> | Date | string | null
}

export type EnumMembershipLevelFilter<$PrismaModel = never> = {
  equals?: $Enums.MembershipLevel | Prisma.EnumMembershipLevelFieldRefInput<$PrismaModel>
  in?: $Enums.MembershipLevel[]
  notIn?: $Enums.MembershipLevel[]
  not?: Prisma.NestedEnumMembershipLevelFilter<$PrismaModel> | $Enums.MembershipLevel
}

export type IntFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[]
  notIn?: number[]
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntFilter<$PrismaModel> | number
}

export type BoolFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolFilter<$PrismaModel> | boolean
}

export type DateTimeFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[]
  notIn?: Date[] | string[]
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeFilter<$PrismaModel> | Date | string
}

export type SortOrderInput = {
  sort: Prisma.SortOrder
  nulls?: Prisma.NullsOrder
}

export type StringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[]
  notIn?: string[]
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  search?: string
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedStringFilter<$PrismaModel>
  _max?: Prisma.NestedStringFilter<$PrismaModel>
}

export type StringNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | null
  notIn?: string[] | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  search?: string
  not?: Prisma.NestedStringNullableWithAggregatesFilter<$PrismaModel> | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedStringNullableFilter<$PrismaModel>
  _max?: Prisma.NestedStringNullableFilter<$PrismaModel>
}

export type EnumUserRoleWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.UserRole | Prisma.EnumUserRoleFieldRefInput<$PrismaModel>
  in?: $Enums.UserRole[]
  notIn?: $Enums.UserRole[]
  not?: Prisma.NestedEnumUserRoleWithAggregatesFilter<$PrismaModel> | $Enums.UserRole
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumUserRoleFilter<$PrismaModel>
  _max?: Prisma.NestedEnumUserRoleFilter<$PrismaModel>
}

export type EnumAccountStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.AccountStatus | Prisma.EnumAccountStatusFieldRefInput<$PrismaModel>
  in?: $Enums.AccountStatus[]
  notIn?: $Enums.AccountStatus[]
  not?: Prisma.NestedEnumAccountStatusWithAggregatesFilter<$PrismaModel> | $Enums.AccountStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumAccountStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumAccountStatusFilter<$PrismaModel>
}

export type DateTimeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | null
  notIn?: Date[] | string[] | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableWithAggregatesFilter<$PrismaModel> | Date | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
}

export type EnumMembershipLevelWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.MembershipLevel | Prisma.EnumMembershipLevelFieldRefInput<$PrismaModel>
  in?: $Enums.MembershipLevel[]
  notIn?: $Enums.MembershipLevel[]
  not?: Prisma.NestedEnumMembershipLevelWithAggregatesFilter<$PrismaModel> | $Enums.MembershipLevel
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumMembershipLevelFilter<$PrismaModel>
  _max?: Prisma.NestedEnumMembershipLevelFilter<$PrismaModel>
}

export type IntWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[]
  notIn?: number[]
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntWithAggregatesFilter<$PrismaModel> | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedIntFilter<$PrismaModel>
  _max?: Prisma.NestedIntFilter<$PrismaModel>
}

export type BoolWithAggregatesFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolWithAggregatesFilter<$PrismaModel> | boolean
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedBoolFilter<$PrismaModel>
  _max?: Prisma.NestedBoolFilter<$PrismaModel>
}

export type DateTimeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[]
  notIn?: Date[] | string[]
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeWithAggregatesFilter<$PrismaModel> | Date | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeFilter<$PrismaModel>
}

export type IntNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | null
  notIn?: number[] | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableFilter<$PrismaModel> | number | null
}

export type EnumGenderNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.Gender | Prisma.EnumGenderFieldRefInput<$PrismaModel> | null
  in?: $Enums.Gender[] | null
  notIn?: $Enums.Gender[] | null
  not?: Prisma.NestedEnumGenderNullableFilter<$PrismaModel> | $Enums.Gender | null
}

export type EnumProfileTierFilter<$PrismaModel = never> = {
  equals?: $Enums.ProfileTier | Prisma.EnumProfileTierFieldRefInput<$PrismaModel>
  in?: $Enums.ProfileTier[]
  notIn?: $Enums.ProfileTier[]
  not?: Prisma.NestedEnumProfileTierFilter<$PrismaModel> | $Enums.ProfileTier
}

export type IntNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | null
  notIn?: number[] | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableWithAggregatesFilter<$PrismaModel> | number | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatNullableFilter<$PrismaModel>
  _sum?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _max?: Prisma.NestedIntNullableFilter<$PrismaModel>
}

export type EnumGenderNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.Gender | Prisma.EnumGenderFieldRefInput<$PrismaModel> | null
  in?: $Enums.Gender[] | null
  notIn?: $Enums.Gender[] | null
  not?: Prisma.NestedEnumGenderNullableWithAggregatesFilter<$PrismaModel> | $Enums.Gender | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumGenderNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumGenderNullableFilter<$PrismaModel>
}

export type EnumProfileTierWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.ProfileTier | Prisma.EnumProfileTierFieldRefInput<$PrismaModel>
  in?: $Enums.ProfileTier[]
  notIn?: $Enums.ProfileTier[]
  not?: Prisma.NestedEnumProfileTierWithAggregatesFilter<$PrismaModel> | $Enums.ProfileTier
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumProfileTierFilter<$PrismaModel>
  _max?: Prisma.NestedEnumProfileTierFilter<$PrismaModel>
}

export type EnumLocationTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.LocationType | Prisma.EnumLocationTypeFieldRefInput<$PrismaModel>
  in?: $Enums.LocationType[]
  notIn?: $Enums.LocationType[]
  not?: Prisma.NestedEnumLocationTypeFilter<$PrismaModel> | $Enums.LocationType
}

export type EnumLocationTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.LocationType | Prisma.EnumLocationTypeFieldRefInput<$PrismaModel>
  in?: $Enums.LocationType[]
  notIn?: $Enums.LocationType[]
  not?: Prisma.NestedEnumLocationTypeWithAggregatesFilter<$PrismaModel> | $Enums.LocationType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumLocationTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumLocationTypeFilter<$PrismaModel>
}

export type EnumModerationStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.ModerationStatus | Prisma.EnumModerationStatusFieldRefInput<$PrismaModel>
  in?: $Enums.ModerationStatus[]
  notIn?: $Enums.ModerationStatus[]
  not?: Prisma.NestedEnumModerationStatusFilter<$PrismaModel> | $Enums.ModerationStatus
}

export type EnumModerationStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.ModerationStatus | Prisma.EnumModerationStatusFieldRefInput<$PrismaModel>
  in?: $Enums.ModerationStatus[]
  notIn?: $Enums.ModerationStatus[]
  not?: Prisma.NestedEnumModerationStatusWithAggregatesFilter<$PrismaModel> | $Enums.ModerationStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumModerationStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumModerationStatusFilter<$PrismaModel>
}

export type EnumMediaTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.MediaType | Prisma.EnumMediaTypeFieldRefInput<$PrismaModel>
  in?: $Enums.MediaType[]
  notIn?: $Enums.MediaType[]
  not?: Prisma.NestedEnumMediaTypeFilter<$PrismaModel> | $Enums.MediaType
}

export type EnumReelStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.ReelStatus | Prisma.EnumReelStatusFieldRefInput<$PrismaModel>
  in?: $Enums.ReelStatus[]
  notIn?: $Enums.ReelStatus[]
  not?: Prisma.NestedEnumReelStatusFilter<$PrismaModel> | $Enums.ReelStatus
}

export type EnumMediaTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.MediaType | Prisma.EnumMediaTypeFieldRefInput<$PrismaModel>
  in?: $Enums.MediaType[]
  notIn?: $Enums.MediaType[]
  not?: Prisma.NestedEnumMediaTypeWithAggregatesFilter<$PrismaModel> | $Enums.MediaType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumMediaTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumMediaTypeFilter<$PrismaModel>
}

export type EnumReelStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.ReelStatus | Prisma.EnumReelStatusFieldRefInput<$PrismaModel>
  in?: $Enums.ReelStatus[]
  notIn?: $Enums.ReelStatus[]
  not?: Prisma.NestedEnumReelStatusWithAggregatesFilter<$PrismaModel> | $Enums.ReelStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumReelStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumReelStatusFilter<$PrismaModel>
}

export type EnumCoinTxnTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.CoinTxnType | Prisma.EnumCoinTxnTypeFieldRefInput<$PrismaModel>
  in?: $Enums.CoinTxnType[]
  notIn?: $Enums.CoinTxnType[]
  not?: Prisma.NestedEnumCoinTxnTypeFilter<$PrismaModel> | $Enums.CoinTxnType
}

export type EnumCoinTxnTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.CoinTxnType | Prisma.EnumCoinTxnTypeFieldRefInput<$PrismaModel>
  in?: $Enums.CoinTxnType[]
  notIn?: $Enums.CoinTxnType[]
  not?: Prisma.NestedEnumCoinTxnTypeWithAggregatesFilter<$PrismaModel> | $Enums.CoinTxnType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumCoinTxnTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumCoinTxnTypeFilter<$PrismaModel>
}

export type DecimalFilter<$PrismaModel = never> = {
  equals?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  in?: runtime.Decimal[] | runtime.DecimalJsLike[] | number[] | string[]
  notIn?: runtime.Decimal[] | runtime.DecimalJsLike[] | number[] | string[]
  lt?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  lte?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  gt?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  gte?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDecimalFilter<$PrismaModel> | runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type DecimalWithAggregatesFilter<$PrismaModel = never> = {
  equals?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  in?: runtime.Decimal[] | runtime.DecimalJsLike[] | number[] | string[]
  notIn?: runtime.Decimal[] | runtime.DecimalJsLike[] | number[] | string[]
  lt?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  lte?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  gt?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  gte?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDecimalWithAggregatesFilter<$PrismaModel> | runtime.Decimal | runtime.DecimalJsLike | number | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedDecimalFilter<$PrismaModel>
  _sum?: Prisma.NestedDecimalFilter<$PrismaModel>
  _min?: Prisma.NestedDecimalFilter<$PrismaModel>
  _max?: Prisma.NestedDecimalFilter<$PrismaModel>
}

export type EnumOrderKindFilter<$PrismaModel = never> = {
  equals?: $Enums.OrderKind | Prisma.EnumOrderKindFieldRefInput<$PrismaModel>
  in?: $Enums.OrderKind[]
  notIn?: $Enums.OrderKind[]
  not?: Prisma.NestedEnumOrderKindFilter<$PrismaModel> | $Enums.OrderKind
}

export type EnumOrderStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.OrderStatus | Prisma.EnumOrderStatusFieldRefInput<$PrismaModel>
  in?: $Enums.OrderStatus[]
  notIn?: $Enums.OrderStatus[]
  not?: Prisma.NestedEnumOrderStatusFilter<$PrismaModel> | $Enums.OrderStatus
}

export type EnumOrderKindWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.OrderKind | Prisma.EnumOrderKindFieldRefInput<$PrismaModel>
  in?: $Enums.OrderKind[]
  notIn?: $Enums.OrderKind[]
  not?: Prisma.NestedEnumOrderKindWithAggregatesFilter<$PrismaModel> | $Enums.OrderKind
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumOrderKindFilter<$PrismaModel>
  _max?: Prisma.NestedEnumOrderKindFilter<$PrismaModel>
}

export type EnumOrderStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.OrderStatus | Prisma.EnumOrderStatusFieldRefInput<$PrismaModel>
  in?: $Enums.OrderStatus[]
  notIn?: $Enums.OrderStatus[]
  not?: Prisma.NestedEnumOrderStatusWithAggregatesFilter<$PrismaModel> | $Enums.OrderStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumOrderStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumOrderStatusFilter<$PrismaModel>
}

export type EnumMessageTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.MessageType | Prisma.EnumMessageTypeFieldRefInput<$PrismaModel>
  in?: $Enums.MessageType[]
  notIn?: $Enums.MessageType[]
  not?: Prisma.NestedEnumMessageTypeFilter<$PrismaModel> | $Enums.MessageType
}

export type EnumMessageTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.MessageType | Prisma.EnumMessageTypeFieldRefInput<$PrismaModel>
  in?: $Enums.MessageType[]
  notIn?: $Enums.MessageType[]
  not?: Prisma.NestedEnumMessageTypeWithAggregatesFilter<$PrismaModel> | $Enums.MessageType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumMessageTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumMessageTypeFilter<$PrismaModel>
}

export type EnumInteractionTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.InteractionType | Prisma.EnumInteractionTypeFieldRefInput<$PrismaModel>
  in?: $Enums.InteractionType[]
  notIn?: $Enums.InteractionType[]
  not?: Prisma.NestedEnumInteractionTypeFilter<$PrismaModel> | $Enums.InteractionType
}

export type EnumInteractionTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.InteractionType | Prisma.EnumInteractionTypeFieldRefInput<$PrismaModel>
  in?: $Enums.InteractionType[]
  notIn?: $Enums.InteractionType[]
  not?: Prisma.NestedEnumInteractionTypeWithAggregatesFilter<$PrismaModel> | $Enums.InteractionType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumInteractionTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumInteractionTypeFilter<$PrismaModel>
}

export type EnumReportCategoryFilter<$PrismaModel = never> = {
  equals?: $Enums.ReportCategory | Prisma.EnumReportCategoryFieldRefInput<$PrismaModel>
  in?: $Enums.ReportCategory[]
  notIn?: $Enums.ReportCategory[]
  not?: Prisma.NestedEnumReportCategoryFilter<$PrismaModel> | $Enums.ReportCategory
}

export type EnumReportStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.ReportStatus | Prisma.EnumReportStatusFieldRefInput<$PrismaModel>
  in?: $Enums.ReportStatus[]
  notIn?: $Enums.ReportStatus[]
  not?: Prisma.NestedEnumReportStatusFilter<$PrismaModel> | $Enums.ReportStatus
}

export type EnumReportCategoryWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.ReportCategory | Prisma.EnumReportCategoryFieldRefInput<$PrismaModel>
  in?: $Enums.ReportCategory[]
  notIn?: $Enums.ReportCategory[]
  not?: Prisma.NestedEnumReportCategoryWithAggregatesFilter<$PrismaModel> | $Enums.ReportCategory
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumReportCategoryFilter<$PrismaModel>
  _max?: Prisma.NestedEnumReportCategoryFilter<$PrismaModel>
}

export type EnumReportStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.ReportStatus | Prisma.EnumReportStatusFieldRefInput<$PrismaModel>
  in?: $Enums.ReportStatus[]
  notIn?: $Enums.ReportStatus[]
  not?: Prisma.NestedEnumReportStatusWithAggregatesFilter<$PrismaModel> | $Enums.ReportStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumReportStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumReportStatusFilter<$PrismaModel>
}

export type EnumVerificationTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.VerificationType | Prisma.EnumVerificationTypeFieldRefInput<$PrismaModel>
  in?: $Enums.VerificationType[]
  notIn?: $Enums.VerificationType[]
  not?: Prisma.NestedEnumVerificationTypeFilter<$PrismaModel> | $Enums.VerificationType
}

export type EnumVerificationStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.VerificationStatus | Prisma.EnumVerificationStatusFieldRefInput<$PrismaModel>
  in?: $Enums.VerificationStatus[]
  notIn?: $Enums.VerificationStatus[]
  not?: Prisma.NestedEnumVerificationStatusFilter<$PrismaModel> | $Enums.VerificationStatus
}

export type EnumVerificationTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.VerificationType | Prisma.EnumVerificationTypeFieldRefInput<$PrismaModel>
  in?: $Enums.VerificationType[]
  notIn?: $Enums.VerificationType[]
  not?: Prisma.NestedEnumVerificationTypeWithAggregatesFilter<$PrismaModel> | $Enums.VerificationType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumVerificationTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumVerificationTypeFilter<$PrismaModel>
}

export type EnumVerificationStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.VerificationStatus | Prisma.EnumVerificationStatusFieldRefInput<$PrismaModel>
  in?: $Enums.VerificationStatus[]
  notIn?: $Enums.VerificationStatus[]
  not?: Prisma.NestedEnumVerificationStatusWithAggregatesFilter<$PrismaModel> | $Enums.VerificationStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumVerificationStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumVerificationStatusFilter<$PrismaModel>
}

export type EnumAdPlacementFilter<$PrismaModel = never> = {
  equals?: $Enums.AdPlacement | Prisma.EnumAdPlacementFieldRefInput<$PrismaModel>
  in?: $Enums.AdPlacement[]
  notIn?: $Enums.AdPlacement[]
  not?: Prisma.NestedEnumAdPlacementFilter<$PrismaModel> | $Enums.AdPlacement
}

export type EnumAdPlacementWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.AdPlacement | Prisma.EnumAdPlacementFieldRefInput<$PrismaModel>
  in?: $Enums.AdPlacement[]
  notIn?: $Enums.AdPlacement[]
  not?: Prisma.NestedEnumAdPlacementWithAggregatesFilter<$PrismaModel> | $Enums.AdPlacement
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumAdPlacementFilter<$PrismaModel>
  _max?: Prisma.NestedEnumAdPlacementFilter<$PrismaModel>
}

export type EnumModRuleKindFilter<$PrismaModel = never> = {
  equals?: $Enums.ModRuleKind | Prisma.EnumModRuleKindFieldRefInput<$PrismaModel>
  in?: $Enums.ModRuleKind[]
  notIn?: $Enums.ModRuleKind[]
  not?: Prisma.NestedEnumModRuleKindFilter<$PrismaModel> | $Enums.ModRuleKind
}

export type EnumModActionFilter<$PrismaModel = never> = {
  equals?: $Enums.ModAction | Prisma.EnumModActionFieldRefInput<$PrismaModel>
  in?: $Enums.ModAction[]
  notIn?: $Enums.ModAction[]
  not?: Prisma.NestedEnumModActionFilter<$PrismaModel> | $Enums.ModAction
}

export type EnumModRuleKindWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.ModRuleKind | Prisma.EnumModRuleKindFieldRefInput<$PrismaModel>
  in?: $Enums.ModRuleKind[]
  notIn?: $Enums.ModRuleKind[]
  not?: Prisma.NestedEnumModRuleKindWithAggregatesFilter<$PrismaModel> | $Enums.ModRuleKind
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumModRuleKindFilter<$PrismaModel>
  _max?: Prisma.NestedEnumModRuleKindFilter<$PrismaModel>
}

export type EnumModActionWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.ModAction | Prisma.EnumModActionFieldRefInput<$PrismaModel>
  in?: $Enums.ModAction[]
  notIn?: $Enums.ModAction[]
  not?: Prisma.NestedEnumModActionWithAggregatesFilter<$PrismaModel> | $Enums.ModAction
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumModActionFilter<$PrismaModel>
  _max?: Prisma.NestedEnumModActionFilter<$PrismaModel>
}

export type EnumLaunchModeFilter<$PrismaModel = never> = {
  equals?: $Enums.LaunchMode | Prisma.EnumLaunchModeFieldRefInput<$PrismaModel>
  in?: $Enums.LaunchMode[]
  notIn?: $Enums.LaunchMode[]
  not?: Prisma.NestedEnumLaunchModeFilter<$PrismaModel> | $Enums.LaunchMode
}

export type EnumLaunchModeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.LaunchMode | Prisma.EnumLaunchModeFieldRefInput<$PrismaModel>
  in?: $Enums.LaunchMode[]
  notIn?: $Enums.LaunchMode[]
  not?: Prisma.NestedEnumLaunchModeWithAggregatesFilter<$PrismaModel> | $Enums.LaunchMode
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumLaunchModeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumLaunchModeFilter<$PrismaModel>
}

export type EnumSupportTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.SupportType | Prisma.EnumSupportTypeFieldRefInput<$PrismaModel>
  in?: $Enums.SupportType[]
  notIn?: $Enums.SupportType[]
  not?: Prisma.NestedEnumSupportTypeFilter<$PrismaModel> | $Enums.SupportType
}

export type EnumSupportStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.SupportStatus | Prisma.EnumSupportStatusFieldRefInput<$PrismaModel>
  in?: $Enums.SupportStatus[]
  notIn?: $Enums.SupportStatus[]
  not?: Prisma.NestedEnumSupportStatusFilter<$PrismaModel> | $Enums.SupportStatus
}

export type EnumSupportTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.SupportType | Prisma.EnumSupportTypeFieldRefInput<$PrismaModel>
  in?: $Enums.SupportType[]
  notIn?: $Enums.SupportType[]
  not?: Prisma.NestedEnumSupportTypeWithAggregatesFilter<$PrismaModel> | $Enums.SupportType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumSupportTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumSupportTypeFilter<$PrismaModel>
}

export type EnumSupportStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.SupportStatus | Prisma.EnumSupportStatusFieldRefInput<$PrismaModel>
  in?: $Enums.SupportStatus[]
  notIn?: $Enums.SupportStatus[]
  not?: Prisma.NestedEnumSupportStatusWithAggregatesFilter<$PrismaModel> | $Enums.SupportStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumSupportStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumSupportStatusFilter<$PrismaModel>
}

export type NestedStringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[]
  notIn?: string[]
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  search?: string
  not?: Prisma.NestedStringFilter<$PrismaModel> | string
}

export type NestedStringNullableFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | null
  notIn?: string[] | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  search?: string
  not?: Prisma.NestedStringNullableFilter<$PrismaModel> | string | null
}

export type NestedEnumUserRoleFilter<$PrismaModel = never> = {
  equals?: $Enums.UserRole | Prisma.EnumUserRoleFieldRefInput<$PrismaModel>
  in?: $Enums.UserRole[]
  notIn?: $Enums.UserRole[]
  not?: Prisma.NestedEnumUserRoleFilter<$PrismaModel> | $Enums.UserRole
}

export type NestedEnumAccountStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.AccountStatus | Prisma.EnumAccountStatusFieldRefInput<$PrismaModel>
  in?: $Enums.AccountStatus[]
  notIn?: $Enums.AccountStatus[]
  not?: Prisma.NestedEnumAccountStatusFilter<$PrismaModel> | $Enums.AccountStatus
}

export type NestedDateTimeNullableFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | null
  notIn?: Date[] | string[] | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableFilter<$PrismaModel> | Date | string | null
}

export type NestedEnumMembershipLevelFilter<$PrismaModel = never> = {
  equals?: $Enums.MembershipLevel | Prisma.EnumMembershipLevelFieldRefInput<$PrismaModel>
  in?: $Enums.MembershipLevel[]
  notIn?: $Enums.MembershipLevel[]
  not?: Prisma.NestedEnumMembershipLevelFilter<$PrismaModel> | $Enums.MembershipLevel
}

export type NestedIntFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[]
  notIn?: number[]
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntFilter<$PrismaModel> | number
}

export type NestedBoolFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolFilter<$PrismaModel> | boolean
}

export type NestedDateTimeFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[]
  notIn?: Date[] | string[]
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeFilter<$PrismaModel> | Date | string
}

export type NestedStringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[]
  notIn?: string[]
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  search?: string
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedStringFilter<$PrismaModel>
  _max?: Prisma.NestedStringFilter<$PrismaModel>
}

export type NestedStringNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | null
  notIn?: string[] | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  search?: string
  not?: Prisma.NestedStringNullableWithAggregatesFilter<$PrismaModel> | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedStringNullableFilter<$PrismaModel>
  _max?: Prisma.NestedStringNullableFilter<$PrismaModel>
}

export type NestedIntNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | null
  notIn?: number[] | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableFilter<$PrismaModel> | number | null
}

export type NestedEnumUserRoleWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.UserRole | Prisma.EnumUserRoleFieldRefInput<$PrismaModel>
  in?: $Enums.UserRole[]
  notIn?: $Enums.UserRole[]
  not?: Prisma.NestedEnumUserRoleWithAggregatesFilter<$PrismaModel> | $Enums.UserRole
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumUserRoleFilter<$PrismaModel>
  _max?: Prisma.NestedEnumUserRoleFilter<$PrismaModel>
}

export type NestedEnumAccountStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.AccountStatus | Prisma.EnumAccountStatusFieldRefInput<$PrismaModel>
  in?: $Enums.AccountStatus[]
  notIn?: $Enums.AccountStatus[]
  not?: Prisma.NestedEnumAccountStatusWithAggregatesFilter<$PrismaModel> | $Enums.AccountStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumAccountStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumAccountStatusFilter<$PrismaModel>
}

export type NestedDateTimeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | null
  notIn?: Date[] | string[] | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableWithAggregatesFilter<$PrismaModel> | Date | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
}

export type NestedEnumMembershipLevelWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.MembershipLevel | Prisma.EnumMembershipLevelFieldRefInput<$PrismaModel>
  in?: $Enums.MembershipLevel[]
  notIn?: $Enums.MembershipLevel[]
  not?: Prisma.NestedEnumMembershipLevelWithAggregatesFilter<$PrismaModel> | $Enums.MembershipLevel
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumMembershipLevelFilter<$PrismaModel>
  _max?: Prisma.NestedEnumMembershipLevelFilter<$PrismaModel>
}

export type NestedIntWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[]
  notIn?: number[]
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntWithAggregatesFilter<$PrismaModel> | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedIntFilter<$PrismaModel>
  _max?: Prisma.NestedIntFilter<$PrismaModel>
}

export type NestedFloatFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  in?: number[]
  notIn?: number[]
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatFilter<$PrismaModel> | number
}

export type NestedBoolWithAggregatesFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolWithAggregatesFilter<$PrismaModel> | boolean
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedBoolFilter<$PrismaModel>
  _max?: Prisma.NestedBoolFilter<$PrismaModel>
}

export type NestedDateTimeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[]
  notIn?: Date[] | string[]
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeWithAggregatesFilter<$PrismaModel> | Date | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeFilter<$PrismaModel>
}

export type NestedEnumGenderNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.Gender | Prisma.EnumGenderFieldRefInput<$PrismaModel> | null
  in?: $Enums.Gender[] | null
  notIn?: $Enums.Gender[] | null
  not?: Prisma.NestedEnumGenderNullableFilter<$PrismaModel> | $Enums.Gender | null
}

export type NestedEnumProfileTierFilter<$PrismaModel = never> = {
  equals?: $Enums.ProfileTier | Prisma.EnumProfileTierFieldRefInput<$PrismaModel>
  in?: $Enums.ProfileTier[]
  notIn?: $Enums.ProfileTier[]
  not?: Prisma.NestedEnumProfileTierFilter<$PrismaModel> | $Enums.ProfileTier
}

export type NestedIntNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | null
  notIn?: number[] | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableWithAggregatesFilter<$PrismaModel> | number | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatNullableFilter<$PrismaModel>
  _sum?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _max?: Prisma.NestedIntNullableFilter<$PrismaModel>
}

export type NestedFloatNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel> | null
  in?: number[] | null
  notIn?: number[] | null
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatNullableFilter<$PrismaModel> | number | null
}

export type NestedEnumGenderNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.Gender | Prisma.EnumGenderFieldRefInput<$PrismaModel> | null
  in?: $Enums.Gender[] | null
  notIn?: $Enums.Gender[] | null
  not?: Prisma.NestedEnumGenderNullableWithAggregatesFilter<$PrismaModel> | $Enums.Gender | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumGenderNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumGenderNullableFilter<$PrismaModel>
}

export type NestedEnumProfileTierWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.ProfileTier | Prisma.EnumProfileTierFieldRefInput<$PrismaModel>
  in?: $Enums.ProfileTier[]
  notIn?: $Enums.ProfileTier[]
  not?: Prisma.NestedEnumProfileTierWithAggregatesFilter<$PrismaModel> | $Enums.ProfileTier
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumProfileTierFilter<$PrismaModel>
  _max?: Prisma.NestedEnumProfileTierFilter<$PrismaModel>
}

export type NestedEnumLocationTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.LocationType | Prisma.EnumLocationTypeFieldRefInput<$PrismaModel>
  in?: $Enums.LocationType[]
  notIn?: $Enums.LocationType[]
  not?: Prisma.NestedEnumLocationTypeFilter<$PrismaModel> | $Enums.LocationType
}

export type NestedEnumLocationTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.LocationType | Prisma.EnumLocationTypeFieldRefInput<$PrismaModel>
  in?: $Enums.LocationType[]
  notIn?: $Enums.LocationType[]
  not?: Prisma.NestedEnumLocationTypeWithAggregatesFilter<$PrismaModel> | $Enums.LocationType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumLocationTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumLocationTypeFilter<$PrismaModel>
}

export type NestedEnumModerationStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.ModerationStatus | Prisma.EnumModerationStatusFieldRefInput<$PrismaModel>
  in?: $Enums.ModerationStatus[]
  notIn?: $Enums.ModerationStatus[]
  not?: Prisma.NestedEnumModerationStatusFilter<$PrismaModel> | $Enums.ModerationStatus
}

export type NestedEnumModerationStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.ModerationStatus | Prisma.EnumModerationStatusFieldRefInput<$PrismaModel>
  in?: $Enums.ModerationStatus[]
  notIn?: $Enums.ModerationStatus[]
  not?: Prisma.NestedEnumModerationStatusWithAggregatesFilter<$PrismaModel> | $Enums.ModerationStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumModerationStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumModerationStatusFilter<$PrismaModel>
}

export type NestedEnumMediaTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.MediaType | Prisma.EnumMediaTypeFieldRefInput<$PrismaModel>
  in?: $Enums.MediaType[]
  notIn?: $Enums.MediaType[]
  not?: Prisma.NestedEnumMediaTypeFilter<$PrismaModel> | $Enums.MediaType
}

export type NestedEnumReelStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.ReelStatus | Prisma.EnumReelStatusFieldRefInput<$PrismaModel>
  in?: $Enums.ReelStatus[]
  notIn?: $Enums.ReelStatus[]
  not?: Prisma.NestedEnumReelStatusFilter<$PrismaModel> | $Enums.ReelStatus
}

export type NestedEnumMediaTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.MediaType | Prisma.EnumMediaTypeFieldRefInput<$PrismaModel>
  in?: $Enums.MediaType[]
  notIn?: $Enums.MediaType[]
  not?: Prisma.NestedEnumMediaTypeWithAggregatesFilter<$PrismaModel> | $Enums.MediaType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumMediaTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumMediaTypeFilter<$PrismaModel>
}

export type NestedEnumReelStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.ReelStatus | Prisma.EnumReelStatusFieldRefInput<$PrismaModel>
  in?: $Enums.ReelStatus[]
  notIn?: $Enums.ReelStatus[]
  not?: Prisma.NestedEnumReelStatusWithAggregatesFilter<$PrismaModel> | $Enums.ReelStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumReelStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumReelStatusFilter<$PrismaModel>
}

export type NestedEnumCoinTxnTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.CoinTxnType | Prisma.EnumCoinTxnTypeFieldRefInput<$PrismaModel>
  in?: $Enums.CoinTxnType[]
  notIn?: $Enums.CoinTxnType[]
  not?: Prisma.NestedEnumCoinTxnTypeFilter<$PrismaModel> | $Enums.CoinTxnType
}

export type NestedEnumCoinTxnTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.CoinTxnType | Prisma.EnumCoinTxnTypeFieldRefInput<$PrismaModel>
  in?: $Enums.CoinTxnType[]
  notIn?: $Enums.CoinTxnType[]
  not?: Prisma.NestedEnumCoinTxnTypeWithAggregatesFilter<$PrismaModel> | $Enums.CoinTxnType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumCoinTxnTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumCoinTxnTypeFilter<$PrismaModel>
}

export type NestedDecimalFilter<$PrismaModel = never> = {
  equals?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  in?: runtime.Decimal[] | runtime.DecimalJsLike[] | number[] | string[]
  notIn?: runtime.Decimal[] | runtime.DecimalJsLike[] | number[] | string[]
  lt?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  lte?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  gt?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  gte?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDecimalFilter<$PrismaModel> | runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type NestedDecimalWithAggregatesFilter<$PrismaModel = never> = {
  equals?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  in?: runtime.Decimal[] | runtime.DecimalJsLike[] | number[] | string[]
  notIn?: runtime.Decimal[] | runtime.DecimalJsLike[] | number[] | string[]
  lt?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  lte?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  gt?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  gte?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDecimalWithAggregatesFilter<$PrismaModel> | runtime.Decimal | runtime.DecimalJsLike | number | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedDecimalFilter<$PrismaModel>
  _sum?: Prisma.NestedDecimalFilter<$PrismaModel>
  _min?: Prisma.NestedDecimalFilter<$PrismaModel>
  _max?: Prisma.NestedDecimalFilter<$PrismaModel>
}

export type NestedEnumOrderKindFilter<$PrismaModel = never> = {
  equals?: $Enums.OrderKind | Prisma.EnumOrderKindFieldRefInput<$PrismaModel>
  in?: $Enums.OrderKind[]
  notIn?: $Enums.OrderKind[]
  not?: Prisma.NestedEnumOrderKindFilter<$PrismaModel> | $Enums.OrderKind
}

export type NestedEnumOrderStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.OrderStatus | Prisma.EnumOrderStatusFieldRefInput<$PrismaModel>
  in?: $Enums.OrderStatus[]
  notIn?: $Enums.OrderStatus[]
  not?: Prisma.NestedEnumOrderStatusFilter<$PrismaModel> | $Enums.OrderStatus
}

export type NestedEnumOrderKindWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.OrderKind | Prisma.EnumOrderKindFieldRefInput<$PrismaModel>
  in?: $Enums.OrderKind[]
  notIn?: $Enums.OrderKind[]
  not?: Prisma.NestedEnumOrderKindWithAggregatesFilter<$PrismaModel> | $Enums.OrderKind
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumOrderKindFilter<$PrismaModel>
  _max?: Prisma.NestedEnumOrderKindFilter<$PrismaModel>
}

export type NestedEnumOrderStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.OrderStatus | Prisma.EnumOrderStatusFieldRefInput<$PrismaModel>
  in?: $Enums.OrderStatus[]
  notIn?: $Enums.OrderStatus[]
  not?: Prisma.NestedEnumOrderStatusWithAggregatesFilter<$PrismaModel> | $Enums.OrderStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumOrderStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumOrderStatusFilter<$PrismaModel>
}

export type NestedEnumMessageTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.MessageType | Prisma.EnumMessageTypeFieldRefInput<$PrismaModel>
  in?: $Enums.MessageType[]
  notIn?: $Enums.MessageType[]
  not?: Prisma.NestedEnumMessageTypeFilter<$PrismaModel> | $Enums.MessageType
}

export type NestedEnumMessageTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.MessageType | Prisma.EnumMessageTypeFieldRefInput<$PrismaModel>
  in?: $Enums.MessageType[]
  notIn?: $Enums.MessageType[]
  not?: Prisma.NestedEnumMessageTypeWithAggregatesFilter<$PrismaModel> | $Enums.MessageType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumMessageTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumMessageTypeFilter<$PrismaModel>
}

export type NestedEnumInteractionTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.InteractionType | Prisma.EnumInteractionTypeFieldRefInput<$PrismaModel>
  in?: $Enums.InteractionType[]
  notIn?: $Enums.InteractionType[]
  not?: Prisma.NestedEnumInteractionTypeFilter<$PrismaModel> | $Enums.InteractionType
}

export type NestedEnumInteractionTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.InteractionType | Prisma.EnumInteractionTypeFieldRefInput<$PrismaModel>
  in?: $Enums.InteractionType[]
  notIn?: $Enums.InteractionType[]
  not?: Prisma.NestedEnumInteractionTypeWithAggregatesFilter<$PrismaModel> | $Enums.InteractionType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumInteractionTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumInteractionTypeFilter<$PrismaModel>
}

export type NestedEnumReportCategoryFilter<$PrismaModel = never> = {
  equals?: $Enums.ReportCategory | Prisma.EnumReportCategoryFieldRefInput<$PrismaModel>
  in?: $Enums.ReportCategory[]
  notIn?: $Enums.ReportCategory[]
  not?: Prisma.NestedEnumReportCategoryFilter<$PrismaModel> | $Enums.ReportCategory
}

export type NestedEnumReportStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.ReportStatus | Prisma.EnumReportStatusFieldRefInput<$PrismaModel>
  in?: $Enums.ReportStatus[]
  notIn?: $Enums.ReportStatus[]
  not?: Prisma.NestedEnumReportStatusFilter<$PrismaModel> | $Enums.ReportStatus
}

export type NestedEnumReportCategoryWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.ReportCategory | Prisma.EnumReportCategoryFieldRefInput<$PrismaModel>
  in?: $Enums.ReportCategory[]
  notIn?: $Enums.ReportCategory[]
  not?: Prisma.NestedEnumReportCategoryWithAggregatesFilter<$PrismaModel> | $Enums.ReportCategory
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumReportCategoryFilter<$PrismaModel>
  _max?: Prisma.NestedEnumReportCategoryFilter<$PrismaModel>
}

export type NestedEnumReportStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.ReportStatus | Prisma.EnumReportStatusFieldRefInput<$PrismaModel>
  in?: $Enums.ReportStatus[]
  notIn?: $Enums.ReportStatus[]
  not?: Prisma.NestedEnumReportStatusWithAggregatesFilter<$PrismaModel> | $Enums.ReportStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumReportStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumReportStatusFilter<$PrismaModel>
}

export type NestedEnumVerificationTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.VerificationType | Prisma.EnumVerificationTypeFieldRefInput<$PrismaModel>
  in?: $Enums.VerificationType[]
  notIn?: $Enums.VerificationType[]
  not?: Prisma.NestedEnumVerificationTypeFilter<$PrismaModel> | $Enums.VerificationType
}

export type NestedEnumVerificationStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.VerificationStatus | Prisma.EnumVerificationStatusFieldRefInput<$PrismaModel>
  in?: $Enums.VerificationStatus[]
  notIn?: $Enums.VerificationStatus[]
  not?: Prisma.NestedEnumVerificationStatusFilter<$PrismaModel> | $Enums.VerificationStatus
}

export type NestedEnumVerificationTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.VerificationType | Prisma.EnumVerificationTypeFieldRefInput<$PrismaModel>
  in?: $Enums.VerificationType[]
  notIn?: $Enums.VerificationType[]
  not?: Prisma.NestedEnumVerificationTypeWithAggregatesFilter<$PrismaModel> | $Enums.VerificationType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumVerificationTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumVerificationTypeFilter<$PrismaModel>
}

export type NestedEnumVerificationStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.VerificationStatus | Prisma.EnumVerificationStatusFieldRefInput<$PrismaModel>
  in?: $Enums.VerificationStatus[]
  notIn?: $Enums.VerificationStatus[]
  not?: Prisma.NestedEnumVerificationStatusWithAggregatesFilter<$PrismaModel> | $Enums.VerificationStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumVerificationStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumVerificationStatusFilter<$PrismaModel>
}

export type NestedEnumAdPlacementFilter<$PrismaModel = never> = {
  equals?: $Enums.AdPlacement | Prisma.EnumAdPlacementFieldRefInput<$PrismaModel>
  in?: $Enums.AdPlacement[]
  notIn?: $Enums.AdPlacement[]
  not?: Prisma.NestedEnumAdPlacementFilter<$PrismaModel> | $Enums.AdPlacement
}

export type NestedEnumAdPlacementWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.AdPlacement | Prisma.EnumAdPlacementFieldRefInput<$PrismaModel>
  in?: $Enums.AdPlacement[]
  notIn?: $Enums.AdPlacement[]
  not?: Prisma.NestedEnumAdPlacementWithAggregatesFilter<$PrismaModel> | $Enums.AdPlacement
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumAdPlacementFilter<$PrismaModel>
  _max?: Prisma.NestedEnumAdPlacementFilter<$PrismaModel>
}

export type NestedEnumModRuleKindFilter<$PrismaModel = never> = {
  equals?: $Enums.ModRuleKind | Prisma.EnumModRuleKindFieldRefInput<$PrismaModel>
  in?: $Enums.ModRuleKind[]
  notIn?: $Enums.ModRuleKind[]
  not?: Prisma.NestedEnumModRuleKindFilter<$PrismaModel> | $Enums.ModRuleKind
}

export type NestedEnumModActionFilter<$PrismaModel = never> = {
  equals?: $Enums.ModAction | Prisma.EnumModActionFieldRefInput<$PrismaModel>
  in?: $Enums.ModAction[]
  notIn?: $Enums.ModAction[]
  not?: Prisma.NestedEnumModActionFilter<$PrismaModel> | $Enums.ModAction
}

export type NestedEnumModRuleKindWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.ModRuleKind | Prisma.EnumModRuleKindFieldRefInput<$PrismaModel>
  in?: $Enums.ModRuleKind[]
  notIn?: $Enums.ModRuleKind[]
  not?: Prisma.NestedEnumModRuleKindWithAggregatesFilter<$PrismaModel> | $Enums.ModRuleKind
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumModRuleKindFilter<$PrismaModel>
  _max?: Prisma.NestedEnumModRuleKindFilter<$PrismaModel>
}

export type NestedEnumModActionWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.ModAction | Prisma.EnumModActionFieldRefInput<$PrismaModel>
  in?: $Enums.ModAction[]
  notIn?: $Enums.ModAction[]
  not?: Prisma.NestedEnumModActionWithAggregatesFilter<$PrismaModel> | $Enums.ModAction
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumModActionFilter<$PrismaModel>
  _max?: Prisma.NestedEnumModActionFilter<$PrismaModel>
}

export type NestedEnumLaunchModeFilter<$PrismaModel = never> = {
  equals?: $Enums.LaunchMode | Prisma.EnumLaunchModeFieldRefInput<$PrismaModel>
  in?: $Enums.LaunchMode[]
  notIn?: $Enums.LaunchMode[]
  not?: Prisma.NestedEnumLaunchModeFilter<$PrismaModel> | $Enums.LaunchMode
}

export type NestedEnumLaunchModeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.LaunchMode | Prisma.EnumLaunchModeFieldRefInput<$PrismaModel>
  in?: $Enums.LaunchMode[]
  notIn?: $Enums.LaunchMode[]
  not?: Prisma.NestedEnumLaunchModeWithAggregatesFilter<$PrismaModel> | $Enums.LaunchMode
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumLaunchModeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumLaunchModeFilter<$PrismaModel>
}

export type NestedEnumSupportTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.SupportType | Prisma.EnumSupportTypeFieldRefInput<$PrismaModel>
  in?: $Enums.SupportType[]
  notIn?: $Enums.SupportType[]
  not?: Prisma.NestedEnumSupportTypeFilter<$PrismaModel> | $Enums.SupportType
}

export type NestedEnumSupportStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.SupportStatus | Prisma.EnumSupportStatusFieldRefInput<$PrismaModel>
  in?: $Enums.SupportStatus[]
  notIn?: $Enums.SupportStatus[]
  not?: Prisma.NestedEnumSupportStatusFilter<$PrismaModel> | $Enums.SupportStatus
}

export type NestedEnumSupportTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.SupportType | Prisma.EnumSupportTypeFieldRefInput<$PrismaModel>
  in?: $Enums.SupportType[]
  notIn?: $Enums.SupportType[]
  not?: Prisma.NestedEnumSupportTypeWithAggregatesFilter<$PrismaModel> | $Enums.SupportType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumSupportTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumSupportTypeFilter<$PrismaModel>
}

export type NestedEnumSupportStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.SupportStatus | Prisma.EnumSupportStatusFieldRefInput<$PrismaModel>
  in?: $Enums.SupportStatus[]
  notIn?: $Enums.SupportStatus[]
  not?: Prisma.NestedEnumSupportStatusWithAggregatesFilter<$PrismaModel> | $Enums.SupportStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumSupportStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumSupportStatusFilter<$PrismaModel>
}


