
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AdImpression` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model AdImpression
 * 
 */
export type AdImpressionModel = runtime.Types.Result.DefaultSelection<Prisma.$AdImpressionPayload>

export type AggregateAdImpression = {
  _count: AdImpressionCountAggregateOutputType | null
  _min: AdImpressionMinAggregateOutputType | null
  _max: AdImpressionMaxAggregateOutputType | null
}

export type AdImpressionMinAggregateOutputType = {
  id: string | null
  adId: string | null
  userId: string | null
  createdAt: Date | null
}

export type AdImpressionMaxAggregateOutputType = {
  id: string | null
  adId: string | null
  userId: string | null
  createdAt: Date | null
}

export type AdImpressionCountAggregateOutputType = {
  id: number
  adId: number
  userId: number
  createdAt: number
  _all: number
}


export type AdImpressionMinAggregateInputType = {
  id?: true
  adId?: true
  userId?: true
  createdAt?: true
}

export type AdImpressionMaxAggregateInputType = {
  id?: true
  adId?: true
  userId?: true
  createdAt?: true
}

export type AdImpressionCountAggregateInputType = {
  id?: true
  adId?: true
  userId?: true
  createdAt?: true
  _all?: true
}

export type AdImpressionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AdImpression to aggregate.
   */
  where?: Prisma.AdImpressionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AdImpressions to fetch.
   */
  orderBy?: Prisma.AdImpressionOrderByWithRelationInput | Prisma.AdImpressionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AdImpressionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AdImpressions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AdImpressions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AdImpressions
  **/
  _count?: true | AdImpressionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AdImpressionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AdImpressionMaxAggregateInputType
}

export type GetAdImpressionAggregateType<T extends AdImpressionAggregateArgs> = {
      [P in keyof T & keyof AggregateAdImpression]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAdImpression[P]>
    : Prisma.GetScalarType<T[P], AggregateAdImpression[P]>
}




export type AdImpressionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AdImpressionWhereInput
  orderBy?: Prisma.AdImpressionOrderByWithAggregationInput | Prisma.AdImpressionOrderByWithAggregationInput[]
  by: Prisma.AdImpressionScalarFieldEnum[] | Prisma.AdImpressionScalarFieldEnum
  having?: Prisma.AdImpressionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AdImpressionCountAggregateInputType | true
  _min?: AdImpressionMinAggregateInputType
  _max?: AdImpressionMaxAggregateInputType
}

export type AdImpressionGroupByOutputType = {
  id: string
  adId: string
  userId: string | null
  createdAt: Date
  _count: AdImpressionCountAggregateOutputType | null
  _min: AdImpressionMinAggregateOutputType | null
  _max: AdImpressionMaxAggregateOutputType | null
}

export type GetAdImpressionGroupByPayload<T extends AdImpressionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AdImpressionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AdImpressionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AdImpressionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AdImpressionGroupByOutputType[P]>
      }
    >
  >



export type AdImpressionWhereInput = {
  AND?: Prisma.AdImpressionWhereInput | Prisma.AdImpressionWhereInput[]
  OR?: Prisma.AdImpressionWhereInput[]
  NOT?: Prisma.AdImpressionWhereInput | Prisma.AdImpressionWhereInput[]
  id?: Prisma.StringFilter<"AdImpression"> | string
  adId?: Prisma.StringFilter<"AdImpression"> | string
  userId?: Prisma.StringNullableFilter<"AdImpression"> | string | null
  createdAt?: Prisma.DateTimeFilter<"AdImpression"> | Date | string
  ad?: Prisma.XOR<Prisma.AdScalarRelationFilter, Prisma.AdWhereInput>
  user?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}

export type AdImpressionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  adId?: Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  ad?: Prisma.AdOrderByWithRelationInput
  user?: Prisma.UserOrderByWithRelationInput
  _relevance?: Prisma.AdImpressionOrderByRelevanceInput
}

export type AdImpressionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.AdImpressionWhereInput | Prisma.AdImpressionWhereInput[]
  OR?: Prisma.AdImpressionWhereInput[]
  NOT?: Prisma.AdImpressionWhereInput | Prisma.AdImpressionWhereInput[]
  adId?: Prisma.StringFilter<"AdImpression"> | string
  userId?: Prisma.StringNullableFilter<"AdImpression"> | string | null
  createdAt?: Prisma.DateTimeFilter<"AdImpression"> | Date | string
  ad?: Prisma.XOR<Prisma.AdScalarRelationFilter, Prisma.AdWhereInput>
  user?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}, "id">

export type AdImpressionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  adId?: Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.AdImpressionCountOrderByAggregateInput
  _max?: Prisma.AdImpressionMaxOrderByAggregateInput
  _min?: Prisma.AdImpressionMinOrderByAggregateInput
}

export type AdImpressionScalarWhereWithAggregatesInput = {
  AND?: Prisma.AdImpressionScalarWhereWithAggregatesInput | Prisma.AdImpressionScalarWhereWithAggregatesInput[]
  OR?: Prisma.AdImpressionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AdImpressionScalarWhereWithAggregatesInput | Prisma.AdImpressionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"AdImpression"> | string
  adId?: Prisma.StringWithAggregatesFilter<"AdImpression"> | string
  userId?: Prisma.StringNullableWithAggregatesFilter<"AdImpression"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"AdImpression"> | Date | string
}

export type AdImpressionCreateInput = {
  id?: string
  createdAt?: Date | string
  ad: Prisma.AdCreateNestedOneWithoutImpressionsInput
  user?: Prisma.UserCreateNestedOneWithoutAdImpressionsInput
}

export type AdImpressionUncheckedCreateInput = {
  id?: string
  adId: string
  userId?: string | null
  createdAt?: Date | string
}

export type AdImpressionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ad?: Prisma.AdUpdateOneRequiredWithoutImpressionsNestedInput
  user?: Prisma.UserUpdateOneWithoutAdImpressionsNestedInput
}

export type AdImpressionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  adId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AdImpressionCreateManyInput = {
  id?: string
  adId: string
  userId?: string | null
  createdAt?: Date | string
}

export type AdImpressionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AdImpressionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  adId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AdImpressionListRelationFilter = {
  every?: Prisma.AdImpressionWhereInput
  some?: Prisma.AdImpressionWhereInput
  none?: Prisma.AdImpressionWhereInput
}

export type AdImpressionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AdImpressionOrderByRelevanceInput = {
  fields: Prisma.AdImpressionOrderByRelevanceFieldEnum | Prisma.AdImpressionOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type AdImpressionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  adId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AdImpressionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  adId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AdImpressionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  adId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AdImpressionCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.AdImpressionCreateWithoutUserInput, Prisma.AdImpressionUncheckedCreateWithoutUserInput> | Prisma.AdImpressionCreateWithoutUserInput[] | Prisma.AdImpressionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AdImpressionCreateOrConnectWithoutUserInput | Prisma.AdImpressionCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.AdImpressionCreateManyUserInputEnvelope
  connect?: Prisma.AdImpressionWhereUniqueInput | Prisma.AdImpressionWhereUniqueInput[]
}

export type AdImpressionUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.AdImpressionCreateWithoutUserInput, Prisma.AdImpressionUncheckedCreateWithoutUserInput> | Prisma.AdImpressionCreateWithoutUserInput[] | Prisma.AdImpressionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AdImpressionCreateOrConnectWithoutUserInput | Prisma.AdImpressionCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.AdImpressionCreateManyUserInputEnvelope
  connect?: Prisma.AdImpressionWhereUniqueInput | Prisma.AdImpressionWhereUniqueInput[]
}

export type AdImpressionUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.AdImpressionCreateWithoutUserInput, Prisma.AdImpressionUncheckedCreateWithoutUserInput> | Prisma.AdImpressionCreateWithoutUserInput[] | Prisma.AdImpressionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AdImpressionCreateOrConnectWithoutUserInput | Prisma.AdImpressionCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.AdImpressionUpsertWithWhereUniqueWithoutUserInput | Prisma.AdImpressionUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.AdImpressionCreateManyUserInputEnvelope
  set?: Prisma.AdImpressionWhereUniqueInput | Prisma.AdImpressionWhereUniqueInput[]
  disconnect?: Prisma.AdImpressionWhereUniqueInput | Prisma.AdImpressionWhereUniqueInput[]
  delete?: Prisma.AdImpressionWhereUniqueInput | Prisma.AdImpressionWhereUniqueInput[]
  connect?: Prisma.AdImpressionWhereUniqueInput | Prisma.AdImpressionWhereUniqueInput[]
  update?: Prisma.AdImpressionUpdateWithWhereUniqueWithoutUserInput | Prisma.AdImpressionUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.AdImpressionUpdateManyWithWhereWithoutUserInput | Prisma.AdImpressionUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.AdImpressionScalarWhereInput | Prisma.AdImpressionScalarWhereInput[]
}

export type AdImpressionUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.AdImpressionCreateWithoutUserInput, Prisma.AdImpressionUncheckedCreateWithoutUserInput> | Prisma.AdImpressionCreateWithoutUserInput[] | Prisma.AdImpressionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AdImpressionCreateOrConnectWithoutUserInput | Prisma.AdImpressionCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.AdImpressionUpsertWithWhereUniqueWithoutUserInput | Prisma.AdImpressionUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.AdImpressionCreateManyUserInputEnvelope
  set?: Prisma.AdImpressionWhereUniqueInput | Prisma.AdImpressionWhereUniqueInput[]
  disconnect?: Prisma.AdImpressionWhereUniqueInput | Prisma.AdImpressionWhereUniqueInput[]
  delete?: Prisma.AdImpressionWhereUniqueInput | Prisma.AdImpressionWhereUniqueInput[]
  connect?: Prisma.AdImpressionWhereUniqueInput | Prisma.AdImpressionWhereUniqueInput[]
  update?: Prisma.AdImpressionUpdateWithWhereUniqueWithoutUserInput | Prisma.AdImpressionUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.AdImpressionUpdateManyWithWhereWithoutUserInput | Prisma.AdImpressionUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.AdImpressionScalarWhereInput | Prisma.AdImpressionScalarWhereInput[]
}

export type AdImpressionCreateNestedManyWithoutAdInput = {
  create?: Prisma.XOR<Prisma.AdImpressionCreateWithoutAdInput, Prisma.AdImpressionUncheckedCreateWithoutAdInput> | Prisma.AdImpressionCreateWithoutAdInput[] | Prisma.AdImpressionUncheckedCreateWithoutAdInput[]
  connectOrCreate?: Prisma.AdImpressionCreateOrConnectWithoutAdInput | Prisma.AdImpressionCreateOrConnectWithoutAdInput[]
  createMany?: Prisma.AdImpressionCreateManyAdInputEnvelope
  connect?: Prisma.AdImpressionWhereUniqueInput | Prisma.AdImpressionWhereUniqueInput[]
}

export type AdImpressionUncheckedCreateNestedManyWithoutAdInput = {
  create?: Prisma.XOR<Prisma.AdImpressionCreateWithoutAdInput, Prisma.AdImpressionUncheckedCreateWithoutAdInput> | Prisma.AdImpressionCreateWithoutAdInput[] | Prisma.AdImpressionUncheckedCreateWithoutAdInput[]
  connectOrCreate?: Prisma.AdImpressionCreateOrConnectWithoutAdInput | Prisma.AdImpressionCreateOrConnectWithoutAdInput[]
  createMany?: Prisma.AdImpressionCreateManyAdInputEnvelope
  connect?: Prisma.AdImpressionWhereUniqueInput | Prisma.AdImpressionWhereUniqueInput[]
}

export type AdImpressionUpdateManyWithoutAdNestedInput = {
  create?: Prisma.XOR<Prisma.AdImpressionCreateWithoutAdInput, Prisma.AdImpressionUncheckedCreateWithoutAdInput> | Prisma.AdImpressionCreateWithoutAdInput[] | Prisma.AdImpressionUncheckedCreateWithoutAdInput[]
  connectOrCreate?: Prisma.AdImpressionCreateOrConnectWithoutAdInput | Prisma.AdImpressionCreateOrConnectWithoutAdInput[]
  upsert?: Prisma.AdImpressionUpsertWithWhereUniqueWithoutAdInput | Prisma.AdImpressionUpsertWithWhereUniqueWithoutAdInput[]
  createMany?: Prisma.AdImpressionCreateManyAdInputEnvelope
  set?: Prisma.AdImpressionWhereUniqueInput | Prisma.AdImpressionWhereUniqueInput[]
  disconnect?: Prisma.AdImpressionWhereUniqueInput | Prisma.AdImpressionWhereUniqueInput[]
  delete?: Prisma.AdImpressionWhereUniqueInput | Prisma.AdImpressionWhereUniqueInput[]
  connect?: Prisma.AdImpressionWhereUniqueInput | Prisma.AdImpressionWhereUniqueInput[]
  update?: Prisma.AdImpressionUpdateWithWhereUniqueWithoutAdInput | Prisma.AdImpressionUpdateWithWhereUniqueWithoutAdInput[]
  updateMany?: Prisma.AdImpressionUpdateManyWithWhereWithoutAdInput | Prisma.AdImpressionUpdateManyWithWhereWithoutAdInput[]
  deleteMany?: Prisma.AdImpressionScalarWhereInput | Prisma.AdImpressionScalarWhereInput[]
}

export type AdImpressionUncheckedUpdateManyWithoutAdNestedInput = {
  create?: Prisma.XOR<Prisma.AdImpressionCreateWithoutAdInput, Prisma.AdImpressionUncheckedCreateWithoutAdInput> | Prisma.AdImpressionCreateWithoutAdInput[] | Prisma.AdImpressionUncheckedCreateWithoutAdInput[]
  connectOrCreate?: Prisma.AdImpressionCreateOrConnectWithoutAdInput | Prisma.AdImpressionCreateOrConnectWithoutAdInput[]
  upsert?: Prisma.AdImpressionUpsertWithWhereUniqueWithoutAdInput | Prisma.AdImpressionUpsertWithWhereUniqueWithoutAdInput[]
  createMany?: Prisma.AdImpressionCreateManyAdInputEnvelope
  set?: Prisma.AdImpressionWhereUniqueInput | Prisma.AdImpressionWhereUniqueInput[]
  disconnect?: Prisma.AdImpressionWhereUniqueInput | Prisma.AdImpressionWhereUniqueInput[]
  delete?: Prisma.AdImpressionWhereUniqueInput | Prisma.AdImpressionWhereUniqueInput[]
  connect?: Prisma.AdImpressionWhereUniqueInput | Prisma.AdImpressionWhereUniqueInput[]
  update?: Prisma.AdImpressionUpdateWithWhereUniqueWithoutAdInput | Prisma.AdImpressionUpdateWithWhereUniqueWithoutAdInput[]
  updateMany?: Prisma.AdImpressionUpdateManyWithWhereWithoutAdInput | Prisma.AdImpressionUpdateManyWithWhereWithoutAdInput[]
  deleteMany?: Prisma.AdImpressionScalarWhereInput | Prisma.AdImpressionScalarWhereInput[]
}

export type AdImpressionCreateWithoutUserInput = {
  id?: string
  createdAt?: Date | string
  ad: Prisma.AdCreateNestedOneWithoutImpressionsInput
}

export type AdImpressionUncheckedCreateWithoutUserInput = {
  id?: string
  adId: string
  createdAt?: Date | string
}

export type AdImpressionCreateOrConnectWithoutUserInput = {
  where: Prisma.AdImpressionWhereUniqueInput
  create: Prisma.XOR<Prisma.AdImpressionCreateWithoutUserInput, Prisma.AdImpressionUncheckedCreateWithoutUserInput>
}

export type AdImpressionCreateManyUserInputEnvelope = {
  data: Prisma.AdImpressionCreateManyUserInput | Prisma.AdImpressionCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type AdImpressionUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.AdImpressionWhereUniqueInput
  update: Prisma.XOR<Prisma.AdImpressionUpdateWithoutUserInput, Prisma.AdImpressionUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.AdImpressionCreateWithoutUserInput, Prisma.AdImpressionUncheckedCreateWithoutUserInput>
}

export type AdImpressionUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.AdImpressionWhereUniqueInput
  data: Prisma.XOR<Prisma.AdImpressionUpdateWithoutUserInput, Prisma.AdImpressionUncheckedUpdateWithoutUserInput>
}

export type AdImpressionUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.AdImpressionScalarWhereInput
  data: Prisma.XOR<Prisma.AdImpressionUpdateManyMutationInput, Prisma.AdImpressionUncheckedUpdateManyWithoutUserInput>
}

export type AdImpressionScalarWhereInput = {
  AND?: Prisma.AdImpressionScalarWhereInput | Prisma.AdImpressionScalarWhereInput[]
  OR?: Prisma.AdImpressionScalarWhereInput[]
  NOT?: Prisma.AdImpressionScalarWhereInput | Prisma.AdImpressionScalarWhereInput[]
  id?: Prisma.StringFilter<"AdImpression"> | string
  adId?: Prisma.StringFilter<"AdImpression"> | string
  userId?: Prisma.StringNullableFilter<"AdImpression"> | string | null
  createdAt?: Prisma.DateTimeFilter<"AdImpression"> | Date | string
}

export type AdImpressionCreateWithoutAdInput = {
  id?: string
  createdAt?: Date | string
  user?: Prisma.UserCreateNestedOneWithoutAdImpressionsInput
}

export type AdImpressionUncheckedCreateWithoutAdInput = {
  id?: string
  userId?: string | null
  createdAt?: Date | string
}

export type AdImpressionCreateOrConnectWithoutAdInput = {
  where: Prisma.AdImpressionWhereUniqueInput
  create: Prisma.XOR<Prisma.AdImpressionCreateWithoutAdInput, Prisma.AdImpressionUncheckedCreateWithoutAdInput>
}

export type AdImpressionCreateManyAdInputEnvelope = {
  data: Prisma.AdImpressionCreateManyAdInput | Prisma.AdImpressionCreateManyAdInput[]
  skipDuplicates?: boolean
}

export type AdImpressionUpsertWithWhereUniqueWithoutAdInput = {
  where: Prisma.AdImpressionWhereUniqueInput
  update: Prisma.XOR<Prisma.AdImpressionUpdateWithoutAdInput, Prisma.AdImpressionUncheckedUpdateWithoutAdInput>
  create: Prisma.XOR<Prisma.AdImpressionCreateWithoutAdInput, Prisma.AdImpressionUncheckedCreateWithoutAdInput>
}

export type AdImpressionUpdateWithWhereUniqueWithoutAdInput = {
  where: Prisma.AdImpressionWhereUniqueInput
  data: Prisma.XOR<Prisma.AdImpressionUpdateWithoutAdInput, Prisma.AdImpressionUncheckedUpdateWithoutAdInput>
}

export type AdImpressionUpdateManyWithWhereWithoutAdInput = {
  where: Prisma.AdImpressionScalarWhereInput
  data: Prisma.XOR<Prisma.AdImpressionUpdateManyMutationInput, Prisma.AdImpressionUncheckedUpdateManyWithoutAdInput>
}

export type AdImpressionCreateManyUserInput = {
  id?: string
  adId: string
  createdAt?: Date | string
}

export type AdImpressionUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ad?: Prisma.AdUpdateOneRequiredWithoutImpressionsNestedInput
}

export type AdImpressionUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  adId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AdImpressionUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  adId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AdImpressionCreateManyAdInput = {
  id?: string
  userId?: string | null
  createdAt?: Date | string
}

export type AdImpressionUpdateWithoutAdInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneWithoutAdImpressionsNestedInput
}

export type AdImpressionUncheckedUpdateWithoutAdInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AdImpressionUncheckedUpdateManyWithoutAdInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type AdImpressionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  adId?: boolean
  userId?: boolean
  createdAt?: boolean
  ad?: boolean | Prisma.AdDefaultArgs<ExtArgs>
  user?: boolean | Prisma.AdImpression$userArgs<ExtArgs>
}, ExtArgs["result"]["adImpression"]>



export type AdImpressionSelectScalar = {
  id?: boolean
  adId?: boolean
  userId?: boolean
  createdAt?: boolean
}

export type AdImpressionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "adId" | "userId" | "createdAt", ExtArgs["result"]["adImpression"]>
export type AdImpressionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  ad?: boolean | Prisma.AdDefaultArgs<ExtArgs>
  user?: boolean | Prisma.AdImpression$userArgs<ExtArgs>
}

export type $AdImpressionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AdImpression"
  objects: {
    ad: Prisma.$AdPayload<ExtArgs>
    user: Prisma.$UserPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    adId: string
    userId: string | null
    createdAt: Date
  }, ExtArgs["result"]["adImpression"]>
  composites: {}
}

export type AdImpressionGetPayload<S extends boolean | null | undefined | AdImpressionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AdImpressionPayload, S>

export type AdImpressionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AdImpressionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AdImpressionCountAggregateInputType | true
  }

export interface AdImpressionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AdImpression'], meta: { name: 'AdImpression' } }
  /**
   * Find zero or one AdImpression that matches the filter.
   * @param {AdImpressionFindUniqueArgs} args - Arguments to find a AdImpression
   * @example
   * // Get one AdImpression
   * const adImpression = await prisma.adImpression.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AdImpressionFindUniqueArgs>(args: Prisma.SelectSubset<T, AdImpressionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AdImpressionClient<runtime.Types.Result.GetResult<Prisma.$AdImpressionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AdImpression that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AdImpressionFindUniqueOrThrowArgs} args - Arguments to find a AdImpression
   * @example
   * // Get one AdImpression
   * const adImpression = await prisma.adImpression.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AdImpressionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AdImpressionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AdImpressionClient<runtime.Types.Result.GetResult<Prisma.$AdImpressionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AdImpression that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AdImpressionFindFirstArgs} args - Arguments to find a AdImpression
   * @example
   * // Get one AdImpression
   * const adImpression = await prisma.adImpression.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AdImpressionFindFirstArgs>(args?: Prisma.SelectSubset<T, AdImpressionFindFirstArgs<ExtArgs>>): Prisma.Prisma__AdImpressionClient<runtime.Types.Result.GetResult<Prisma.$AdImpressionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AdImpression that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AdImpressionFindFirstOrThrowArgs} args - Arguments to find a AdImpression
   * @example
   * // Get one AdImpression
   * const adImpression = await prisma.adImpression.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AdImpressionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AdImpressionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AdImpressionClient<runtime.Types.Result.GetResult<Prisma.$AdImpressionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AdImpressions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AdImpressionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AdImpressions
   * const adImpressions = await prisma.adImpression.findMany()
   * 
   * // Get first 10 AdImpressions
   * const adImpressions = await prisma.adImpression.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const adImpressionWithIdOnly = await prisma.adImpression.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AdImpressionFindManyArgs>(args?: Prisma.SelectSubset<T, AdImpressionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AdImpressionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AdImpression.
   * @param {AdImpressionCreateArgs} args - Arguments to create a AdImpression.
   * @example
   * // Create one AdImpression
   * const AdImpression = await prisma.adImpression.create({
   *   data: {
   *     // ... data to create a AdImpression
   *   }
   * })
   * 
   */
  create<T extends AdImpressionCreateArgs>(args: Prisma.SelectSubset<T, AdImpressionCreateArgs<ExtArgs>>): Prisma.Prisma__AdImpressionClient<runtime.Types.Result.GetResult<Prisma.$AdImpressionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AdImpressions.
   * @param {AdImpressionCreateManyArgs} args - Arguments to create many AdImpressions.
   * @example
   * // Create many AdImpressions
   * const adImpression = await prisma.adImpression.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AdImpressionCreateManyArgs>(args?: Prisma.SelectSubset<T, AdImpressionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a AdImpression.
   * @param {AdImpressionDeleteArgs} args - Arguments to delete one AdImpression.
   * @example
   * // Delete one AdImpression
   * const AdImpression = await prisma.adImpression.delete({
   *   where: {
   *     // ... filter to delete one AdImpression
   *   }
   * })
   * 
   */
  delete<T extends AdImpressionDeleteArgs>(args: Prisma.SelectSubset<T, AdImpressionDeleteArgs<ExtArgs>>): Prisma.Prisma__AdImpressionClient<runtime.Types.Result.GetResult<Prisma.$AdImpressionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AdImpression.
   * @param {AdImpressionUpdateArgs} args - Arguments to update one AdImpression.
   * @example
   * // Update one AdImpression
   * const adImpression = await prisma.adImpression.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AdImpressionUpdateArgs>(args: Prisma.SelectSubset<T, AdImpressionUpdateArgs<ExtArgs>>): Prisma.Prisma__AdImpressionClient<runtime.Types.Result.GetResult<Prisma.$AdImpressionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AdImpressions.
   * @param {AdImpressionDeleteManyArgs} args - Arguments to filter AdImpressions to delete.
   * @example
   * // Delete a few AdImpressions
   * const { count } = await prisma.adImpression.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AdImpressionDeleteManyArgs>(args?: Prisma.SelectSubset<T, AdImpressionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AdImpressions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AdImpressionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AdImpressions
   * const adImpression = await prisma.adImpression.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AdImpressionUpdateManyArgs>(args: Prisma.SelectSubset<T, AdImpressionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one AdImpression.
   * @param {AdImpressionUpsertArgs} args - Arguments to update or create a AdImpression.
   * @example
   * // Update or create a AdImpression
   * const adImpression = await prisma.adImpression.upsert({
   *   create: {
   *     // ... data to create a AdImpression
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AdImpression we want to update
   *   }
   * })
   */
  upsert<T extends AdImpressionUpsertArgs>(args: Prisma.SelectSubset<T, AdImpressionUpsertArgs<ExtArgs>>): Prisma.Prisma__AdImpressionClient<runtime.Types.Result.GetResult<Prisma.$AdImpressionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AdImpressions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AdImpressionCountArgs} args - Arguments to filter AdImpressions to count.
   * @example
   * // Count the number of AdImpressions
   * const count = await prisma.adImpression.count({
   *   where: {
   *     // ... the filter for the AdImpressions we want to count
   *   }
   * })
  **/
  count<T extends AdImpressionCountArgs>(
    args?: Prisma.Subset<T, AdImpressionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AdImpressionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AdImpression.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AdImpressionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AdImpressionAggregateArgs>(args: Prisma.Subset<T, AdImpressionAggregateArgs>): Prisma.PrismaPromise<GetAdImpressionAggregateType<T>>

  /**
   * Group by AdImpression.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AdImpressionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AdImpressionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AdImpressionGroupByArgs['orderBy'] }
      : { orderBy?: AdImpressionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AdImpressionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAdImpressionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AdImpression model
 */
readonly fields: AdImpressionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AdImpression.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AdImpressionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  ad<T extends Prisma.AdDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AdDefaultArgs<ExtArgs>>): Prisma.Prisma__AdClient<runtime.Types.Result.GetResult<Prisma.$AdPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.AdImpression$userArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AdImpression$userArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AdImpression model
 */
export interface AdImpressionFieldRefs {
  readonly id: Prisma.FieldRef<"AdImpression", 'String'>
  readonly adId: Prisma.FieldRef<"AdImpression", 'String'>
  readonly userId: Prisma.FieldRef<"AdImpression", 'String'>
  readonly createdAt: Prisma.FieldRef<"AdImpression", 'DateTime'>
}
    

// Custom InputTypes
/**
 * AdImpression findUnique
 */
export type AdImpressionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdImpression
   */
  select?: Prisma.AdImpressionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AdImpression
   */
  omit?: Prisma.AdImpressionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdImpressionInclude<ExtArgs> | null
  /**
   * Filter, which AdImpression to fetch.
   */
  where: Prisma.AdImpressionWhereUniqueInput
}

/**
 * AdImpression findUniqueOrThrow
 */
export type AdImpressionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdImpression
   */
  select?: Prisma.AdImpressionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AdImpression
   */
  omit?: Prisma.AdImpressionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdImpressionInclude<ExtArgs> | null
  /**
   * Filter, which AdImpression to fetch.
   */
  where: Prisma.AdImpressionWhereUniqueInput
}

/**
 * AdImpression findFirst
 */
export type AdImpressionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdImpression
   */
  select?: Prisma.AdImpressionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AdImpression
   */
  omit?: Prisma.AdImpressionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdImpressionInclude<ExtArgs> | null
  /**
   * Filter, which AdImpression to fetch.
   */
  where?: Prisma.AdImpressionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AdImpressions to fetch.
   */
  orderBy?: Prisma.AdImpressionOrderByWithRelationInput | Prisma.AdImpressionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AdImpressions.
   */
  cursor?: Prisma.AdImpressionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AdImpressions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AdImpressions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AdImpressions.
   */
  distinct?: Prisma.AdImpressionScalarFieldEnum | Prisma.AdImpressionScalarFieldEnum[]
}

/**
 * AdImpression findFirstOrThrow
 */
export type AdImpressionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdImpression
   */
  select?: Prisma.AdImpressionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AdImpression
   */
  omit?: Prisma.AdImpressionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdImpressionInclude<ExtArgs> | null
  /**
   * Filter, which AdImpression to fetch.
   */
  where?: Prisma.AdImpressionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AdImpressions to fetch.
   */
  orderBy?: Prisma.AdImpressionOrderByWithRelationInput | Prisma.AdImpressionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AdImpressions.
   */
  cursor?: Prisma.AdImpressionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AdImpressions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AdImpressions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AdImpressions.
   */
  distinct?: Prisma.AdImpressionScalarFieldEnum | Prisma.AdImpressionScalarFieldEnum[]
}

/**
 * AdImpression findMany
 */
export type AdImpressionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdImpression
   */
  select?: Prisma.AdImpressionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AdImpression
   */
  omit?: Prisma.AdImpressionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdImpressionInclude<ExtArgs> | null
  /**
   * Filter, which AdImpressions to fetch.
   */
  where?: Prisma.AdImpressionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AdImpressions to fetch.
   */
  orderBy?: Prisma.AdImpressionOrderByWithRelationInput | Prisma.AdImpressionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AdImpressions.
   */
  cursor?: Prisma.AdImpressionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AdImpressions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AdImpressions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AdImpressions.
   */
  distinct?: Prisma.AdImpressionScalarFieldEnum | Prisma.AdImpressionScalarFieldEnum[]
}

/**
 * AdImpression create
 */
export type AdImpressionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdImpression
   */
  select?: Prisma.AdImpressionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AdImpression
   */
  omit?: Prisma.AdImpressionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdImpressionInclude<ExtArgs> | null
  /**
   * The data needed to create a AdImpression.
   */
  data: Prisma.XOR<Prisma.AdImpressionCreateInput, Prisma.AdImpressionUncheckedCreateInput>
}

/**
 * AdImpression createMany
 */
export type AdImpressionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AdImpressions.
   */
  data: Prisma.AdImpressionCreateManyInput | Prisma.AdImpressionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AdImpression update
 */
export type AdImpressionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdImpression
   */
  select?: Prisma.AdImpressionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AdImpression
   */
  omit?: Prisma.AdImpressionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdImpressionInclude<ExtArgs> | null
  /**
   * The data needed to update a AdImpression.
   */
  data: Prisma.XOR<Prisma.AdImpressionUpdateInput, Prisma.AdImpressionUncheckedUpdateInput>
  /**
   * Choose, which AdImpression to update.
   */
  where: Prisma.AdImpressionWhereUniqueInput
}

/**
 * AdImpression updateMany
 */
export type AdImpressionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AdImpressions.
   */
  data: Prisma.XOR<Prisma.AdImpressionUpdateManyMutationInput, Prisma.AdImpressionUncheckedUpdateManyInput>
  /**
   * Filter which AdImpressions to update
   */
  where?: Prisma.AdImpressionWhereInput
  /**
   * Limit how many AdImpressions to update.
   */
  limit?: number
}

/**
 * AdImpression upsert
 */
export type AdImpressionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdImpression
   */
  select?: Prisma.AdImpressionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AdImpression
   */
  omit?: Prisma.AdImpressionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdImpressionInclude<ExtArgs> | null
  /**
   * The filter to search for the AdImpression to update in case it exists.
   */
  where: Prisma.AdImpressionWhereUniqueInput
  /**
   * In case the AdImpression found by the `where` argument doesn't exist, create a new AdImpression with this data.
   */
  create: Prisma.XOR<Prisma.AdImpressionCreateInput, Prisma.AdImpressionUncheckedCreateInput>
  /**
   * In case the AdImpression was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AdImpressionUpdateInput, Prisma.AdImpressionUncheckedUpdateInput>
}

/**
 * AdImpression delete
 */
export type AdImpressionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdImpression
   */
  select?: Prisma.AdImpressionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AdImpression
   */
  omit?: Prisma.AdImpressionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdImpressionInclude<ExtArgs> | null
  /**
   * Filter which AdImpression to delete.
   */
  where: Prisma.AdImpressionWhereUniqueInput
}

/**
 * AdImpression deleteMany
 */
export type AdImpressionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AdImpressions to delete
   */
  where?: Prisma.AdImpressionWhereInput
  /**
   * Limit how many AdImpressions to delete.
   */
  limit?: number
}

/**
 * AdImpression.user
 */
export type AdImpression$userArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * AdImpression without action
 */
export type AdImpressionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdImpression
   */
  select?: Prisma.AdImpressionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AdImpression
   */
  omit?: Prisma.AdImpressionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdImpressionInclude<ExtArgs> | null
}
