
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CoinPackage` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model CoinPackage
 * 
 */
export type CoinPackageModel = runtime.Types.Result.DefaultSelection<Prisma.$CoinPackagePayload>

export type AggregateCoinPackage = {
  _count: CoinPackageCountAggregateOutputType | null
  _avg: CoinPackageAvgAggregateOutputType | null
  _sum: CoinPackageSumAggregateOutputType | null
  _min: CoinPackageMinAggregateOutputType | null
  _max: CoinPackageMaxAggregateOutputType | null
}

export type CoinPackageAvgAggregateOutputType = {
  coins: number | null
  priceGBP: runtime.Decimal | null
  bonus: number | null
  sortOrder: number | null
}

export type CoinPackageSumAggregateOutputType = {
  coins: number | null
  priceGBP: runtime.Decimal | null
  bonus: number | null
  sortOrder: number | null
}

export type CoinPackageMinAggregateOutputType = {
  id: string | null
  label: string | null
  coins: number | null
  priceGBP: runtime.Decimal | null
  bonus: number | null
  active: boolean | null
  sortOrder: number | null
}

export type CoinPackageMaxAggregateOutputType = {
  id: string | null
  label: string | null
  coins: number | null
  priceGBP: runtime.Decimal | null
  bonus: number | null
  active: boolean | null
  sortOrder: number | null
}

export type CoinPackageCountAggregateOutputType = {
  id: number
  label: number
  coins: number
  priceGBP: number
  bonus: number
  active: number
  sortOrder: number
  _all: number
}


export type CoinPackageAvgAggregateInputType = {
  coins?: true
  priceGBP?: true
  bonus?: true
  sortOrder?: true
}

export type CoinPackageSumAggregateInputType = {
  coins?: true
  priceGBP?: true
  bonus?: true
  sortOrder?: true
}

export type CoinPackageMinAggregateInputType = {
  id?: true
  label?: true
  coins?: true
  priceGBP?: true
  bonus?: true
  active?: true
  sortOrder?: true
}

export type CoinPackageMaxAggregateInputType = {
  id?: true
  label?: true
  coins?: true
  priceGBP?: true
  bonus?: true
  active?: true
  sortOrder?: true
}

export type CoinPackageCountAggregateInputType = {
  id?: true
  label?: true
  coins?: true
  priceGBP?: true
  bonus?: true
  active?: true
  sortOrder?: true
  _all?: true
}

export type CoinPackageAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CoinPackage to aggregate.
   */
  where?: Prisma.CoinPackageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CoinPackages to fetch.
   */
  orderBy?: Prisma.CoinPackageOrderByWithRelationInput | Prisma.CoinPackageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CoinPackageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CoinPackages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CoinPackages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CoinPackages
  **/
  _count?: true | CoinPackageCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CoinPackageAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CoinPackageSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CoinPackageMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CoinPackageMaxAggregateInputType
}

export type GetCoinPackageAggregateType<T extends CoinPackageAggregateArgs> = {
      [P in keyof T & keyof AggregateCoinPackage]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCoinPackage[P]>
    : Prisma.GetScalarType<T[P], AggregateCoinPackage[P]>
}




export type CoinPackageGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CoinPackageWhereInput
  orderBy?: Prisma.CoinPackageOrderByWithAggregationInput | Prisma.CoinPackageOrderByWithAggregationInput[]
  by: Prisma.CoinPackageScalarFieldEnum[] | Prisma.CoinPackageScalarFieldEnum
  having?: Prisma.CoinPackageScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CoinPackageCountAggregateInputType | true
  _avg?: CoinPackageAvgAggregateInputType
  _sum?: CoinPackageSumAggregateInputType
  _min?: CoinPackageMinAggregateInputType
  _max?: CoinPackageMaxAggregateInputType
}

export type CoinPackageGroupByOutputType = {
  id: string
  label: string
  coins: number
  priceGBP: runtime.Decimal
  bonus: number
  active: boolean
  sortOrder: number
  _count: CoinPackageCountAggregateOutputType | null
  _avg: CoinPackageAvgAggregateOutputType | null
  _sum: CoinPackageSumAggregateOutputType | null
  _min: CoinPackageMinAggregateOutputType | null
  _max: CoinPackageMaxAggregateOutputType | null
}

export type GetCoinPackageGroupByPayload<T extends CoinPackageGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CoinPackageGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CoinPackageGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CoinPackageGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CoinPackageGroupByOutputType[P]>
      }
    >
  >



export type CoinPackageWhereInput = {
  AND?: Prisma.CoinPackageWhereInput | Prisma.CoinPackageWhereInput[]
  OR?: Prisma.CoinPackageWhereInput[]
  NOT?: Prisma.CoinPackageWhereInput | Prisma.CoinPackageWhereInput[]
  id?: Prisma.StringFilter<"CoinPackage"> | string
  label?: Prisma.StringFilter<"CoinPackage"> | string
  coins?: Prisma.IntFilter<"CoinPackage"> | number
  priceGBP?: Prisma.DecimalFilter<"CoinPackage"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  bonus?: Prisma.IntFilter<"CoinPackage"> | number
  active?: Prisma.BoolFilter<"CoinPackage"> | boolean
  sortOrder?: Prisma.IntFilter<"CoinPackage"> | number
}

export type CoinPackageOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  label?: Prisma.SortOrder
  coins?: Prisma.SortOrder
  priceGBP?: Prisma.SortOrder
  bonus?: Prisma.SortOrder
  active?: Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
  _relevance?: Prisma.CoinPackageOrderByRelevanceInput
}

export type CoinPackageWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.CoinPackageWhereInput | Prisma.CoinPackageWhereInput[]
  OR?: Prisma.CoinPackageWhereInput[]
  NOT?: Prisma.CoinPackageWhereInput | Prisma.CoinPackageWhereInput[]
  label?: Prisma.StringFilter<"CoinPackage"> | string
  coins?: Prisma.IntFilter<"CoinPackage"> | number
  priceGBP?: Prisma.DecimalFilter<"CoinPackage"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  bonus?: Prisma.IntFilter<"CoinPackage"> | number
  active?: Prisma.BoolFilter<"CoinPackage"> | boolean
  sortOrder?: Prisma.IntFilter<"CoinPackage"> | number
}, "id">

export type CoinPackageOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  label?: Prisma.SortOrder
  coins?: Prisma.SortOrder
  priceGBP?: Prisma.SortOrder
  bonus?: Prisma.SortOrder
  active?: Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
  _count?: Prisma.CoinPackageCountOrderByAggregateInput
  _avg?: Prisma.CoinPackageAvgOrderByAggregateInput
  _max?: Prisma.CoinPackageMaxOrderByAggregateInput
  _min?: Prisma.CoinPackageMinOrderByAggregateInput
  _sum?: Prisma.CoinPackageSumOrderByAggregateInput
}

export type CoinPackageScalarWhereWithAggregatesInput = {
  AND?: Prisma.CoinPackageScalarWhereWithAggregatesInput | Prisma.CoinPackageScalarWhereWithAggregatesInput[]
  OR?: Prisma.CoinPackageScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CoinPackageScalarWhereWithAggregatesInput | Prisma.CoinPackageScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"CoinPackage"> | string
  label?: Prisma.StringWithAggregatesFilter<"CoinPackage"> | string
  coins?: Prisma.IntWithAggregatesFilter<"CoinPackage"> | number
  priceGBP?: Prisma.DecimalWithAggregatesFilter<"CoinPackage"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  bonus?: Prisma.IntWithAggregatesFilter<"CoinPackage"> | number
  active?: Prisma.BoolWithAggregatesFilter<"CoinPackage"> | boolean
  sortOrder?: Prisma.IntWithAggregatesFilter<"CoinPackage"> | number
}

export type CoinPackageCreateInput = {
  id?: string
  label: string
  coins: number
  priceGBP: runtime.Decimal | runtime.DecimalJsLike | number | string
  bonus?: number
  active?: boolean
  sortOrder?: number
}

export type CoinPackageUncheckedCreateInput = {
  id?: string
  label: string
  coins: number
  priceGBP: runtime.Decimal | runtime.DecimalJsLike | number | string
  bonus?: number
  active?: boolean
  sortOrder?: number
}

export type CoinPackageUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  coins?: Prisma.IntFieldUpdateOperationsInput | number
  priceGBP?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  bonus?: Prisma.IntFieldUpdateOperationsInput | number
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
}

export type CoinPackageUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  coins?: Prisma.IntFieldUpdateOperationsInput | number
  priceGBP?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  bonus?: Prisma.IntFieldUpdateOperationsInput | number
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
}

export type CoinPackageCreateManyInput = {
  id?: string
  label: string
  coins: number
  priceGBP: runtime.Decimal | runtime.DecimalJsLike | number | string
  bonus?: number
  active?: boolean
  sortOrder?: number
}

export type CoinPackageUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  coins?: Prisma.IntFieldUpdateOperationsInput | number
  priceGBP?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  bonus?: Prisma.IntFieldUpdateOperationsInput | number
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
}

export type CoinPackageUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  coins?: Prisma.IntFieldUpdateOperationsInput | number
  priceGBP?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  bonus?: Prisma.IntFieldUpdateOperationsInput | number
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
}

export type CoinPackageOrderByRelevanceInput = {
  fields: Prisma.CoinPackageOrderByRelevanceFieldEnum | Prisma.CoinPackageOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type CoinPackageCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  label?: Prisma.SortOrder
  coins?: Prisma.SortOrder
  priceGBP?: Prisma.SortOrder
  bonus?: Prisma.SortOrder
  active?: Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
}

export type CoinPackageAvgOrderByAggregateInput = {
  coins?: Prisma.SortOrder
  priceGBP?: Prisma.SortOrder
  bonus?: Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
}

export type CoinPackageMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  label?: Prisma.SortOrder
  coins?: Prisma.SortOrder
  priceGBP?: Prisma.SortOrder
  bonus?: Prisma.SortOrder
  active?: Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
}

export type CoinPackageMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  label?: Prisma.SortOrder
  coins?: Prisma.SortOrder
  priceGBP?: Prisma.SortOrder
  bonus?: Prisma.SortOrder
  active?: Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
}

export type CoinPackageSumOrderByAggregateInput = {
  coins?: Prisma.SortOrder
  priceGBP?: Prisma.SortOrder
  bonus?: Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
}

export type DecimalFieldUpdateOperationsInput = {
  set?: runtime.Decimal | runtime.DecimalJsLike | number | string
  increment?: runtime.Decimal | runtime.DecimalJsLike | number | string
  decrement?: runtime.Decimal | runtime.DecimalJsLike | number | string
  multiply?: runtime.Decimal | runtime.DecimalJsLike | number | string
  divide?: runtime.Decimal | runtime.DecimalJsLike | number | string
}



export type CoinPackageSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  label?: boolean
  coins?: boolean
  priceGBP?: boolean
  bonus?: boolean
  active?: boolean
  sortOrder?: boolean
}, ExtArgs["result"]["coinPackage"]>



export type CoinPackageSelectScalar = {
  id?: boolean
  label?: boolean
  coins?: boolean
  priceGBP?: boolean
  bonus?: boolean
  active?: boolean
  sortOrder?: boolean
}

export type CoinPackageOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "label" | "coins" | "priceGBP" | "bonus" | "active" | "sortOrder", ExtArgs["result"]["coinPackage"]>

export type $CoinPackagePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CoinPackage"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    label: string
    coins: number
    priceGBP: runtime.Decimal
    bonus: number
    active: boolean
    sortOrder: number
  }, ExtArgs["result"]["coinPackage"]>
  composites: {}
}

export type CoinPackageGetPayload<S extends boolean | null | undefined | CoinPackageDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CoinPackagePayload, S>

export type CoinPackageCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CoinPackageFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CoinPackageCountAggregateInputType | true
  }

export interface CoinPackageDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CoinPackage'], meta: { name: 'CoinPackage' } }
  /**
   * Find zero or one CoinPackage that matches the filter.
   * @param {CoinPackageFindUniqueArgs} args - Arguments to find a CoinPackage
   * @example
   * // Get one CoinPackage
   * const coinPackage = await prisma.coinPackage.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CoinPackageFindUniqueArgs>(args: Prisma.SelectSubset<T, CoinPackageFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CoinPackageClient<runtime.Types.Result.GetResult<Prisma.$CoinPackagePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CoinPackage that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CoinPackageFindUniqueOrThrowArgs} args - Arguments to find a CoinPackage
   * @example
   * // Get one CoinPackage
   * const coinPackage = await prisma.coinPackage.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CoinPackageFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CoinPackageFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CoinPackageClient<runtime.Types.Result.GetResult<Prisma.$CoinPackagePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CoinPackage that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CoinPackageFindFirstArgs} args - Arguments to find a CoinPackage
   * @example
   * // Get one CoinPackage
   * const coinPackage = await prisma.coinPackage.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CoinPackageFindFirstArgs>(args?: Prisma.SelectSubset<T, CoinPackageFindFirstArgs<ExtArgs>>): Prisma.Prisma__CoinPackageClient<runtime.Types.Result.GetResult<Prisma.$CoinPackagePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CoinPackage that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CoinPackageFindFirstOrThrowArgs} args - Arguments to find a CoinPackage
   * @example
   * // Get one CoinPackage
   * const coinPackage = await prisma.coinPackage.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CoinPackageFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CoinPackageFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CoinPackageClient<runtime.Types.Result.GetResult<Prisma.$CoinPackagePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CoinPackages that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CoinPackageFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CoinPackages
   * const coinPackages = await prisma.coinPackage.findMany()
   * 
   * // Get first 10 CoinPackages
   * const coinPackages = await prisma.coinPackage.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const coinPackageWithIdOnly = await prisma.coinPackage.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CoinPackageFindManyArgs>(args?: Prisma.SelectSubset<T, CoinPackageFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CoinPackagePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CoinPackage.
   * @param {CoinPackageCreateArgs} args - Arguments to create a CoinPackage.
   * @example
   * // Create one CoinPackage
   * const CoinPackage = await prisma.coinPackage.create({
   *   data: {
   *     // ... data to create a CoinPackage
   *   }
   * })
   * 
   */
  create<T extends CoinPackageCreateArgs>(args: Prisma.SelectSubset<T, CoinPackageCreateArgs<ExtArgs>>): Prisma.Prisma__CoinPackageClient<runtime.Types.Result.GetResult<Prisma.$CoinPackagePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CoinPackages.
   * @param {CoinPackageCreateManyArgs} args - Arguments to create many CoinPackages.
   * @example
   * // Create many CoinPackages
   * const coinPackage = await prisma.coinPackage.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CoinPackageCreateManyArgs>(args?: Prisma.SelectSubset<T, CoinPackageCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a CoinPackage.
   * @param {CoinPackageDeleteArgs} args - Arguments to delete one CoinPackage.
   * @example
   * // Delete one CoinPackage
   * const CoinPackage = await prisma.coinPackage.delete({
   *   where: {
   *     // ... filter to delete one CoinPackage
   *   }
   * })
   * 
   */
  delete<T extends CoinPackageDeleteArgs>(args: Prisma.SelectSubset<T, CoinPackageDeleteArgs<ExtArgs>>): Prisma.Prisma__CoinPackageClient<runtime.Types.Result.GetResult<Prisma.$CoinPackagePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CoinPackage.
   * @param {CoinPackageUpdateArgs} args - Arguments to update one CoinPackage.
   * @example
   * // Update one CoinPackage
   * const coinPackage = await prisma.coinPackage.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CoinPackageUpdateArgs>(args: Prisma.SelectSubset<T, CoinPackageUpdateArgs<ExtArgs>>): Prisma.Prisma__CoinPackageClient<runtime.Types.Result.GetResult<Prisma.$CoinPackagePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CoinPackages.
   * @param {CoinPackageDeleteManyArgs} args - Arguments to filter CoinPackages to delete.
   * @example
   * // Delete a few CoinPackages
   * const { count } = await prisma.coinPackage.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CoinPackageDeleteManyArgs>(args?: Prisma.SelectSubset<T, CoinPackageDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CoinPackages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CoinPackageUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CoinPackages
   * const coinPackage = await prisma.coinPackage.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CoinPackageUpdateManyArgs>(args: Prisma.SelectSubset<T, CoinPackageUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one CoinPackage.
   * @param {CoinPackageUpsertArgs} args - Arguments to update or create a CoinPackage.
   * @example
   * // Update or create a CoinPackage
   * const coinPackage = await prisma.coinPackage.upsert({
   *   create: {
   *     // ... data to create a CoinPackage
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CoinPackage we want to update
   *   }
   * })
   */
  upsert<T extends CoinPackageUpsertArgs>(args: Prisma.SelectSubset<T, CoinPackageUpsertArgs<ExtArgs>>): Prisma.Prisma__CoinPackageClient<runtime.Types.Result.GetResult<Prisma.$CoinPackagePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CoinPackages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CoinPackageCountArgs} args - Arguments to filter CoinPackages to count.
   * @example
   * // Count the number of CoinPackages
   * const count = await prisma.coinPackage.count({
   *   where: {
   *     // ... the filter for the CoinPackages we want to count
   *   }
   * })
  **/
  count<T extends CoinPackageCountArgs>(
    args?: Prisma.Subset<T, CoinPackageCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CoinPackageCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CoinPackage.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CoinPackageAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CoinPackageAggregateArgs>(args: Prisma.Subset<T, CoinPackageAggregateArgs>): Prisma.PrismaPromise<GetCoinPackageAggregateType<T>>

  /**
   * Group by CoinPackage.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CoinPackageGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CoinPackageGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CoinPackageGroupByArgs['orderBy'] }
      : { orderBy?: CoinPackageGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CoinPackageGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCoinPackageGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CoinPackage model
 */
readonly fields: CoinPackageFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CoinPackage.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CoinPackageClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CoinPackage model
 */
export interface CoinPackageFieldRefs {
  readonly id: Prisma.FieldRef<"CoinPackage", 'String'>
  readonly label: Prisma.FieldRef<"CoinPackage", 'String'>
  readonly coins: Prisma.FieldRef<"CoinPackage", 'Int'>
  readonly priceGBP: Prisma.FieldRef<"CoinPackage", 'Decimal'>
  readonly bonus: Prisma.FieldRef<"CoinPackage", 'Int'>
  readonly active: Prisma.FieldRef<"CoinPackage", 'Boolean'>
  readonly sortOrder: Prisma.FieldRef<"CoinPackage", 'Int'>
}
    

// Custom InputTypes
/**
 * CoinPackage findUnique
 */
export type CoinPackageFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CoinPackage
   */
  select?: Prisma.CoinPackageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CoinPackage
   */
  omit?: Prisma.CoinPackageOmit<ExtArgs> | null
  /**
   * Filter, which CoinPackage to fetch.
   */
  where: Prisma.CoinPackageWhereUniqueInput
}

/**
 * CoinPackage findUniqueOrThrow
 */
export type CoinPackageFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CoinPackage
   */
  select?: Prisma.CoinPackageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CoinPackage
   */
  omit?: Prisma.CoinPackageOmit<ExtArgs> | null
  /**
   * Filter, which CoinPackage to fetch.
   */
  where: Prisma.CoinPackageWhereUniqueInput
}

/**
 * CoinPackage findFirst
 */
export type CoinPackageFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CoinPackage
   */
  select?: Prisma.CoinPackageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CoinPackage
   */
  omit?: Prisma.CoinPackageOmit<ExtArgs> | null
  /**
   * Filter, which CoinPackage to fetch.
   */
  where?: Prisma.CoinPackageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CoinPackages to fetch.
   */
  orderBy?: Prisma.CoinPackageOrderByWithRelationInput | Prisma.CoinPackageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CoinPackages.
   */
  cursor?: Prisma.CoinPackageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CoinPackages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CoinPackages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CoinPackages.
   */
  distinct?: Prisma.CoinPackageScalarFieldEnum | Prisma.CoinPackageScalarFieldEnum[]
}

/**
 * CoinPackage findFirstOrThrow
 */
export type CoinPackageFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CoinPackage
   */
  select?: Prisma.CoinPackageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CoinPackage
   */
  omit?: Prisma.CoinPackageOmit<ExtArgs> | null
  /**
   * Filter, which CoinPackage to fetch.
   */
  where?: Prisma.CoinPackageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CoinPackages to fetch.
   */
  orderBy?: Prisma.CoinPackageOrderByWithRelationInput | Prisma.CoinPackageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CoinPackages.
   */
  cursor?: Prisma.CoinPackageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CoinPackages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CoinPackages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CoinPackages.
   */
  distinct?: Prisma.CoinPackageScalarFieldEnum | Prisma.CoinPackageScalarFieldEnum[]
}

/**
 * CoinPackage findMany
 */
export type CoinPackageFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CoinPackage
   */
  select?: Prisma.CoinPackageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CoinPackage
   */
  omit?: Prisma.CoinPackageOmit<ExtArgs> | null
  /**
   * Filter, which CoinPackages to fetch.
   */
  where?: Prisma.CoinPackageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CoinPackages to fetch.
   */
  orderBy?: Prisma.CoinPackageOrderByWithRelationInput | Prisma.CoinPackageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CoinPackages.
   */
  cursor?: Prisma.CoinPackageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CoinPackages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CoinPackages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CoinPackages.
   */
  distinct?: Prisma.CoinPackageScalarFieldEnum | Prisma.CoinPackageScalarFieldEnum[]
}

/**
 * CoinPackage create
 */
export type CoinPackageCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CoinPackage
   */
  select?: Prisma.CoinPackageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CoinPackage
   */
  omit?: Prisma.CoinPackageOmit<ExtArgs> | null
  /**
   * The data needed to create a CoinPackage.
   */
  data: Prisma.XOR<Prisma.CoinPackageCreateInput, Prisma.CoinPackageUncheckedCreateInput>
}

/**
 * CoinPackage createMany
 */
export type CoinPackageCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CoinPackages.
   */
  data: Prisma.CoinPackageCreateManyInput | Prisma.CoinPackageCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * CoinPackage update
 */
export type CoinPackageUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CoinPackage
   */
  select?: Prisma.CoinPackageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CoinPackage
   */
  omit?: Prisma.CoinPackageOmit<ExtArgs> | null
  /**
   * The data needed to update a CoinPackage.
   */
  data: Prisma.XOR<Prisma.CoinPackageUpdateInput, Prisma.CoinPackageUncheckedUpdateInput>
  /**
   * Choose, which CoinPackage to update.
   */
  where: Prisma.CoinPackageWhereUniqueInput
}

/**
 * CoinPackage updateMany
 */
export type CoinPackageUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CoinPackages.
   */
  data: Prisma.XOR<Prisma.CoinPackageUpdateManyMutationInput, Prisma.CoinPackageUncheckedUpdateManyInput>
  /**
   * Filter which CoinPackages to update
   */
  where?: Prisma.CoinPackageWhereInput
  /**
   * Limit how many CoinPackages to update.
   */
  limit?: number
}

/**
 * CoinPackage upsert
 */
export type CoinPackageUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CoinPackage
   */
  select?: Prisma.CoinPackageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CoinPackage
   */
  omit?: Prisma.CoinPackageOmit<ExtArgs> | null
  /**
   * The filter to search for the CoinPackage to update in case it exists.
   */
  where: Prisma.CoinPackageWhereUniqueInput
  /**
   * In case the CoinPackage found by the `where` argument doesn't exist, create a new CoinPackage with this data.
   */
  create: Prisma.XOR<Prisma.CoinPackageCreateInput, Prisma.CoinPackageUncheckedCreateInput>
  /**
   * In case the CoinPackage was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CoinPackageUpdateInput, Prisma.CoinPackageUncheckedUpdateInput>
}

/**
 * CoinPackage delete
 */
export type CoinPackageDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CoinPackage
   */
  select?: Prisma.CoinPackageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CoinPackage
   */
  omit?: Prisma.CoinPackageOmit<ExtArgs> | null
  /**
   * Filter which CoinPackage to delete.
   */
  where: Prisma.CoinPackageWhereUniqueInput
}

/**
 * CoinPackage deleteMany
 */
export type CoinPackageDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CoinPackages to delete
   */
  where?: Prisma.CoinPackageWhereInput
  /**
   * Limit how many CoinPackages to delete.
   */
  limit?: number
}

/**
 * CoinPackage without action
 */
export type CoinPackageDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CoinPackage
   */
  select?: Prisma.CoinPackageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CoinPackage
   */
  omit?: Prisma.CoinPackageOmit<ExtArgs> | null
}
