
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Interaction` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Interaction
 * 
 */
export type InteractionModel = runtime.Types.Result.DefaultSelection<Prisma.$InteractionPayload>

export type AggregateInteraction = {
  _count: InteractionCountAggregateOutputType | null
  _min: InteractionMinAggregateOutputType | null
  _max: InteractionMaxAggregateOutputType | null
}

export type InteractionMinAggregateOutputType = {
  id: string | null
  fromId: string | null
  toId: string | null
  type: $Enums.InteractionType | null
  createdAt: Date | null
}

export type InteractionMaxAggregateOutputType = {
  id: string | null
  fromId: string | null
  toId: string | null
  type: $Enums.InteractionType | null
  createdAt: Date | null
}

export type InteractionCountAggregateOutputType = {
  id: number
  fromId: number
  toId: number
  type: number
  createdAt: number
  _all: number
}


export type InteractionMinAggregateInputType = {
  id?: true
  fromId?: true
  toId?: true
  type?: true
  createdAt?: true
}

export type InteractionMaxAggregateInputType = {
  id?: true
  fromId?: true
  toId?: true
  type?: true
  createdAt?: true
}

export type InteractionCountAggregateInputType = {
  id?: true
  fromId?: true
  toId?: true
  type?: true
  createdAt?: true
  _all?: true
}

export type InteractionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Interaction to aggregate.
   */
  where?: Prisma.InteractionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Interactions to fetch.
   */
  orderBy?: Prisma.InteractionOrderByWithRelationInput | Prisma.InteractionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.InteractionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Interactions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Interactions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Interactions
  **/
  _count?: true | InteractionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: InteractionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: InteractionMaxAggregateInputType
}

export type GetInteractionAggregateType<T extends InteractionAggregateArgs> = {
      [P in keyof T & keyof AggregateInteraction]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateInteraction[P]>
    : Prisma.GetScalarType<T[P], AggregateInteraction[P]>
}




export type InteractionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.InteractionWhereInput
  orderBy?: Prisma.InteractionOrderByWithAggregationInput | Prisma.InteractionOrderByWithAggregationInput[]
  by: Prisma.InteractionScalarFieldEnum[] | Prisma.InteractionScalarFieldEnum
  having?: Prisma.InteractionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: InteractionCountAggregateInputType | true
  _min?: InteractionMinAggregateInputType
  _max?: InteractionMaxAggregateInputType
}

export type InteractionGroupByOutputType = {
  id: string
  fromId: string
  toId: string
  type: $Enums.InteractionType
  createdAt: Date
  _count: InteractionCountAggregateOutputType | null
  _min: InteractionMinAggregateOutputType | null
  _max: InteractionMaxAggregateOutputType | null
}

export type GetInteractionGroupByPayload<T extends InteractionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<InteractionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof InteractionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], InteractionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], InteractionGroupByOutputType[P]>
      }
    >
  >



export type InteractionWhereInput = {
  AND?: Prisma.InteractionWhereInput | Prisma.InteractionWhereInput[]
  OR?: Prisma.InteractionWhereInput[]
  NOT?: Prisma.InteractionWhereInput | Prisma.InteractionWhereInput[]
  id?: Prisma.StringFilter<"Interaction"> | string
  fromId?: Prisma.StringFilter<"Interaction"> | string
  toId?: Prisma.StringFilter<"Interaction"> | string
  type?: Prisma.EnumInteractionTypeFilter<"Interaction"> | $Enums.InteractionType
  createdAt?: Prisma.DateTimeFilter<"Interaction"> | Date | string
  from?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  to?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type InteractionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  fromId?: Prisma.SortOrder
  toId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  from?: Prisma.UserOrderByWithRelationInput
  to?: Prisma.UserOrderByWithRelationInput
  _relevance?: Prisma.InteractionOrderByRelevanceInput
}

export type InteractionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  fromId_toId_type?: Prisma.InteractionFromIdToIdTypeCompoundUniqueInput
  AND?: Prisma.InteractionWhereInput | Prisma.InteractionWhereInput[]
  OR?: Prisma.InteractionWhereInput[]
  NOT?: Prisma.InteractionWhereInput | Prisma.InteractionWhereInput[]
  fromId?: Prisma.StringFilter<"Interaction"> | string
  toId?: Prisma.StringFilter<"Interaction"> | string
  type?: Prisma.EnumInteractionTypeFilter<"Interaction"> | $Enums.InteractionType
  createdAt?: Prisma.DateTimeFilter<"Interaction"> | Date | string
  from?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  to?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id" | "fromId_toId_type">

export type InteractionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  fromId?: Prisma.SortOrder
  toId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.InteractionCountOrderByAggregateInput
  _max?: Prisma.InteractionMaxOrderByAggregateInput
  _min?: Prisma.InteractionMinOrderByAggregateInput
}

export type InteractionScalarWhereWithAggregatesInput = {
  AND?: Prisma.InteractionScalarWhereWithAggregatesInput | Prisma.InteractionScalarWhereWithAggregatesInput[]
  OR?: Prisma.InteractionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.InteractionScalarWhereWithAggregatesInput | Prisma.InteractionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Interaction"> | string
  fromId?: Prisma.StringWithAggregatesFilter<"Interaction"> | string
  toId?: Prisma.StringWithAggregatesFilter<"Interaction"> | string
  type?: Prisma.EnumInteractionTypeWithAggregatesFilter<"Interaction"> | $Enums.InteractionType
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Interaction"> | Date | string
}

export type InteractionCreateInput = {
  id?: string
  type: $Enums.InteractionType
  createdAt?: Date | string
  from: Prisma.UserCreateNestedOneWithoutInteractionsFromInput
  to: Prisma.UserCreateNestedOneWithoutInteractionsToInput
}

export type InteractionUncheckedCreateInput = {
  id?: string
  fromId: string
  toId: string
  type: $Enums.InteractionType
  createdAt?: Date | string
}

export type InteractionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumInteractionTypeFieldUpdateOperationsInput | $Enums.InteractionType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  from?: Prisma.UserUpdateOneRequiredWithoutInteractionsFromNestedInput
  to?: Prisma.UserUpdateOneRequiredWithoutInteractionsToNestedInput
}

export type InteractionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fromId?: Prisma.StringFieldUpdateOperationsInput | string
  toId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumInteractionTypeFieldUpdateOperationsInput | $Enums.InteractionType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type InteractionCreateManyInput = {
  id?: string
  fromId: string
  toId: string
  type: $Enums.InteractionType
  createdAt?: Date | string
}

export type InteractionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumInteractionTypeFieldUpdateOperationsInput | $Enums.InteractionType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type InteractionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fromId?: Prisma.StringFieldUpdateOperationsInput | string
  toId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumInteractionTypeFieldUpdateOperationsInput | $Enums.InteractionType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type InteractionListRelationFilter = {
  every?: Prisma.InteractionWhereInput
  some?: Prisma.InteractionWhereInput
  none?: Prisma.InteractionWhereInput
}

export type InteractionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type InteractionOrderByRelevanceInput = {
  fields: Prisma.InteractionOrderByRelevanceFieldEnum | Prisma.InteractionOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type InteractionFromIdToIdTypeCompoundUniqueInput = {
  fromId: string
  toId: string
  type: $Enums.InteractionType
}

export type InteractionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fromId?: Prisma.SortOrder
  toId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type InteractionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fromId?: Prisma.SortOrder
  toId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type InteractionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fromId?: Prisma.SortOrder
  toId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type InteractionCreateNestedManyWithoutFromInput = {
  create?: Prisma.XOR<Prisma.InteractionCreateWithoutFromInput, Prisma.InteractionUncheckedCreateWithoutFromInput> | Prisma.InteractionCreateWithoutFromInput[] | Prisma.InteractionUncheckedCreateWithoutFromInput[]
  connectOrCreate?: Prisma.InteractionCreateOrConnectWithoutFromInput | Prisma.InteractionCreateOrConnectWithoutFromInput[]
  createMany?: Prisma.InteractionCreateManyFromInputEnvelope
  connect?: Prisma.InteractionWhereUniqueInput | Prisma.InteractionWhereUniqueInput[]
}

export type InteractionCreateNestedManyWithoutToInput = {
  create?: Prisma.XOR<Prisma.InteractionCreateWithoutToInput, Prisma.InteractionUncheckedCreateWithoutToInput> | Prisma.InteractionCreateWithoutToInput[] | Prisma.InteractionUncheckedCreateWithoutToInput[]
  connectOrCreate?: Prisma.InteractionCreateOrConnectWithoutToInput | Prisma.InteractionCreateOrConnectWithoutToInput[]
  createMany?: Prisma.InteractionCreateManyToInputEnvelope
  connect?: Prisma.InteractionWhereUniqueInput | Prisma.InteractionWhereUniqueInput[]
}

export type InteractionUncheckedCreateNestedManyWithoutFromInput = {
  create?: Prisma.XOR<Prisma.InteractionCreateWithoutFromInput, Prisma.InteractionUncheckedCreateWithoutFromInput> | Prisma.InteractionCreateWithoutFromInput[] | Prisma.InteractionUncheckedCreateWithoutFromInput[]
  connectOrCreate?: Prisma.InteractionCreateOrConnectWithoutFromInput | Prisma.InteractionCreateOrConnectWithoutFromInput[]
  createMany?: Prisma.InteractionCreateManyFromInputEnvelope
  connect?: Prisma.InteractionWhereUniqueInput | Prisma.InteractionWhereUniqueInput[]
}

export type InteractionUncheckedCreateNestedManyWithoutToInput = {
  create?: Prisma.XOR<Prisma.InteractionCreateWithoutToInput, Prisma.InteractionUncheckedCreateWithoutToInput> | Prisma.InteractionCreateWithoutToInput[] | Prisma.InteractionUncheckedCreateWithoutToInput[]
  connectOrCreate?: Prisma.InteractionCreateOrConnectWithoutToInput | Prisma.InteractionCreateOrConnectWithoutToInput[]
  createMany?: Prisma.InteractionCreateManyToInputEnvelope
  connect?: Prisma.InteractionWhereUniqueInput | Prisma.InteractionWhereUniqueInput[]
}

export type InteractionUpdateManyWithoutFromNestedInput = {
  create?: Prisma.XOR<Prisma.InteractionCreateWithoutFromInput, Prisma.InteractionUncheckedCreateWithoutFromInput> | Prisma.InteractionCreateWithoutFromInput[] | Prisma.InteractionUncheckedCreateWithoutFromInput[]
  connectOrCreate?: Prisma.InteractionCreateOrConnectWithoutFromInput | Prisma.InteractionCreateOrConnectWithoutFromInput[]
  upsert?: Prisma.InteractionUpsertWithWhereUniqueWithoutFromInput | Prisma.InteractionUpsertWithWhereUniqueWithoutFromInput[]
  createMany?: Prisma.InteractionCreateManyFromInputEnvelope
  set?: Prisma.InteractionWhereUniqueInput | Prisma.InteractionWhereUniqueInput[]
  disconnect?: Prisma.InteractionWhereUniqueInput | Prisma.InteractionWhereUniqueInput[]
  delete?: Prisma.InteractionWhereUniqueInput | Prisma.InteractionWhereUniqueInput[]
  connect?: Prisma.InteractionWhereUniqueInput | Prisma.InteractionWhereUniqueInput[]
  update?: Prisma.InteractionUpdateWithWhereUniqueWithoutFromInput | Prisma.InteractionUpdateWithWhereUniqueWithoutFromInput[]
  updateMany?: Prisma.InteractionUpdateManyWithWhereWithoutFromInput | Prisma.InteractionUpdateManyWithWhereWithoutFromInput[]
  deleteMany?: Prisma.InteractionScalarWhereInput | Prisma.InteractionScalarWhereInput[]
}

export type InteractionUpdateManyWithoutToNestedInput = {
  create?: Prisma.XOR<Prisma.InteractionCreateWithoutToInput, Prisma.InteractionUncheckedCreateWithoutToInput> | Prisma.InteractionCreateWithoutToInput[] | Prisma.InteractionUncheckedCreateWithoutToInput[]
  connectOrCreate?: Prisma.InteractionCreateOrConnectWithoutToInput | Prisma.InteractionCreateOrConnectWithoutToInput[]
  upsert?: Prisma.InteractionUpsertWithWhereUniqueWithoutToInput | Prisma.InteractionUpsertWithWhereUniqueWithoutToInput[]
  createMany?: Prisma.InteractionCreateManyToInputEnvelope
  set?: Prisma.InteractionWhereUniqueInput | Prisma.InteractionWhereUniqueInput[]
  disconnect?: Prisma.InteractionWhereUniqueInput | Prisma.InteractionWhereUniqueInput[]
  delete?: Prisma.InteractionWhereUniqueInput | Prisma.InteractionWhereUniqueInput[]
  connect?: Prisma.InteractionWhereUniqueInput | Prisma.InteractionWhereUniqueInput[]
  update?: Prisma.InteractionUpdateWithWhereUniqueWithoutToInput | Prisma.InteractionUpdateWithWhereUniqueWithoutToInput[]
  updateMany?: Prisma.InteractionUpdateManyWithWhereWithoutToInput | Prisma.InteractionUpdateManyWithWhereWithoutToInput[]
  deleteMany?: Prisma.InteractionScalarWhereInput | Prisma.InteractionScalarWhereInput[]
}

export type InteractionUncheckedUpdateManyWithoutFromNestedInput = {
  create?: Prisma.XOR<Prisma.InteractionCreateWithoutFromInput, Prisma.InteractionUncheckedCreateWithoutFromInput> | Prisma.InteractionCreateWithoutFromInput[] | Prisma.InteractionUncheckedCreateWithoutFromInput[]
  connectOrCreate?: Prisma.InteractionCreateOrConnectWithoutFromInput | Prisma.InteractionCreateOrConnectWithoutFromInput[]
  upsert?: Prisma.InteractionUpsertWithWhereUniqueWithoutFromInput | Prisma.InteractionUpsertWithWhereUniqueWithoutFromInput[]
  createMany?: Prisma.InteractionCreateManyFromInputEnvelope
  set?: Prisma.InteractionWhereUniqueInput | Prisma.InteractionWhereUniqueInput[]
  disconnect?: Prisma.InteractionWhereUniqueInput | Prisma.InteractionWhereUniqueInput[]
  delete?: Prisma.InteractionWhereUniqueInput | Prisma.InteractionWhereUniqueInput[]
  connect?: Prisma.InteractionWhereUniqueInput | Prisma.InteractionWhereUniqueInput[]
  update?: Prisma.InteractionUpdateWithWhereUniqueWithoutFromInput | Prisma.InteractionUpdateWithWhereUniqueWithoutFromInput[]
  updateMany?: Prisma.InteractionUpdateManyWithWhereWithoutFromInput | Prisma.InteractionUpdateManyWithWhereWithoutFromInput[]
  deleteMany?: Prisma.InteractionScalarWhereInput | Prisma.InteractionScalarWhereInput[]
}

export type InteractionUncheckedUpdateManyWithoutToNestedInput = {
  create?: Prisma.XOR<Prisma.InteractionCreateWithoutToInput, Prisma.InteractionUncheckedCreateWithoutToInput> | Prisma.InteractionCreateWithoutToInput[] | Prisma.InteractionUncheckedCreateWithoutToInput[]
  connectOrCreate?: Prisma.InteractionCreateOrConnectWithoutToInput | Prisma.InteractionCreateOrConnectWithoutToInput[]
  upsert?: Prisma.InteractionUpsertWithWhereUniqueWithoutToInput | Prisma.InteractionUpsertWithWhereUniqueWithoutToInput[]
  createMany?: Prisma.InteractionCreateManyToInputEnvelope
  set?: Prisma.InteractionWhereUniqueInput | Prisma.InteractionWhereUniqueInput[]
  disconnect?: Prisma.InteractionWhereUniqueInput | Prisma.InteractionWhereUniqueInput[]
  delete?: Prisma.InteractionWhereUniqueInput | Prisma.InteractionWhereUniqueInput[]
  connect?: Prisma.InteractionWhereUniqueInput | Prisma.InteractionWhereUniqueInput[]
  update?: Prisma.InteractionUpdateWithWhereUniqueWithoutToInput | Prisma.InteractionUpdateWithWhereUniqueWithoutToInput[]
  updateMany?: Prisma.InteractionUpdateManyWithWhereWithoutToInput | Prisma.InteractionUpdateManyWithWhereWithoutToInput[]
  deleteMany?: Prisma.InteractionScalarWhereInput | Prisma.InteractionScalarWhereInput[]
}

export type EnumInteractionTypeFieldUpdateOperationsInput = {
  set?: $Enums.InteractionType
}

export type InteractionCreateWithoutFromInput = {
  id?: string
  type: $Enums.InteractionType
  createdAt?: Date | string
  to: Prisma.UserCreateNestedOneWithoutInteractionsToInput
}

export type InteractionUncheckedCreateWithoutFromInput = {
  id?: string
  toId: string
  type: $Enums.InteractionType
  createdAt?: Date | string
}

export type InteractionCreateOrConnectWithoutFromInput = {
  where: Prisma.InteractionWhereUniqueInput
  create: Prisma.XOR<Prisma.InteractionCreateWithoutFromInput, Prisma.InteractionUncheckedCreateWithoutFromInput>
}

export type InteractionCreateManyFromInputEnvelope = {
  data: Prisma.InteractionCreateManyFromInput | Prisma.InteractionCreateManyFromInput[]
  skipDuplicates?: boolean
}

export type InteractionCreateWithoutToInput = {
  id?: string
  type: $Enums.InteractionType
  createdAt?: Date | string
  from: Prisma.UserCreateNestedOneWithoutInteractionsFromInput
}

export type InteractionUncheckedCreateWithoutToInput = {
  id?: string
  fromId: string
  type: $Enums.InteractionType
  createdAt?: Date | string
}

export type InteractionCreateOrConnectWithoutToInput = {
  where: Prisma.InteractionWhereUniqueInput
  create: Prisma.XOR<Prisma.InteractionCreateWithoutToInput, Prisma.InteractionUncheckedCreateWithoutToInput>
}

export type InteractionCreateManyToInputEnvelope = {
  data: Prisma.InteractionCreateManyToInput | Prisma.InteractionCreateManyToInput[]
  skipDuplicates?: boolean
}

export type InteractionUpsertWithWhereUniqueWithoutFromInput = {
  where: Prisma.InteractionWhereUniqueInput
  update: Prisma.XOR<Prisma.InteractionUpdateWithoutFromInput, Prisma.InteractionUncheckedUpdateWithoutFromInput>
  create: Prisma.XOR<Prisma.InteractionCreateWithoutFromInput, Prisma.InteractionUncheckedCreateWithoutFromInput>
}

export type InteractionUpdateWithWhereUniqueWithoutFromInput = {
  where: Prisma.InteractionWhereUniqueInput
  data: Prisma.XOR<Prisma.InteractionUpdateWithoutFromInput, Prisma.InteractionUncheckedUpdateWithoutFromInput>
}

export type InteractionUpdateManyWithWhereWithoutFromInput = {
  where: Prisma.InteractionScalarWhereInput
  data: Prisma.XOR<Prisma.InteractionUpdateManyMutationInput, Prisma.InteractionUncheckedUpdateManyWithoutFromInput>
}

export type InteractionScalarWhereInput = {
  AND?: Prisma.InteractionScalarWhereInput | Prisma.InteractionScalarWhereInput[]
  OR?: Prisma.InteractionScalarWhereInput[]
  NOT?: Prisma.InteractionScalarWhereInput | Prisma.InteractionScalarWhereInput[]
  id?: Prisma.StringFilter<"Interaction"> | string
  fromId?: Prisma.StringFilter<"Interaction"> | string
  toId?: Prisma.StringFilter<"Interaction"> | string
  type?: Prisma.EnumInteractionTypeFilter<"Interaction"> | $Enums.InteractionType
  createdAt?: Prisma.DateTimeFilter<"Interaction"> | Date | string
}

export type InteractionUpsertWithWhereUniqueWithoutToInput = {
  where: Prisma.InteractionWhereUniqueInput
  update: Prisma.XOR<Prisma.InteractionUpdateWithoutToInput, Prisma.InteractionUncheckedUpdateWithoutToInput>
  create: Prisma.XOR<Prisma.InteractionCreateWithoutToInput, Prisma.InteractionUncheckedCreateWithoutToInput>
}

export type InteractionUpdateWithWhereUniqueWithoutToInput = {
  where: Prisma.InteractionWhereUniqueInput
  data: Prisma.XOR<Prisma.InteractionUpdateWithoutToInput, Prisma.InteractionUncheckedUpdateWithoutToInput>
}

export type InteractionUpdateManyWithWhereWithoutToInput = {
  where: Prisma.InteractionScalarWhereInput
  data: Prisma.XOR<Prisma.InteractionUpdateManyMutationInput, Prisma.InteractionUncheckedUpdateManyWithoutToInput>
}

export type InteractionCreateManyFromInput = {
  id?: string
  toId: string
  type: $Enums.InteractionType
  createdAt?: Date | string
}

export type InteractionCreateManyToInput = {
  id?: string
  fromId: string
  type: $Enums.InteractionType
  createdAt?: Date | string
}

export type InteractionUpdateWithoutFromInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumInteractionTypeFieldUpdateOperationsInput | $Enums.InteractionType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  to?: Prisma.UserUpdateOneRequiredWithoutInteractionsToNestedInput
}

export type InteractionUncheckedUpdateWithoutFromInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  toId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumInteractionTypeFieldUpdateOperationsInput | $Enums.InteractionType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type InteractionUncheckedUpdateManyWithoutFromInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  toId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumInteractionTypeFieldUpdateOperationsInput | $Enums.InteractionType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type InteractionUpdateWithoutToInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumInteractionTypeFieldUpdateOperationsInput | $Enums.InteractionType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  from?: Prisma.UserUpdateOneRequiredWithoutInteractionsFromNestedInput
}

export type InteractionUncheckedUpdateWithoutToInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fromId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumInteractionTypeFieldUpdateOperationsInput | $Enums.InteractionType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type InteractionUncheckedUpdateManyWithoutToInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fromId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumInteractionTypeFieldUpdateOperationsInput | $Enums.InteractionType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type InteractionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fromId?: boolean
  toId?: boolean
  type?: boolean
  createdAt?: boolean
  from?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  to?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["interaction"]>



export type InteractionSelectScalar = {
  id?: boolean
  fromId?: boolean
  toId?: boolean
  type?: boolean
  createdAt?: boolean
}

export type InteractionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "fromId" | "toId" | "type" | "createdAt", ExtArgs["result"]["interaction"]>
export type InteractionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  from?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  to?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $InteractionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Interaction"
  objects: {
    from: Prisma.$UserPayload<ExtArgs>
    to: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    fromId: string
    toId: string
    type: $Enums.InteractionType
    createdAt: Date
  }, ExtArgs["result"]["interaction"]>
  composites: {}
}

export type InteractionGetPayload<S extends boolean | null | undefined | InteractionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$InteractionPayload, S>

export type InteractionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<InteractionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: InteractionCountAggregateInputType | true
  }

export interface InteractionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Interaction'], meta: { name: 'Interaction' } }
  /**
   * Find zero or one Interaction that matches the filter.
   * @param {InteractionFindUniqueArgs} args - Arguments to find a Interaction
   * @example
   * // Get one Interaction
   * const interaction = await prisma.interaction.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends InteractionFindUniqueArgs>(args: Prisma.SelectSubset<T, InteractionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__InteractionClient<runtime.Types.Result.GetResult<Prisma.$InteractionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Interaction that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {InteractionFindUniqueOrThrowArgs} args - Arguments to find a Interaction
   * @example
   * // Get one Interaction
   * const interaction = await prisma.interaction.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends InteractionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, InteractionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__InteractionClient<runtime.Types.Result.GetResult<Prisma.$InteractionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Interaction that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InteractionFindFirstArgs} args - Arguments to find a Interaction
   * @example
   * // Get one Interaction
   * const interaction = await prisma.interaction.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends InteractionFindFirstArgs>(args?: Prisma.SelectSubset<T, InteractionFindFirstArgs<ExtArgs>>): Prisma.Prisma__InteractionClient<runtime.Types.Result.GetResult<Prisma.$InteractionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Interaction that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InteractionFindFirstOrThrowArgs} args - Arguments to find a Interaction
   * @example
   * // Get one Interaction
   * const interaction = await prisma.interaction.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends InteractionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, InteractionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__InteractionClient<runtime.Types.Result.GetResult<Prisma.$InteractionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Interactions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InteractionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Interactions
   * const interactions = await prisma.interaction.findMany()
   * 
   * // Get first 10 Interactions
   * const interactions = await prisma.interaction.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const interactionWithIdOnly = await prisma.interaction.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends InteractionFindManyArgs>(args?: Prisma.SelectSubset<T, InteractionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InteractionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Interaction.
   * @param {InteractionCreateArgs} args - Arguments to create a Interaction.
   * @example
   * // Create one Interaction
   * const Interaction = await prisma.interaction.create({
   *   data: {
   *     // ... data to create a Interaction
   *   }
   * })
   * 
   */
  create<T extends InteractionCreateArgs>(args: Prisma.SelectSubset<T, InteractionCreateArgs<ExtArgs>>): Prisma.Prisma__InteractionClient<runtime.Types.Result.GetResult<Prisma.$InteractionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Interactions.
   * @param {InteractionCreateManyArgs} args - Arguments to create many Interactions.
   * @example
   * // Create many Interactions
   * const interaction = await prisma.interaction.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends InteractionCreateManyArgs>(args?: Prisma.SelectSubset<T, InteractionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Interaction.
   * @param {InteractionDeleteArgs} args - Arguments to delete one Interaction.
   * @example
   * // Delete one Interaction
   * const Interaction = await prisma.interaction.delete({
   *   where: {
   *     // ... filter to delete one Interaction
   *   }
   * })
   * 
   */
  delete<T extends InteractionDeleteArgs>(args: Prisma.SelectSubset<T, InteractionDeleteArgs<ExtArgs>>): Prisma.Prisma__InteractionClient<runtime.Types.Result.GetResult<Prisma.$InteractionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Interaction.
   * @param {InteractionUpdateArgs} args - Arguments to update one Interaction.
   * @example
   * // Update one Interaction
   * const interaction = await prisma.interaction.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends InteractionUpdateArgs>(args: Prisma.SelectSubset<T, InteractionUpdateArgs<ExtArgs>>): Prisma.Prisma__InteractionClient<runtime.Types.Result.GetResult<Prisma.$InteractionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Interactions.
   * @param {InteractionDeleteManyArgs} args - Arguments to filter Interactions to delete.
   * @example
   * // Delete a few Interactions
   * const { count } = await prisma.interaction.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends InteractionDeleteManyArgs>(args?: Prisma.SelectSubset<T, InteractionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Interactions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InteractionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Interactions
   * const interaction = await prisma.interaction.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends InteractionUpdateManyArgs>(args: Prisma.SelectSubset<T, InteractionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Interaction.
   * @param {InteractionUpsertArgs} args - Arguments to update or create a Interaction.
   * @example
   * // Update or create a Interaction
   * const interaction = await prisma.interaction.upsert({
   *   create: {
   *     // ... data to create a Interaction
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Interaction we want to update
   *   }
   * })
   */
  upsert<T extends InteractionUpsertArgs>(args: Prisma.SelectSubset<T, InteractionUpsertArgs<ExtArgs>>): Prisma.Prisma__InteractionClient<runtime.Types.Result.GetResult<Prisma.$InteractionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Interactions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InteractionCountArgs} args - Arguments to filter Interactions to count.
   * @example
   * // Count the number of Interactions
   * const count = await prisma.interaction.count({
   *   where: {
   *     // ... the filter for the Interactions we want to count
   *   }
   * })
  **/
  count<T extends InteractionCountArgs>(
    args?: Prisma.Subset<T, InteractionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], InteractionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Interaction.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InteractionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends InteractionAggregateArgs>(args: Prisma.Subset<T, InteractionAggregateArgs>): Prisma.PrismaPromise<GetInteractionAggregateType<T>>

  /**
   * Group by Interaction.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InteractionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends InteractionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: InteractionGroupByArgs['orderBy'] }
      : { orderBy?: InteractionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, InteractionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetInteractionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Interaction model
 */
readonly fields: InteractionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Interaction.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__InteractionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  from<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  to<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Interaction model
 */
export interface InteractionFieldRefs {
  readonly id: Prisma.FieldRef<"Interaction", 'String'>
  readonly fromId: Prisma.FieldRef<"Interaction", 'String'>
  readonly toId: Prisma.FieldRef<"Interaction", 'String'>
  readonly type: Prisma.FieldRef<"Interaction", 'InteractionType'>
  readonly createdAt: Prisma.FieldRef<"Interaction", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Interaction findUnique
 */
export type InteractionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Interaction
   */
  select?: Prisma.InteractionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Interaction
   */
  omit?: Prisma.InteractionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InteractionInclude<ExtArgs> | null
  /**
   * Filter, which Interaction to fetch.
   */
  where: Prisma.InteractionWhereUniqueInput
}

/**
 * Interaction findUniqueOrThrow
 */
export type InteractionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Interaction
   */
  select?: Prisma.InteractionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Interaction
   */
  omit?: Prisma.InteractionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InteractionInclude<ExtArgs> | null
  /**
   * Filter, which Interaction to fetch.
   */
  where: Prisma.InteractionWhereUniqueInput
}

/**
 * Interaction findFirst
 */
export type InteractionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Interaction
   */
  select?: Prisma.InteractionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Interaction
   */
  omit?: Prisma.InteractionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InteractionInclude<ExtArgs> | null
  /**
   * Filter, which Interaction to fetch.
   */
  where?: Prisma.InteractionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Interactions to fetch.
   */
  orderBy?: Prisma.InteractionOrderByWithRelationInput | Prisma.InteractionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Interactions.
   */
  cursor?: Prisma.InteractionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Interactions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Interactions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Interactions.
   */
  distinct?: Prisma.InteractionScalarFieldEnum | Prisma.InteractionScalarFieldEnum[]
}

/**
 * Interaction findFirstOrThrow
 */
export type InteractionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Interaction
   */
  select?: Prisma.InteractionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Interaction
   */
  omit?: Prisma.InteractionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InteractionInclude<ExtArgs> | null
  /**
   * Filter, which Interaction to fetch.
   */
  where?: Prisma.InteractionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Interactions to fetch.
   */
  orderBy?: Prisma.InteractionOrderByWithRelationInput | Prisma.InteractionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Interactions.
   */
  cursor?: Prisma.InteractionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Interactions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Interactions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Interactions.
   */
  distinct?: Prisma.InteractionScalarFieldEnum | Prisma.InteractionScalarFieldEnum[]
}

/**
 * Interaction findMany
 */
export type InteractionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Interaction
   */
  select?: Prisma.InteractionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Interaction
   */
  omit?: Prisma.InteractionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InteractionInclude<ExtArgs> | null
  /**
   * Filter, which Interactions to fetch.
   */
  where?: Prisma.InteractionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Interactions to fetch.
   */
  orderBy?: Prisma.InteractionOrderByWithRelationInput | Prisma.InteractionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Interactions.
   */
  cursor?: Prisma.InteractionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Interactions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Interactions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Interactions.
   */
  distinct?: Prisma.InteractionScalarFieldEnum | Prisma.InteractionScalarFieldEnum[]
}

/**
 * Interaction create
 */
export type InteractionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Interaction
   */
  select?: Prisma.InteractionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Interaction
   */
  omit?: Prisma.InteractionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InteractionInclude<ExtArgs> | null
  /**
   * The data needed to create a Interaction.
   */
  data: Prisma.XOR<Prisma.InteractionCreateInput, Prisma.InteractionUncheckedCreateInput>
}

/**
 * Interaction createMany
 */
export type InteractionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Interactions.
   */
  data: Prisma.InteractionCreateManyInput | Prisma.InteractionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Interaction update
 */
export type InteractionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Interaction
   */
  select?: Prisma.InteractionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Interaction
   */
  omit?: Prisma.InteractionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InteractionInclude<ExtArgs> | null
  /**
   * The data needed to update a Interaction.
   */
  data: Prisma.XOR<Prisma.InteractionUpdateInput, Prisma.InteractionUncheckedUpdateInput>
  /**
   * Choose, which Interaction to update.
   */
  where: Prisma.InteractionWhereUniqueInput
}

/**
 * Interaction updateMany
 */
export type InteractionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Interactions.
   */
  data: Prisma.XOR<Prisma.InteractionUpdateManyMutationInput, Prisma.InteractionUncheckedUpdateManyInput>
  /**
   * Filter which Interactions to update
   */
  where?: Prisma.InteractionWhereInput
  /**
   * Limit how many Interactions to update.
   */
  limit?: number
}

/**
 * Interaction upsert
 */
export type InteractionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Interaction
   */
  select?: Prisma.InteractionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Interaction
   */
  omit?: Prisma.InteractionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InteractionInclude<ExtArgs> | null
  /**
   * The filter to search for the Interaction to update in case it exists.
   */
  where: Prisma.InteractionWhereUniqueInput
  /**
   * In case the Interaction found by the `where` argument doesn't exist, create a new Interaction with this data.
   */
  create: Prisma.XOR<Prisma.InteractionCreateInput, Prisma.InteractionUncheckedCreateInput>
  /**
   * In case the Interaction was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.InteractionUpdateInput, Prisma.InteractionUncheckedUpdateInput>
}

/**
 * Interaction delete
 */
export type InteractionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Interaction
   */
  select?: Prisma.InteractionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Interaction
   */
  omit?: Prisma.InteractionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InteractionInclude<ExtArgs> | null
  /**
   * Filter which Interaction to delete.
   */
  where: Prisma.InteractionWhereUniqueInput
}

/**
 * Interaction deleteMany
 */
export type InteractionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Interactions to delete
   */
  where?: Prisma.InteractionWhereInput
  /**
   * Limit how many Interactions to delete.
   */
  limit?: number
}

/**
 * Interaction without action
 */
export type InteractionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Interaction
   */
  select?: Prisma.InteractionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Interaction
   */
  omit?: Prisma.InteractionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InteractionInclude<ExtArgs> | null
}
