
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ModerationRule` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ModerationRule
 * 
 */
export type ModerationRuleModel = runtime.Types.Result.DefaultSelection<Prisma.$ModerationRulePayload>

export type AggregateModerationRule = {
  _count: ModerationRuleCountAggregateOutputType | null
  _min: ModerationRuleMinAggregateOutputType | null
  _max: ModerationRuleMaxAggregateOutputType | null
}

export type ModerationRuleMinAggregateOutputType = {
  id: string | null
  kind: $Enums.ModRuleKind | null
  pattern: string | null
  action: $Enums.ModAction | null
  active: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ModerationRuleMaxAggregateOutputType = {
  id: string | null
  kind: $Enums.ModRuleKind | null
  pattern: string | null
  action: $Enums.ModAction | null
  active: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ModerationRuleCountAggregateOutputType = {
  id: number
  kind: number
  pattern: number
  action: number
  active: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ModerationRuleMinAggregateInputType = {
  id?: true
  kind?: true
  pattern?: true
  action?: true
  active?: true
  createdAt?: true
  updatedAt?: true
}

export type ModerationRuleMaxAggregateInputType = {
  id?: true
  kind?: true
  pattern?: true
  action?: true
  active?: true
  createdAt?: true
  updatedAt?: true
}

export type ModerationRuleCountAggregateInputType = {
  id?: true
  kind?: true
  pattern?: true
  action?: true
  active?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ModerationRuleAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ModerationRule to aggregate.
   */
  where?: Prisma.ModerationRuleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ModerationRules to fetch.
   */
  orderBy?: Prisma.ModerationRuleOrderByWithRelationInput | Prisma.ModerationRuleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ModerationRuleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ModerationRules from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ModerationRules.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ModerationRules
  **/
  _count?: true | ModerationRuleCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ModerationRuleMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ModerationRuleMaxAggregateInputType
}

export type GetModerationRuleAggregateType<T extends ModerationRuleAggregateArgs> = {
      [P in keyof T & keyof AggregateModerationRule]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateModerationRule[P]>
    : Prisma.GetScalarType<T[P], AggregateModerationRule[P]>
}




export type ModerationRuleGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ModerationRuleWhereInput
  orderBy?: Prisma.ModerationRuleOrderByWithAggregationInput | Prisma.ModerationRuleOrderByWithAggregationInput[]
  by: Prisma.ModerationRuleScalarFieldEnum[] | Prisma.ModerationRuleScalarFieldEnum
  having?: Prisma.ModerationRuleScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ModerationRuleCountAggregateInputType | true
  _min?: ModerationRuleMinAggregateInputType
  _max?: ModerationRuleMaxAggregateInputType
}

export type ModerationRuleGroupByOutputType = {
  id: string
  kind: $Enums.ModRuleKind
  pattern: string
  action: $Enums.ModAction
  active: boolean
  createdAt: Date
  updatedAt: Date
  _count: ModerationRuleCountAggregateOutputType | null
  _min: ModerationRuleMinAggregateOutputType | null
  _max: ModerationRuleMaxAggregateOutputType | null
}

export type GetModerationRuleGroupByPayload<T extends ModerationRuleGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ModerationRuleGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ModerationRuleGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ModerationRuleGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ModerationRuleGroupByOutputType[P]>
      }
    >
  >



export type ModerationRuleWhereInput = {
  AND?: Prisma.ModerationRuleWhereInput | Prisma.ModerationRuleWhereInput[]
  OR?: Prisma.ModerationRuleWhereInput[]
  NOT?: Prisma.ModerationRuleWhereInput | Prisma.ModerationRuleWhereInput[]
  id?: Prisma.StringFilter<"ModerationRule"> | string
  kind?: Prisma.EnumModRuleKindFilter<"ModerationRule"> | $Enums.ModRuleKind
  pattern?: Prisma.StringFilter<"ModerationRule"> | string
  action?: Prisma.EnumModActionFilter<"ModerationRule"> | $Enums.ModAction
  active?: Prisma.BoolFilter<"ModerationRule"> | boolean
  createdAt?: Prisma.DateTimeFilter<"ModerationRule"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ModerationRule"> | Date | string
}

export type ModerationRuleOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  kind?: Prisma.SortOrder
  pattern?: Prisma.SortOrder
  action?: Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _relevance?: Prisma.ModerationRuleOrderByRelevanceInput
}

export type ModerationRuleWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ModerationRuleWhereInput | Prisma.ModerationRuleWhereInput[]
  OR?: Prisma.ModerationRuleWhereInput[]
  NOT?: Prisma.ModerationRuleWhereInput | Prisma.ModerationRuleWhereInput[]
  kind?: Prisma.EnumModRuleKindFilter<"ModerationRule"> | $Enums.ModRuleKind
  pattern?: Prisma.StringFilter<"ModerationRule"> | string
  action?: Prisma.EnumModActionFilter<"ModerationRule"> | $Enums.ModAction
  active?: Prisma.BoolFilter<"ModerationRule"> | boolean
  createdAt?: Prisma.DateTimeFilter<"ModerationRule"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ModerationRule"> | Date | string
}, "id">

export type ModerationRuleOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  kind?: Prisma.SortOrder
  pattern?: Prisma.SortOrder
  action?: Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ModerationRuleCountOrderByAggregateInput
  _max?: Prisma.ModerationRuleMaxOrderByAggregateInput
  _min?: Prisma.ModerationRuleMinOrderByAggregateInput
}

export type ModerationRuleScalarWhereWithAggregatesInput = {
  AND?: Prisma.ModerationRuleScalarWhereWithAggregatesInput | Prisma.ModerationRuleScalarWhereWithAggregatesInput[]
  OR?: Prisma.ModerationRuleScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ModerationRuleScalarWhereWithAggregatesInput | Prisma.ModerationRuleScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ModerationRule"> | string
  kind?: Prisma.EnumModRuleKindWithAggregatesFilter<"ModerationRule"> | $Enums.ModRuleKind
  pattern?: Prisma.StringWithAggregatesFilter<"ModerationRule"> | string
  action?: Prisma.EnumModActionWithAggregatesFilter<"ModerationRule"> | $Enums.ModAction
  active?: Prisma.BoolWithAggregatesFilter<"ModerationRule"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ModerationRule"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ModerationRule"> | Date | string
}

export type ModerationRuleCreateInput = {
  id?: string
  kind: $Enums.ModRuleKind
  pattern: string
  action: $Enums.ModAction
  active?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ModerationRuleUncheckedCreateInput = {
  id?: string
  kind: $Enums.ModRuleKind
  pattern: string
  action: $Enums.ModAction
  active?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ModerationRuleUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumModRuleKindFieldUpdateOperationsInput | $Enums.ModRuleKind
  pattern?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.EnumModActionFieldUpdateOperationsInput | $Enums.ModAction
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ModerationRuleUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumModRuleKindFieldUpdateOperationsInput | $Enums.ModRuleKind
  pattern?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.EnumModActionFieldUpdateOperationsInput | $Enums.ModAction
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ModerationRuleCreateManyInput = {
  id?: string
  kind: $Enums.ModRuleKind
  pattern: string
  action: $Enums.ModAction
  active?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ModerationRuleUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumModRuleKindFieldUpdateOperationsInput | $Enums.ModRuleKind
  pattern?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.EnumModActionFieldUpdateOperationsInput | $Enums.ModAction
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ModerationRuleUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumModRuleKindFieldUpdateOperationsInput | $Enums.ModRuleKind
  pattern?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.EnumModActionFieldUpdateOperationsInput | $Enums.ModAction
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ModerationRuleOrderByRelevanceInput = {
  fields: Prisma.ModerationRuleOrderByRelevanceFieldEnum | Prisma.ModerationRuleOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type ModerationRuleCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  kind?: Prisma.SortOrder
  pattern?: Prisma.SortOrder
  action?: Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ModerationRuleMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  kind?: Prisma.SortOrder
  pattern?: Prisma.SortOrder
  action?: Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ModerationRuleMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  kind?: Prisma.SortOrder
  pattern?: Prisma.SortOrder
  action?: Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type EnumModRuleKindFieldUpdateOperationsInput = {
  set?: $Enums.ModRuleKind
}

export type EnumModActionFieldUpdateOperationsInput = {
  set?: $Enums.ModAction
}



export type ModerationRuleSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  kind?: boolean
  pattern?: boolean
  action?: boolean
  active?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["moderationRule"]>



export type ModerationRuleSelectScalar = {
  id?: boolean
  kind?: boolean
  pattern?: boolean
  action?: boolean
  active?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ModerationRuleOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "kind" | "pattern" | "action" | "active" | "createdAt" | "updatedAt", ExtArgs["result"]["moderationRule"]>

export type $ModerationRulePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ModerationRule"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    kind: $Enums.ModRuleKind
    pattern: string
    action: $Enums.ModAction
    active: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["moderationRule"]>
  composites: {}
}

export type ModerationRuleGetPayload<S extends boolean | null | undefined | ModerationRuleDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ModerationRulePayload, S>

export type ModerationRuleCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ModerationRuleFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ModerationRuleCountAggregateInputType | true
  }

export interface ModerationRuleDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ModerationRule'], meta: { name: 'ModerationRule' } }
  /**
   * Find zero or one ModerationRule that matches the filter.
   * @param {ModerationRuleFindUniqueArgs} args - Arguments to find a ModerationRule
   * @example
   * // Get one ModerationRule
   * const moderationRule = await prisma.moderationRule.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ModerationRuleFindUniqueArgs>(args: Prisma.SelectSubset<T, ModerationRuleFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ModerationRuleClient<runtime.Types.Result.GetResult<Prisma.$ModerationRulePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ModerationRule that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ModerationRuleFindUniqueOrThrowArgs} args - Arguments to find a ModerationRule
   * @example
   * // Get one ModerationRule
   * const moderationRule = await prisma.moderationRule.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ModerationRuleFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ModerationRuleFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ModerationRuleClient<runtime.Types.Result.GetResult<Prisma.$ModerationRulePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ModerationRule that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ModerationRuleFindFirstArgs} args - Arguments to find a ModerationRule
   * @example
   * // Get one ModerationRule
   * const moderationRule = await prisma.moderationRule.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ModerationRuleFindFirstArgs>(args?: Prisma.SelectSubset<T, ModerationRuleFindFirstArgs<ExtArgs>>): Prisma.Prisma__ModerationRuleClient<runtime.Types.Result.GetResult<Prisma.$ModerationRulePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ModerationRule that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ModerationRuleFindFirstOrThrowArgs} args - Arguments to find a ModerationRule
   * @example
   * // Get one ModerationRule
   * const moderationRule = await prisma.moderationRule.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ModerationRuleFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ModerationRuleFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ModerationRuleClient<runtime.Types.Result.GetResult<Prisma.$ModerationRulePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ModerationRules that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ModerationRuleFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ModerationRules
   * const moderationRules = await prisma.moderationRule.findMany()
   * 
   * // Get first 10 ModerationRules
   * const moderationRules = await prisma.moderationRule.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const moderationRuleWithIdOnly = await prisma.moderationRule.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ModerationRuleFindManyArgs>(args?: Prisma.SelectSubset<T, ModerationRuleFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ModerationRulePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ModerationRule.
   * @param {ModerationRuleCreateArgs} args - Arguments to create a ModerationRule.
   * @example
   * // Create one ModerationRule
   * const ModerationRule = await prisma.moderationRule.create({
   *   data: {
   *     // ... data to create a ModerationRule
   *   }
   * })
   * 
   */
  create<T extends ModerationRuleCreateArgs>(args: Prisma.SelectSubset<T, ModerationRuleCreateArgs<ExtArgs>>): Prisma.Prisma__ModerationRuleClient<runtime.Types.Result.GetResult<Prisma.$ModerationRulePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ModerationRules.
   * @param {ModerationRuleCreateManyArgs} args - Arguments to create many ModerationRules.
   * @example
   * // Create many ModerationRules
   * const moderationRule = await prisma.moderationRule.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ModerationRuleCreateManyArgs>(args?: Prisma.SelectSubset<T, ModerationRuleCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a ModerationRule.
   * @param {ModerationRuleDeleteArgs} args - Arguments to delete one ModerationRule.
   * @example
   * // Delete one ModerationRule
   * const ModerationRule = await prisma.moderationRule.delete({
   *   where: {
   *     // ... filter to delete one ModerationRule
   *   }
   * })
   * 
   */
  delete<T extends ModerationRuleDeleteArgs>(args: Prisma.SelectSubset<T, ModerationRuleDeleteArgs<ExtArgs>>): Prisma.Prisma__ModerationRuleClient<runtime.Types.Result.GetResult<Prisma.$ModerationRulePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ModerationRule.
   * @param {ModerationRuleUpdateArgs} args - Arguments to update one ModerationRule.
   * @example
   * // Update one ModerationRule
   * const moderationRule = await prisma.moderationRule.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ModerationRuleUpdateArgs>(args: Prisma.SelectSubset<T, ModerationRuleUpdateArgs<ExtArgs>>): Prisma.Prisma__ModerationRuleClient<runtime.Types.Result.GetResult<Prisma.$ModerationRulePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ModerationRules.
   * @param {ModerationRuleDeleteManyArgs} args - Arguments to filter ModerationRules to delete.
   * @example
   * // Delete a few ModerationRules
   * const { count } = await prisma.moderationRule.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ModerationRuleDeleteManyArgs>(args?: Prisma.SelectSubset<T, ModerationRuleDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ModerationRules.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ModerationRuleUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ModerationRules
   * const moderationRule = await prisma.moderationRule.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ModerationRuleUpdateManyArgs>(args: Prisma.SelectSubset<T, ModerationRuleUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one ModerationRule.
   * @param {ModerationRuleUpsertArgs} args - Arguments to update or create a ModerationRule.
   * @example
   * // Update or create a ModerationRule
   * const moderationRule = await prisma.moderationRule.upsert({
   *   create: {
   *     // ... data to create a ModerationRule
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ModerationRule we want to update
   *   }
   * })
   */
  upsert<T extends ModerationRuleUpsertArgs>(args: Prisma.SelectSubset<T, ModerationRuleUpsertArgs<ExtArgs>>): Prisma.Prisma__ModerationRuleClient<runtime.Types.Result.GetResult<Prisma.$ModerationRulePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ModerationRules.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ModerationRuleCountArgs} args - Arguments to filter ModerationRules to count.
   * @example
   * // Count the number of ModerationRules
   * const count = await prisma.moderationRule.count({
   *   where: {
   *     // ... the filter for the ModerationRules we want to count
   *   }
   * })
  **/
  count<T extends ModerationRuleCountArgs>(
    args?: Prisma.Subset<T, ModerationRuleCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ModerationRuleCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ModerationRule.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ModerationRuleAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ModerationRuleAggregateArgs>(args: Prisma.Subset<T, ModerationRuleAggregateArgs>): Prisma.PrismaPromise<GetModerationRuleAggregateType<T>>

  /**
   * Group by ModerationRule.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ModerationRuleGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ModerationRuleGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ModerationRuleGroupByArgs['orderBy'] }
      : { orderBy?: ModerationRuleGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ModerationRuleGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetModerationRuleGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ModerationRule model
 */
readonly fields: ModerationRuleFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ModerationRule.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ModerationRuleClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ModerationRule model
 */
export interface ModerationRuleFieldRefs {
  readonly id: Prisma.FieldRef<"ModerationRule", 'String'>
  readonly kind: Prisma.FieldRef<"ModerationRule", 'ModRuleKind'>
  readonly pattern: Prisma.FieldRef<"ModerationRule", 'String'>
  readonly action: Prisma.FieldRef<"ModerationRule", 'ModAction'>
  readonly active: Prisma.FieldRef<"ModerationRule", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"ModerationRule", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ModerationRule", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ModerationRule findUnique
 */
export type ModerationRuleFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModerationRule
   */
  select?: Prisma.ModerationRuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModerationRule
   */
  omit?: Prisma.ModerationRuleOmit<ExtArgs> | null
  /**
   * Filter, which ModerationRule to fetch.
   */
  where: Prisma.ModerationRuleWhereUniqueInput
}

/**
 * ModerationRule findUniqueOrThrow
 */
export type ModerationRuleFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModerationRule
   */
  select?: Prisma.ModerationRuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModerationRule
   */
  omit?: Prisma.ModerationRuleOmit<ExtArgs> | null
  /**
   * Filter, which ModerationRule to fetch.
   */
  where: Prisma.ModerationRuleWhereUniqueInput
}

/**
 * ModerationRule findFirst
 */
export type ModerationRuleFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModerationRule
   */
  select?: Prisma.ModerationRuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModerationRule
   */
  omit?: Prisma.ModerationRuleOmit<ExtArgs> | null
  /**
   * Filter, which ModerationRule to fetch.
   */
  where?: Prisma.ModerationRuleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ModerationRules to fetch.
   */
  orderBy?: Prisma.ModerationRuleOrderByWithRelationInput | Prisma.ModerationRuleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ModerationRules.
   */
  cursor?: Prisma.ModerationRuleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ModerationRules from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ModerationRules.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ModerationRules.
   */
  distinct?: Prisma.ModerationRuleScalarFieldEnum | Prisma.ModerationRuleScalarFieldEnum[]
}

/**
 * ModerationRule findFirstOrThrow
 */
export type ModerationRuleFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModerationRule
   */
  select?: Prisma.ModerationRuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModerationRule
   */
  omit?: Prisma.ModerationRuleOmit<ExtArgs> | null
  /**
   * Filter, which ModerationRule to fetch.
   */
  where?: Prisma.ModerationRuleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ModerationRules to fetch.
   */
  orderBy?: Prisma.ModerationRuleOrderByWithRelationInput | Prisma.ModerationRuleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ModerationRules.
   */
  cursor?: Prisma.ModerationRuleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ModerationRules from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ModerationRules.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ModerationRules.
   */
  distinct?: Prisma.ModerationRuleScalarFieldEnum | Prisma.ModerationRuleScalarFieldEnum[]
}

/**
 * ModerationRule findMany
 */
export type ModerationRuleFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModerationRule
   */
  select?: Prisma.ModerationRuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModerationRule
   */
  omit?: Prisma.ModerationRuleOmit<ExtArgs> | null
  /**
   * Filter, which ModerationRules to fetch.
   */
  where?: Prisma.ModerationRuleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ModerationRules to fetch.
   */
  orderBy?: Prisma.ModerationRuleOrderByWithRelationInput | Prisma.ModerationRuleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ModerationRules.
   */
  cursor?: Prisma.ModerationRuleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ModerationRules from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ModerationRules.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ModerationRules.
   */
  distinct?: Prisma.ModerationRuleScalarFieldEnum | Prisma.ModerationRuleScalarFieldEnum[]
}

/**
 * ModerationRule create
 */
export type ModerationRuleCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModerationRule
   */
  select?: Prisma.ModerationRuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModerationRule
   */
  omit?: Prisma.ModerationRuleOmit<ExtArgs> | null
  /**
   * The data needed to create a ModerationRule.
   */
  data: Prisma.XOR<Prisma.ModerationRuleCreateInput, Prisma.ModerationRuleUncheckedCreateInput>
}

/**
 * ModerationRule createMany
 */
export type ModerationRuleCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ModerationRules.
   */
  data: Prisma.ModerationRuleCreateManyInput | Prisma.ModerationRuleCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ModerationRule update
 */
export type ModerationRuleUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModerationRule
   */
  select?: Prisma.ModerationRuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModerationRule
   */
  omit?: Prisma.ModerationRuleOmit<ExtArgs> | null
  /**
   * The data needed to update a ModerationRule.
   */
  data: Prisma.XOR<Prisma.ModerationRuleUpdateInput, Prisma.ModerationRuleUncheckedUpdateInput>
  /**
   * Choose, which ModerationRule to update.
   */
  where: Prisma.ModerationRuleWhereUniqueInput
}

/**
 * ModerationRule updateMany
 */
export type ModerationRuleUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ModerationRules.
   */
  data: Prisma.XOR<Prisma.ModerationRuleUpdateManyMutationInput, Prisma.ModerationRuleUncheckedUpdateManyInput>
  /**
   * Filter which ModerationRules to update
   */
  where?: Prisma.ModerationRuleWhereInput
  /**
   * Limit how many ModerationRules to update.
   */
  limit?: number
}

/**
 * ModerationRule upsert
 */
export type ModerationRuleUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModerationRule
   */
  select?: Prisma.ModerationRuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModerationRule
   */
  omit?: Prisma.ModerationRuleOmit<ExtArgs> | null
  /**
   * The filter to search for the ModerationRule to update in case it exists.
   */
  where: Prisma.ModerationRuleWhereUniqueInput
  /**
   * In case the ModerationRule found by the `where` argument doesn't exist, create a new ModerationRule with this data.
   */
  create: Prisma.XOR<Prisma.ModerationRuleCreateInput, Prisma.ModerationRuleUncheckedCreateInput>
  /**
   * In case the ModerationRule was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ModerationRuleUpdateInput, Prisma.ModerationRuleUncheckedUpdateInput>
}

/**
 * ModerationRule delete
 */
export type ModerationRuleDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModerationRule
   */
  select?: Prisma.ModerationRuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModerationRule
   */
  omit?: Prisma.ModerationRuleOmit<ExtArgs> | null
  /**
   * Filter which ModerationRule to delete.
   */
  where: Prisma.ModerationRuleWhereUniqueInput
}

/**
 * ModerationRule deleteMany
 */
export type ModerationRuleDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ModerationRules to delete
   */
  where?: Prisma.ModerationRuleWhereInput
  /**
   * Limit how many ModerationRules to delete.
   */
  limit?: number
}

/**
 * ModerationRule without action
 */
export type ModerationRuleDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModerationRule
   */
  select?: Prisma.ModerationRuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModerationRule
   */
  omit?: Prisma.ModerationRuleOmit<ExtArgs> | null
}
