
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ProfileVideo` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ProfileVideo
 * 
 */
export type ProfileVideoModel = runtime.Types.Result.DefaultSelection<Prisma.$ProfileVideoPayload>

export type AggregateProfileVideo = {
  _count: ProfileVideoCountAggregateOutputType | null
  _avg: ProfileVideoAvgAggregateOutputType | null
  _sum: ProfileVideoSumAggregateOutputType | null
  _min: ProfileVideoMinAggregateOutputType | null
  _max: ProfileVideoMaxAggregateOutputType | null
}

export type ProfileVideoAvgAggregateOutputType = {
  durationSec: number | null
  position: number | null
}

export type ProfileVideoSumAggregateOutputType = {
  durationSec: number | null
  position: number | null
}

export type ProfileVideoMinAggregateOutputType = {
  id: string | null
  userId: string | null
  url: string | null
  durationSec: number | null
  position: number | null
  moderation: $Enums.ModerationStatus | null
  createdAt: Date | null
}

export type ProfileVideoMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  url: string | null
  durationSec: number | null
  position: number | null
  moderation: $Enums.ModerationStatus | null
  createdAt: Date | null
}

export type ProfileVideoCountAggregateOutputType = {
  id: number
  userId: number
  url: number
  durationSec: number
  position: number
  moderation: number
  createdAt: number
  _all: number
}


export type ProfileVideoAvgAggregateInputType = {
  durationSec?: true
  position?: true
}

export type ProfileVideoSumAggregateInputType = {
  durationSec?: true
  position?: true
}

export type ProfileVideoMinAggregateInputType = {
  id?: true
  userId?: true
  url?: true
  durationSec?: true
  position?: true
  moderation?: true
  createdAt?: true
}

export type ProfileVideoMaxAggregateInputType = {
  id?: true
  userId?: true
  url?: true
  durationSec?: true
  position?: true
  moderation?: true
  createdAt?: true
}

export type ProfileVideoCountAggregateInputType = {
  id?: true
  userId?: true
  url?: true
  durationSec?: true
  position?: true
  moderation?: true
  createdAt?: true
  _all?: true
}

export type ProfileVideoAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProfileVideo to aggregate.
   */
  where?: Prisma.ProfileVideoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProfileVideos to fetch.
   */
  orderBy?: Prisma.ProfileVideoOrderByWithRelationInput | Prisma.ProfileVideoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ProfileVideoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProfileVideos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProfileVideos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ProfileVideos
  **/
  _count?: true | ProfileVideoCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ProfileVideoAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ProfileVideoSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProfileVideoMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProfileVideoMaxAggregateInputType
}

export type GetProfileVideoAggregateType<T extends ProfileVideoAggregateArgs> = {
      [P in keyof T & keyof AggregateProfileVideo]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProfileVideo[P]>
    : Prisma.GetScalarType<T[P], AggregateProfileVideo[P]>
}




export type ProfileVideoGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProfileVideoWhereInput
  orderBy?: Prisma.ProfileVideoOrderByWithAggregationInput | Prisma.ProfileVideoOrderByWithAggregationInput[]
  by: Prisma.ProfileVideoScalarFieldEnum[] | Prisma.ProfileVideoScalarFieldEnum
  having?: Prisma.ProfileVideoScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProfileVideoCountAggregateInputType | true
  _avg?: ProfileVideoAvgAggregateInputType
  _sum?: ProfileVideoSumAggregateInputType
  _min?: ProfileVideoMinAggregateInputType
  _max?: ProfileVideoMaxAggregateInputType
}

export type ProfileVideoGroupByOutputType = {
  id: string
  userId: string
  url: string
  durationSec: number
  position: number
  moderation: $Enums.ModerationStatus
  createdAt: Date
  _count: ProfileVideoCountAggregateOutputType | null
  _avg: ProfileVideoAvgAggregateOutputType | null
  _sum: ProfileVideoSumAggregateOutputType | null
  _min: ProfileVideoMinAggregateOutputType | null
  _max: ProfileVideoMaxAggregateOutputType | null
}

export type GetProfileVideoGroupByPayload<T extends ProfileVideoGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProfileVideoGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProfileVideoGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProfileVideoGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProfileVideoGroupByOutputType[P]>
      }
    >
  >



export type ProfileVideoWhereInput = {
  AND?: Prisma.ProfileVideoWhereInput | Prisma.ProfileVideoWhereInput[]
  OR?: Prisma.ProfileVideoWhereInput[]
  NOT?: Prisma.ProfileVideoWhereInput | Prisma.ProfileVideoWhereInput[]
  id?: Prisma.StringFilter<"ProfileVideo"> | string
  userId?: Prisma.StringFilter<"ProfileVideo"> | string
  url?: Prisma.StringFilter<"ProfileVideo"> | string
  durationSec?: Prisma.IntFilter<"ProfileVideo"> | number
  position?: Prisma.IntFilter<"ProfileVideo"> | number
  moderation?: Prisma.EnumModerationStatusFilter<"ProfileVideo"> | $Enums.ModerationStatus
  createdAt?: Prisma.DateTimeFilter<"ProfileVideo"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type ProfileVideoOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  url?: Prisma.SortOrder
  durationSec?: Prisma.SortOrder
  position?: Prisma.SortOrder
  moderation?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  _relevance?: Prisma.ProfileVideoOrderByRelevanceInput
}

export type ProfileVideoWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ProfileVideoWhereInput | Prisma.ProfileVideoWhereInput[]
  OR?: Prisma.ProfileVideoWhereInput[]
  NOT?: Prisma.ProfileVideoWhereInput | Prisma.ProfileVideoWhereInput[]
  userId?: Prisma.StringFilter<"ProfileVideo"> | string
  url?: Prisma.StringFilter<"ProfileVideo"> | string
  durationSec?: Prisma.IntFilter<"ProfileVideo"> | number
  position?: Prisma.IntFilter<"ProfileVideo"> | number
  moderation?: Prisma.EnumModerationStatusFilter<"ProfileVideo"> | $Enums.ModerationStatus
  createdAt?: Prisma.DateTimeFilter<"ProfileVideo"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type ProfileVideoOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  url?: Prisma.SortOrder
  durationSec?: Prisma.SortOrder
  position?: Prisma.SortOrder
  moderation?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.ProfileVideoCountOrderByAggregateInput
  _avg?: Prisma.ProfileVideoAvgOrderByAggregateInput
  _max?: Prisma.ProfileVideoMaxOrderByAggregateInput
  _min?: Prisma.ProfileVideoMinOrderByAggregateInput
  _sum?: Prisma.ProfileVideoSumOrderByAggregateInput
}

export type ProfileVideoScalarWhereWithAggregatesInput = {
  AND?: Prisma.ProfileVideoScalarWhereWithAggregatesInput | Prisma.ProfileVideoScalarWhereWithAggregatesInput[]
  OR?: Prisma.ProfileVideoScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ProfileVideoScalarWhereWithAggregatesInput | Prisma.ProfileVideoScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ProfileVideo"> | string
  userId?: Prisma.StringWithAggregatesFilter<"ProfileVideo"> | string
  url?: Prisma.StringWithAggregatesFilter<"ProfileVideo"> | string
  durationSec?: Prisma.IntWithAggregatesFilter<"ProfileVideo"> | number
  position?: Prisma.IntWithAggregatesFilter<"ProfileVideo"> | number
  moderation?: Prisma.EnumModerationStatusWithAggregatesFilter<"ProfileVideo"> | $Enums.ModerationStatus
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ProfileVideo"> | Date | string
}

export type ProfileVideoCreateInput = {
  id?: string
  url: string
  durationSec: number
  position?: number
  moderation?: $Enums.ModerationStatus
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutProfileVideosInput
}

export type ProfileVideoUncheckedCreateInput = {
  id?: string
  userId: string
  url: string
  durationSec: number
  position?: number
  moderation?: $Enums.ModerationStatus
  createdAt?: Date | string
}

export type ProfileVideoUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  durationSec?: Prisma.IntFieldUpdateOperationsInput | number
  position?: Prisma.IntFieldUpdateOperationsInput | number
  moderation?: Prisma.EnumModerationStatusFieldUpdateOperationsInput | $Enums.ModerationStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutProfileVideosNestedInput
}

export type ProfileVideoUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  durationSec?: Prisma.IntFieldUpdateOperationsInput | number
  position?: Prisma.IntFieldUpdateOperationsInput | number
  moderation?: Prisma.EnumModerationStatusFieldUpdateOperationsInput | $Enums.ModerationStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProfileVideoCreateManyInput = {
  id?: string
  userId: string
  url: string
  durationSec: number
  position?: number
  moderation?: $Enums.ModerationStatus
  createdAt?: Date | string
}

export type ProfileVideoUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  durationSec?: Prisma.IntFieldUpdateOperationsInput | number
  position?: Prisma.IntFieldUpdateOperationsInput | number
  moderation?: Prisma.EnumModerationStatusFieldUpdateOperationsInput | $Enums.ModerationStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProfileVideoUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  durationSec?: Prisma.IntFieldUpdateOperationsInput | number
  position?: Prisma.IntFieldUpdateOperationsInput | number
  moderation?: Prisma.EnumModerationStatusFieldUpdateOperationsInput | $Enums.ModerationStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProfileVideoListRelationFilter = {
  every?: Prisma.ProfileVideoWhereInput
  some?: Prisma.ProfileVideoWhereInput
  none?: Prisma.ProfileVideoWhereInput
}

export type ProfileVideoOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ProfileVideoOrderByRelevanceInput = {
  fields: Prisma.ProfileVideoOrderByRelevanceFieldEnum | Prisma.ProfileVideoOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type ProfileVideoCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  url?: Prisma.SortOrder
  durationSec?: Prisma.SortOrder
  position?: Prisma.SortOrder
  moderation?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ProfileVideoAvgOrderByAggregateInput = {
  durationSec?: Prisma.SortOrder
  position?: Prisma.SortOrder
}

export type ProfileVideoMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  url?: Prisma.SortOrder
  durationSec?: Prisma.SortOrder
  position?: Prisma.SortOrder
  moderation?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ProfileVideoMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  url?: Prisma.SortOrder
  durationSec?: Prisma.SortOrder
  position?: Prisma.SortOrder
  moderation?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type ProfileVideoSumOrderByAggregateInput = {
  durationSec?: Prisma.SortOrder
  position?: Prisma.SortOrder
}

export type ProfileVideoCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ProfileVideoCreateWithoutUserInput, Prisma.ProfileVideoUncheckedCreateWithoutUserInput> | Prisma.ProfileVideoCreateWithoutUserInput[] | Prisma.ProfileVideoUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ProfileVideoCreateOrConnectWithoutUserInput | Prisma.ProfileVideoCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ProfileVideoCreateManyUserInputEnvelope
  connect?: Prisma.ProfileVideoWhereUniqueInput | Prisma.ProfileVideoWhereUniqueInput[]
}

export type ProfileVideoUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ProfileVideoCreateWithoutUserInput, Prisma.ProfileVideoUncheckedCreateWithoutUserInput> | Prisma.ProfileVideoCreateWithoutUserInput[] | Prisma.ProfileVideoUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ProfileVideoCreateOrConnectWithoutUserInput | Prisma.ProfileVideoCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ProfileVideoCreateManyUserInputEnvelope
  connect?: Prisma.ProfileVideoWhereUniqueInput | Prisma.ProfileVideoWhereUniqueInput[]
}

export type ProfileVideoUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ProfileVideoCreateWithoutUserInput, Prisma.ProfileVideoUncheckedCreateWithoutUserInput> | Prisma.ProfileVideoCreateWithoutUserInput[] | Prisma.ProfileVideoUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ProfileVideoCreateOrConnectWithoutUserInput | Prisma.ProfileVideoCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ProfileVideoUpsertWithWhereUniqueWithoutUserInput | Prisma.ProfileVideoUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ProfileVideoCreateManyUserInputEnvelope
  set?: Prisma.ProfileVideoWhereUniqueInput | Prisma.ProfileVideoWhereUniqueInput[]
  disconnect?: Prisma.ProfileVideoWhereUniqueInput | Prisma.ProfileVideoWhereUniqueInput[]
  delete?: Prisma.ProfileVideoWhereUniqueInput | Prisma.ProfileVideoWhereUniqueInput[]
  connect?: Prisma.ProfileVideoWhereUniqueInput | Prisma.ProfileVideoWhereUniqueInput[]
  update?: Prisma.ProfileVideoUpdateWithWhereUniqueWithoutUserInput | Prisma.ProfileVideoUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ProfileVideoUpdateManyWithWhereWithoutUserInput | Prisma.ProfileVideoUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ProfileVideoScalarWhereInput | Prisma.ProfileVideoScalarWhereInput[]
}

export type ProfileVideoUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ProfileVideoCreateWithoutUserInput, Prisma.ProfileVideoUncheckedCreateWithoutUserInput> | Prisma.ProfileVideoCreateWithoutUserInput[] | Prisma.ProfileVideoUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ProfileVideoCreateOrConnectWithoutUserInput | Prisma.ProfileVideoCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ProfileVideoUpsertWithWhereUniqueWithoutUserInput | Prisma.ProfileVideoUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ProfileVideoCreateManyUserInputEnvelope
  set?: Prisma.ProfileVideoWhereUniqueInput | Prisma.ProfileVideoWhereUniqueInput[]
  disconnect?: Prisma.ProfileVideoWhereUniqueInput | Prisma.ProfileVideoWhereUniqueInput[]
  delete?: Prisma.ProfileVideoWhereUniqueInput | Prisma.ProfileVideoWhereUniqueInput[]
  connect?: Prisma.ProfileVideoWhereUniqueInput | Prisma.ProfileVideoWhereUniqueInput[]
  update?: Prisma.ProfileVideoUpdateWithWhereUniqueWithoutUserInput | Prisma.ProfileVideoUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ProfileVideoUpdateManyWithWhereWithoutUserInput | Prisma.ProfileVideoUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ProfileVideoScalarWhereInput | Prisma.ProfileVideoScalarWhereInput[]
}

export type ProfileVideoCreateWithoutUserInput = {
  id?: string
  url: string
  durationSec: number
  position?: number
  moderation?: $Enums.ModerationStatus
  createdAt?: Date | string
}

export type ProfileVideoUncheckedCreateWithoutUserInput = {
  id?: string
  url: string
  durationSec: number
  position?: number
  moderation?: $Enums.ModerationStatus
  createdAt?: Date | string
}

export type ProfileVideoCreateOrConnectWithoutUserInput = {
  where: Prisma.ProfileVideoWhereUniqueInput
  create: Prisma.XOR<Prisma.ProfileVideoCreateWithoutUserInput, Prisma.ProfileVideoUncheckedCreateWithoutUserInput>
}

export type ProfileVideoCreateManyUserInputEnvelope = {
  data: Prisma.ProfileVideoCreateManyUserInput | Prisma.ProfileVideoCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type ProfileVideoUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.ProfileVideoWhereUniqueInput
  update: Prisma.XOR<Prisma.ProfileVideoUpdateWithoutUserInput, Prisma.ProfileVideoUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.ProfileVideoCreateWithoutUserInput, Prisma.ProfileVideoUncheckedCreateWithoutUserInput>
}

export type ProfileVideoUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.ProfileVideoWhereUniqueInput
  data: Prisma.XOR<Prisma.ProfileVideoUpdateWithoutUserInput, Prisma.ProfileVideoUncheckedUpdateWithoutUserInput>
}

export type ProfileVideoUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.ProfileVideoScalarWhereInput
  data: Prisma.XOR<Prisma.ProfileVideoUpdateManyMutationInput, Prisma.ProfileVideoUncheckedUpdateManyWithoutUserInput>
}

export type ProfileVideoScalarWhereInput = {
  AND?: Prisma.ProfileVideoScalarWhereInput | Prisma.ProfileVideoScalarWhereInput[]
  OR?: Prisma.ProfileVideoScalarWhereInput[]
  NOT?: Prisma.ProfileVideoScalarWhereInput | Prisma.ProfileVideoScalarWhereInput[]
  id?: Prisma.StringFilter<"ProfileVideo"> | string
  userId?: Prisma.StringFilter<"ProfileVideo"> | string
  url?: Prisma.StringFilter<"ProfileVideo"> | string
  durationSec?: Prisma.IntFilter<"ProfileVideo"> | number
  position?: Prisma.IntFilter<"ProfileVideo"> | number
  moderation?: Prisma.EnumModerationStatusFilter<"ProfileVideo"> | $Enums.ModerationStatus
  createdAt?: Prisma.DateTimeFilter<"ProfileVideo"> | Date | string
}

export type ProfileVideoCreateManyUserInput = {
  id?: string
  url: string
  durationSec: number
  position?: number
  moderation?: $Enums.ModerationStatus
  createdAt?: Date | string
}

export type ProfileVideoUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  durationSec?: Prisma.IntFieldUpdateOperationsInput | number
  position?: Prisma.IntFieldUpdateOperationsInput | number
  moderation?: Prisma.EnumModerationStatusFieldUpdateOperationsInput | $Enums.ModerationStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProfileVideoUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  durationSec?: Prisma.IntFieldUpdateOperationsInput | number
  position?: Prisma.IntFieldUpdateOperationsInput | number
  moderation?: Prisma.EnumModerationStatusFieldUpdateOperationsInput | $Enums.ModerationStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProfileVideoUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  url?: Prisma.StringFieldUpdateOperationsInput | string
  durationSec?: Prisma.IntFieldUpdateOperationsInput | number
  position?: Prisma.IntFieldUpdateOperationsInput | number
  moderation?: Prisma.EnumModerationStatusFieldUpdateOperationsInput | $Enums.ModerationStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ProfileVideoSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  url?: boolean
  durationSec?: boolean
  position?: boolean
  moderation?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["profileVideo"]>



export type ProfileVideoSelectScalar = {
  id?: boolean
  userId?: boolean
  url?: boolean
  durationSec?: boolean
  position?: boolean
  moderation?: boolean
  createdAt?: boolean
}

export type ProfileVideoOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "url" | "durationSec" | "position" | "moderation" | "createdAt", ExtArgs["result"]["profileVideo"]>
export type ProfileVideoInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $ProfileVideoPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ProfileVideo"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    url: string
    durationSec: number
    position: number
    moderation: $Enums.ModerationStatus
    createdAt: Date
  }, ExtArgs["result"]["profileVideo"]>
  composites: {}
}

export type ProfileVideoGetPayload<S extends boolean | null | undefined | ProfileVideoDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProfileVideoPayload, S>

export type ProfileVideoCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ProfileVideoFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProfileVideoCountAggregateInputType | true
  }

export interface ProfileVideoDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ProfileVideo'], meta: { name: 'ProfileVideo' } }
  /**
   * Find zero or one ProfileVideo that matches the filter.
   * @param {ProfileVideoFindUniqueArgs} args - Arguments to find a ProfileVideo
   * @example
   * // Get one ProfileVideo
   * const profileVideo = await prisma.profileVideo.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ProfileVideoFindUniqueArgs>(args: Prisma.SelectSubset<T, ProfileVideoFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProfileVideoClient<runtime.Types.Result.GetResult<Prisma.$ProfileVideoPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ProfileVideo that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ProfileVideoFindUniqueOrThrowArgs} args - Arguments to find a ProfileVideo
   * @example
   * // Get one ProfileVideo
   * const profileVideo = await prisma.profileVideo.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ProfileVideoFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProfileVideoFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProfileVideoClient<runtime.Types.Result.GetResult<Prisma.$ProfileVideoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProfileVideo that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfileVideoFindFirstArgs} args - Arguments to find a ProfileVideo
   * @example
   * // Get one ProfileVideo
   * const profileVideo = await prisma.profileVideo.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ProfileVideoFindFirstArgs>(args?: Prisma.SelectSubset<T, ProfileVideoFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProfileVideoClient<runtime.Types.Result.GetResult<Prisma.$ProfileVideoPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProfileVideo that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfileVideoFindFirstOrThrowArgs} args - Arguments to find a ProfileVideo
   * @example
   * // Get one ProfileVideo
   * const profileVideo = await prisma.profileVideo.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ProfileVideoFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProfileVideoFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProfileVideoClient<runtime.Types.Result.GetResult<Prisma.$ProfileVideoPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ProfileVideos that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfileVideoFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ProfileVideos
   * const profileVideos = await prisma.profileVideo.findMany()
   * 
   * // Get first 10 ProfileVideos
   * const profileVideos = await prisma.profileVideo.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const profileVideoWithIdOnly = await prisma.profileVideo.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ProfileVideoFindManyArgs>(args?: Prisma.SelectSubset<T, ProfileVideoFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProfileVideoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ProfileVideo.
   * @param {ProfileVideoCreateArgs} args - Arguments to create a ProfileVideo.
   * @example
   * // Create one ProfileVideo
   * const ProfileVideo = await prisma.profileVideo.create({
   *   data: {
   *     // ... data to create a ProfileVideo
   *   }
   * })
   * 
   */
  create<T extends ProfileVideoCreateArgs>(args: Prisma.SelectSubset<T, ProfileVideoCreateArgs<ExtArgs>>): Prisma.Prisma__ProfileVideoClient<runtime.Types.Result.GetResult<Prisma.$ProfileVideoPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ProfileVideos.
   * @param {ProfileVideoCreateManyArgs} args - Arguments to create many ProfileVideos.
   * @example
   * // Create many ProfileVideos
   * const profileVideo = await prisma.profileVideo.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ProfileVideoCreateManyArgs>(args?: Prisma.SelectSubset<T, ProfileVideoCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a ProfileVideo.
   * @param {ProfileVideoDeleteArgs} args - Arguments to delete one ProfileVideo.
   * @example
   * // Delete one ProfileVideo
   * const ProfileVideo = await prisma.profileVideo.delete({
   *   where: {
   *     // ... filter to delete one ProfileVideo
   *   }
   * })
   * 
   */
  delete<T extends ProfileVideoDeleteArgs>(args: Prisma.SelectSubset<T, ProfileVideoDeleteArgs<ExtArgs>>): Prisma.Prisma__ProfileVideoClient<runtime.Types.Result.GetResult<Prisma.$ProfileVideoPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ProfileVideo.
   * @param {ProfileVideoUpdateArgs} args - Arguments to update one ProfileVideo.
   * @example
   * // Update one ProfileVideo
   * const profileVideo = await prisma.profileVideo.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ProfileVideoUpdateArgs>(args: Prisma.SelectSubset<T, ProfileVideoUpdateArgs<ExtArgs>>): Prisma.Prisma__ProfileVideoClient<runtime.Types.Result.GetResult<Prisma.$ProfileVideoPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ProfileVideos.
   * @param {ProfileVideoDeleteManyArgs} args - Arguments to filter ProfileVideos to delete.
   * @example
   * // Delete a few ProfileVideos
   * const { count } = await prisma.profileVideo.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ProfileVideoDeleteManyArgs>(args?: Prisma.SelectSubset<T, ProfileVideoDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProfileVideos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfileVideoUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ProfileVideos
   * const profileVideo = await prisma.profileVideo.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ProfileVideoUpdateManyArgs>(args: Prisma.SelectSubset<T, ProfileVideoUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one ProfileVideo.
   * @param {ProfileVideoUpsertArgs} args - Arguments to update or create a ProfileVideo.
   * @example
   * // Update or create a ProfileVideo
   * const profileVideo = await prisma.profileVideo.upsert({
   *   create: {
   *     // ... data to create a ProfileVideo
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ProfileVideo we want to update
   *   }
   * })
   */
  upsert<T extends ProfileVideoUpsertArgs>(args: Prisma.SelectSubset<T, ProfileVideoUpsertArgs<ExtArgs>>): Prisma.Prisma__ProfileVideoClient<runtime.Types.Result.GetResult<Prisma.$ProfileVideoPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ProfileVideos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfileVideoCountArgs} args - Arguments to filter ProfileVideos to count.
   * @example
   * // Count the number of ProfileVideos
   * const count = await prisma.profileVideo.count({
   *   where: {
   *     // ... the filter for the ProfileVideos we want to count
   *   }
   * })
  **/
  count<T extends ProfileVideoCountArgs>(
    args?: Prisma.Subset<T, ProfileVideoCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProfileVideoCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ProfileVideo.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfileVideoAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProfileVideoAggregateArgs>(args: Prisma.Subset<T, ProfileVideoAggregateArgs>): Prisma.PrismaPromise<GetProfileVideoAggregateType<T>>

  /**
   * Group by ProfileVideo.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfileVideoGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ProfileVideoGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ProfileVideoGroupByArgs['orderBy'] }
      : { orderBy?: ProfileVideoGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ProfileVideoGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProfileVideoGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ProfileVideo model
 */
readonly fields: ProfileVideoFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ProfileVideo.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProfileVideoClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ProfileVideo model
 */
export interface ProfileVideoFieldRefs {
  readonly id: Prisma.FieldRef<"ProfileVideo", 'String'>
  readonly userId: Prisma.FieldRef<"ProfileVideo", 'String'>
  readonly url: Prisma.FieldRef<"ProfileVideo", 'String'>
  readonly durationSec: Prisma.FieldRef<"ProfileVideo", 'Int'>
  readonly position: Prisma.FieldRef<"ProfileVideo", 'Int'>
  readonly moderation: Prisma.FieldRef<"ProfileVideo", 'ModerationStatus'>
  readonly createdAt: Prisma.FieldRef<"ProfileVideo", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ProfileVideo findUnique
 */
export type ProfileVideoFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProfileVideo
   */
  select?: Prisma.ProfileVideoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProfileVideo
   */
  omit?: Prisma.ProfileVideoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileVideoInclude<ExtArgs> | null
  /**
   * Filter, which ProfileVideo to fetch.
   */
  where: Prisma.ProfileVideoWhereUniqueInput
}

/**
 * ProfileVideo findUniqueOrThrow
 */
export type ProfileVideoFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProfileVideo
   */
  select?: Prisma.ProfileVideoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProfileVideo
   */
  omit?: Prisma.ProfileVideoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileVideoInclude<ExtArgs> | null
  /**
   * Filter, which ProfileVideo to fetch.
   */
  where: Prisma.ProfileVideoWhereUniqueInput
}

/**
 * ProfileVideo findFirst
 */
export type ProfileVideoFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProfileVideo
   */
  select?: Prisma.ProfileVideoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProfileVideo
   */
  omit?: Prisma.ProfileVideoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileVideoInclude<ExtArgs> | null
  /**
   * Filter, which ProfileVideo to fetch.
   */
  where?: Prisma.ProfileVideoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProfileVideos to fetch.
   */
  orderBy?: Prisma.ProfileVideoOrderByWithRelationInput | Prisma.ProfileVideoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProfileVideos.
   */
  cursor?: Prisma.ProfileVideoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProfileVideos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProfileVideos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProfileVideos.
   */
  distinct?: Prisma.ProfileVideoScalarFieldEnum | Prisma.ProfileVideoScalarFieldEnum[]
}

/**
 * ProfileVideo findFirstOrThrow
 */
export type ProfileVideoFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProfileVideo
   */
  select?: Prisma.ProfileVideoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProfileVideo
   */
  omit?: Prisma.ProfileVideoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileVideoInclude<ExtArgs> | null
  /**
   * Filter, which ProfileVideo to fetch.
   */
  where?: Prisma.ProfileVideoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProfileVideos to fetch.
   */
  orderBy?: Prisma.ProfileVideoOrderByWithRelationInput | Prisma.ProfileVideoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProfileVideos.
   */
  cursor?: Prisma.ProfileVideoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProfileVideos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProfileVideos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProfileVideos.
   */
  distinct?: Prisma.ProfileVideoScalarFieldEnum | Prisma.ProfileVideoScalarFieldEnum[]
}

/**
 * ProfileVideo findMany
 */
export type ProfileVideoFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProfileVideo
   */
  select?: Prisma.ProfileVideoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProfileVideo
   */
  omit?: Prisma.ProfileVideoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileVideoInclude<ExtArgs> | null
  /**
   * Filter, which ProfileVideos to fetch.
   */
  where?: Prisma.ProfileVideoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProfileVideos to fetch.
   */
  orderBy?: Prisma.ProfileVideoOrderByWithRelationInput | Prisma.ProfileVideoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ProfileVideos.
   */
  cursor?: Prisma.ProfileVideoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProfileVideos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProfileVideos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProfileVideos.
   */
  distinct?: Prisma.ProfileVideoScalarFieldEnum | Prisma.ProfileVideoScalarFieldEnum[]
}

/**
 * ProfileVideo create
 */
export type ProfileVideoCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProfileVideo
   */
  select?: Prisma.ProfileVideoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProfileVideo
   */
  omit?: Prisma.ProfileVideoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileVideoInclude<ExtArgs> | null
  /**
   * The data needed to create a ProfileVideo.
   */
  data: Prisma.XOR<Prisma.ProfileVideoCreateInput, Prisma.ProfileVideoUncheckedCreateInput>
}

/**
 * ProfileVideo createMany
 */
export type ProfileVideoCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ProfileVideos.
   */
  data: Prisma.ProfileVideoCreateManyInput | Prisma.ProfileVideoCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ProfileVideo update
 */
export type ProfileVideoUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProfileVideo
   */
  select?: Prisma.ProfileVideoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProfileVideo
   */
  omit?: Prisma.ProfileVideoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileVideoInclude<ExtArgs> | null
  /**
   * The data needed to update a ProfileVideo.
   */
  data: Prisma.XOR<Prisma.ProfileVideoUpdateInput, Prisma.ProfileVideoUncheckedUpdateInput>
  /**
   * Choose, which ProfileVideo to update.
   */
  where: Prisma.ProfileVideoWhereUniqueInput
}

/**
 * ProfileVideo updateMany
 */
export type ProfileVideoUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ProfileVideos.
   */
  data: Prisma.XOR<Prisma.ProfileVideoUpdateManyMutationInput, Prisma.ProfileVideoUncheckedUpdateManyInput>
  /**
   * Filter which ProfileVideos to update
   */
  where?: Prisma.ProfileVideoWhereInput
  /**
   * Limit how many ProfileVideos to update.
   */
  limit?: number
}

/**
 * ProfileVideo upsert
 */
export type ProfileVideoUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProfileVideo
   */
  select?: Prisma.ProfileVideoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProfileVideo
   */
  omit?: Prisma.ProfileVideoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileVideoInclude<ExtArgs> | null
  /**
   * The filter to search for the ProfileVideo to update in case it exists.
   */
  where: Prisma.ProfileVideoWhereUniqueInput
  /**
   * In case the ProfileVideo found by the `where` argument doesn't exist, create a new ProfileVideo with this data.
   */
  create: Prisma.XOR<Prisma.ProfileVideoCreateInput, Prisma.ProfileVideoUncheckedCreateInput>
  /**
   * In case the ProfileVideo was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ProfileVideoUpdateInput, Prisma.ProfileVideoUncheckedUpdateInput>
}

/**
 * ProfileVideo delete
 */
export type ProfileVideoDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProfileVideo
   */
  select?: Prisma.ProfileVideoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProfileVideo
   */
  omit?: Prisma.ProfileVideoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileVideoInclude<ExtArgs> | null
  /**
   * Filter which ProfileVideo to delete.
   */
  where: Prisma.ProfileVideoWhereUniqueInput
}

/**
 * ProfileVideo deleteMany
 */
export type ProfileVideoDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProfileVideos to delete
   */
  where?: Prisma.ProfileVideoWhereInput
  /**
   * Limit how many ProfileVideos to delete.
   */
  limit?: number
}

/**
 * ProfileVideo without action
 */
export type ProfileVideoDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProfileVideo
   */
  select?: Prisma.ProfileVideoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProfileVideo
   */
  omit?: Prisma.ProfileVideoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileVideoInclude<ExtArgs> | null
}
