
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Reel` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Reel
 * 
 */
export type ReelModel = runtime.Types.Result.DefaultSelection<Prisma.$ReelPayload>

export type AggregateReel = {
  _count: ReelCountAggregateOutputType | null
  _avg: ReelAvgAggregateOutputType | null
  _sum: ReelSumAggregateOutputType | null
  _min: ReelMinAggregateOutputType | null
  _max: ReelMaxAggregateOutputType | null
}

export type ReelAvgAggregateOutputType = {
  viewsCount: number | null
}

export type ReelSumAggregateOutputType = {
  viewsCount: number | null
}

export type ReelMinAggregateOutputType = {
  id: string | null
  userId: string | null
  mediaUrl: string | null
  mediaType: $Enums.MediaType | null
  thumbnailUrl: string | null
  caption: string | null
  status: $Enums.ReelStatus | null
  moderation: $Enums.ModerationStatus | null
  viewsCount: number | null
  createdAt: Date | null
  expiresAt: Date | null
}

export type ReelMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  mediaUrl: string | null
  mediaType: $Enums.MediaType | null
  thumbnailUrl: string | null
  caption: string | null
  status: $Enums.ReelStatus | null
  moderation: $Enums.ModerationStatus | null
  viewsCount: number | null
  createdAt: Date | null
  expiresAt: Date | null
}

export type ReelCountAggregateOutputType = {
  id: number
  userId: number
  mediaUrl: number
  mediaType: number
  thumbnailUrl: number
  caption: number
  status: number
  moderation: number
  viewsCount: number
  createdAt: number
  expiresAt: number
  _all: number
}


export type ReelAvgAggregateInputType = {
  viewsCount?: true
}

export type ReelSumAggregateInputType = {
  viewsCount?: true
}

export type ReelMinAggregateInputType = {
  id?: true
  userId?: true
  mediaUrl?: true
  mediaType?: true
  thumbnailUrl?: true
  caption?: true
  status?: true
  moderation?: true
  viewsCount?: true
  createdAt?: true
  expiresAt?: true
}

export type ReelMaxAggregateInputType = {
  id?: true
  userId?: true
  mediaUrl?: true
  mediaType?: true
  thumbnailUrl?: true
  caption?: true
  status?: true
  moderation?: true
  viewsCount?: true
  createdAt?: true
  expiresAt?: true
}

export type ReelCountAggregateInputType = {
  id?: true
  userId?: true
  mediaUrl?: true
  mediaType?: true
  thumbnailUrl?: true
  caption?: true
  status?: true
  moderation?: true
  viewsCount?: true
  createdAt?: true
  expiresAt?: true
  _all?: true
}

export type ReelAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Reel to aggregate.
   */
  where?: Prisma.ReelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Reels to fetch.
   */
  orderBy?: Prisma.ReelOrderByWithRelationInput | Prisma.ReelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ReelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Reels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Reels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Reels
  **/
  _count?: true | ReelCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ReelAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ReelSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ReelMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ReelMaxAggregateInputType
}

export type GetReelAggregateType<T extends ReelAggregateArgs> = {
      [P in keyof T & keyof AggregateReel]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateReel[P]>
    : Prisma.GetScalarType<T[P], AggregateReel[P]>
}




export type ReelGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ReelWhereInput
  orderBy?: Prisma.ReelOrderByWithAggregationInput | Prisma.ReelOrderByWithAggregationInput[]
  by: Prisma.ReelScalarFieldEnum[] | Prisma.ReelScalarFieldEnum
  having?: Prisma.ReelScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ReelCountAggregateInputType | true
  _avg?: ReelAvgAggregateInputType
  _sum?: ReelSumAggregateInputType
  _min?: ReelMinAggregateInputType
  _max?: ReelMaxAggregateInputType
}

export type ReelGroupByOutputType = {
  id: string
  userId: string
  mediaUrl: string
  mediaType: $Enums.MediaType
  thumbnailUrl: string | null
  caption: string | null
  status: $Enums.ReelStatus
  moderation: $Enums.ModerationStatus
  viewsCount: number
  createdAt: Date
  expiresAt: Date
  _count: ReelCountAggregateOutputType | null
  _avg: ReelAvgAggregateOutputType | null
  _sum: ReelSumAggregateOutputType | null
  _min: ReelMinAggregateOutputType | null
  _max: ReelMaxAggregateOutputType | null
}

export type GetReelGroupByPayload<T extends ReelGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ReelGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ReelGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ReelGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ReelGroupByOutputType[P]>
      }
    >
  >



export type ReelWhereInput = {
  AND?: Prisma.ReelWhereInput | Prisma.ReelWhereInput[]
  OR?: Prisma.ReelWhereInput[]
  NOT?: Prisma.ReelWhereInput | Prisma.ReelWhereInput[]
  id?: Prisma.StringFilter<"Reel"> | string
  userId?: Prisma.StringFilter<"Reel"> | string
  mediaUrl?: Prisma.StringFilter<"Reel"> | string
  mediaType?: Prisma.EnumMediaTypeFilter<"Reel"> | $Enums.MediaType
  thumbnailUrl?: Prisma.StringNullableFilter<"Reel"> | string | null
  caption?: Prisma.StringNullableFilter<"Reel"> | string | null
  status?: Prisma.EnumReelStatusFilter<"Reel"> | $Enums.ReelStatus
  moderation?: Prisma.EnumModerationStatusFilter<"Reel"> | $Enums.ModerationStatus
  viewsCount?: Prisma.IntFilter<"Reel"> | number
  createdAt?: Prisma.DateTimeFilter<"Reel"> | Date | string
  expiresAt?: Prisma.DateTimeFilter<"Reel"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  views?: Prisma.ReelViewListRelationFilter
}

export type ReelOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  mediaUrl?: Prisma.SortOrder
  mediaType?: Prisma.SortOrder
  thumbnailUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  caption?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  moderation?: Prisma.SortOrder
  viewsCount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  views?: Prisma.ReelViewOrderByRelationAggregateInput
  _relevance?: Prisma.ReelOrderByRelevanceInput
}

export type ReelWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ReelWhereInput | Prisma.ReelWhereInput[]
  OR?: Prisma.ReelWhereInput[]
  NOT?: Prisma.ReelWhereInput | Prisma.ReelWhereInput[]
  userId?: Prisma.StringFilter<"Reel"> | string
  mediaUrl?: Prisma.StringFilter<"Reel"> | string
  mediaType?: Prisma.EnumMediaTypeFilter<"Reel"> | $Enums.MediaType
  thumbnailUrl?: Prisma.StringNullableFilter<"Reel"> | string | null
  caption?: Prisma.StringNullableFilter<"Reel"> | string | null
  status?: Prisma.EnumReelStatusFilter<"Reel"> | $Enums.ReelStatus
  moderation?: Prisma.EnumModerationStatusFilter<"Reel"> | $Enums.ModerationStatus
  viewsCount?: Prisma.IntFilter<"Reel"> | number
  createdAt?: Prisma.DateTimeFilter<"Reel"> | Date | string
  expiresAt?: Prisma.DateTimeFilter<"Reel"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  views?: Prisma.ReelViewListRelationFilter
}, "id">

export type ReelOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  mediaUrl?: Prisma.SortOrder
  mediaType?: Prisma.SortOrder
  thumbnailUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  caption?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  moderation?: Prisma.SortOrder
  viewsCount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  _count?: Prisma.ReelCountOrderByAggregateInput
  _avg?: Prisma.ReelAvgOrderByAggregateInput
  _max?: Prisma.ReelMaxOrderByAggregateInput
  _min?: Prisma.ReelMinOrderByAggregateInput
  _sum?: Prisma.ReelSumOrderByAggregateInput
}

export type ReelScalarWhereWithAggregatesInput = {
  AND?: Prisma.ReelScalarWhereWithAggregatesInput | Prisma.ReelScalarWhereWithAggregatesInput[]
  OR?: Prisma.ReelScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ReelScalarWhereWithAggregatesInput | Prisma.ReelScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Reel"> | string
  userId?: Prisma.StringWithAggregatesFilter<"Reel"> | string
  mediaUrl?: Prisma.StringWithAggregatesFilter<"Reel"> | string
  mediaType?: Prisma.EnumMediaTypeWithAggregatesFilter<"Reel"> | $Enums.MediaType
  thumbnailUrl?: Prisma.StringNullableWithAggregatesFilter<"Reel"> | string | null
  caption?: Prisma.StringNullableWithAggregatesFilter<"Reel"> | string | null
  status?: Prisma.EnumReelStatusWithAggregatesFilter<"Reel"> | $Enums.ReelStatus
  moderation?: Prisma.EnumModerationStatusWithAggregatesFilter<"Reel"> | $Enums.ModerationStatus
  viewsCount?: Prisma.IntWithAggregatesFilter<"Reel"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Reel"> | Date | string
  expiresAt?: Prisma.DateTimeWithAggregatesFilter<"Reel"> | Date | string
}

export type ReelCreateInput = {
  id?: string
  mediaUrl: string
  mediaType?: $Enums.MediaType
  thumbnailUrl?: string | null
  caption?: string | null
  status?: $Enums.ReelStatus
  moderation?: $Enums.ModerationStatus
  viewsCount?: number
  createdAt?: Date | string
  expiresAt: Date | string
  user: Prisma.UserCreateNestedOneWithoutReelsInput
  views?: Prisma.ReelViewCreateNestedManyWithoutReelInput
}

export type ReelUncheckedCreateInput = {
  id?: string
  userId: string
  mediaUrl: string
  mediaType?: $Enums.MediaType
  thumbnailUrl?: string | null
  caption?: string | null
  status?: $Enums.ReelStatus
  moderation?: $Enums.ModerationStatus
  viewsCount?: number
  createdAt?: Date | string
  expiresAt: Date | string
  views?: Prisma.ReelViewUncheckedCreateNestedManyWithoutReelInput
}

export type ReelUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mediaUrl?: Prisma.StringFieldUpdateOperationsInput | string
  mediaType?: Prisma.EnumMediaTypeFieldUpdateOperationsInput | $Enums.MediaType
  thumbnailUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  caption?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumReelStatusFieldUpdateOperationsInput | $Enums.ReelStatus
  moderation?: Prisma.EnumModerationStatusFieldUpdateOperationsInput | $Enums.ModerationStatus
  viewsCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutReelsNestedInput
  views?: Prisma.ReelViewUpdateManyWithoutReelNestedInput
}

export type ReelUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  mediaUrl?: Prisma.StringFieldUpdateOperationsInput | string
  mediaType?: Prisma.EnumMediaTypeFieldUpdateOperationsInput | $Enums.MediaType
  thumbnailUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  caption?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumReelStatusFieldUpdateOperationsInput | $Enums.ReelStatus
  moderation?: Prisma.EnumModerationStatusFieldUpdateOperationsInput | $Enums.ModerationStatus
  viewsCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  views?: Prisma.ReelViewUncheckedUpdateManyWithoutReelNestedInput
}

export type ReelCreateManyInput = {
  id?: string
  userId: string
  mediaUrl: string
  mediaType?: $Enums.MediaType
  thumbnailUrl?: string | null
  caption?: string | null
  status?: $Enums.ReelStatus
  moderation?: $Enums.ModerationStatus
  viewsCount?: number
  createdAt?: Date | string
  expiresAt: Date | string
}

export type ReelUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mediaUrl?: Prisma.StringFieldUpdateOperationsInput | string
  mediaType?: Prisma.EnumMediaTypeFieldUpdateOperationsInput | $Enums.MediaType
  thumbnailUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  caption?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumReelStatusFieldUpdateOperationsInput | $Enums.ReelStatus
  moderation?: Prisma.EnumModerationStatusFieldUpdateOperationsInput | $Enums.ModerationStatus
  viewsCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ReelUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  mediaUrl?: Prisma.StringFieldUpdateOperationsInput | string
  mediaType?: Prisma.EnumMediaTypeFieldUpdateOperationsInput | $Enums.MediaType
  thumbnailUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  caption?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumReelStatusFieldUpdateOperationsInput | $Enums.ReelStatus
  moderation?: Prisma.EnumModerationStatusFieldUpdateOperationsInput | $Enums.ModerationStatus
  viewsCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ReelListRelationFilter = {
  every?: Prisma.ReelWhereInput
  some?: Prisma.ReelWhereInput
  none?: Prisma.ReelWhereInput
}

export type ReelOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ReelOrderByRelevanceInput = {
  fields: Prisma.ReelOrderByRelevanceFieldEnum | Prisma.ReelOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type ReelCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  mediaUrl?: Prisma.SortOrder
  mediaType?: Prisma.SortOrder
  thumbnailUrl?: Prisma.SortOrder
  caption?: Prisma.SortOrder
  status?: Prisma.SortOrder
  moderation?: Prisma.SortOrder
  viewsCount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
}

export type ReelAvgOrderByAggregateInput = {
  viewsCount?: Prisma.SortOrder
}

export type ReelMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  mediaUrl?: Prisma.SortOrder
  mediaType?: Prisma.SortOrder
  thumbnailUrl?: Prisma.SortOrder
  caption?: Prisma.SortOrder
  status?: Prisma.SortOrder
  moderation?: Prisma.SortOrder
  viewsCount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
}

export type ReelMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  mediaUrl?: Prisma.SortOrder
  mediaType?: Prisma.SortOrder
  thumbnailUrl?: Prisma.SortOrder
  caption?: Prisma.SortOrder
  status?: Prisma.SortOrder
  moderation?: Prisma.SortOrder
  viewsCount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
}

export type ReelSumOrderByAggregateInput = {
  viewsCount?: Prisma.SortOrder
}

export type ReelScalarRelationFilter = {
  is?: Prisma.ReelWhereInput
  isNot?: Prisma.ReelWhereInput
}

export type ReelCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ReelCreateWithoutUserInput, Prisma.ReelUncheckedCreateWithoutUserInput> | Prisma.ReelCreateWithoutUserInput[] | Prisma.ReelUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ReelCreateOrConnectWithoutUserInput | Prisma.ReelCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ReelCreateManyUserInputEnvelope
  connect?: Prisma.ReelWhereUniqueInput | Prisma.ReelWhereUniqueInput[]
}

export type ReelUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ReelCreateWithoutUserInput, Prisma.ReelUncheckedCreateWithoutUserInput> | Prisma.ReelCreateWithoutUserInput[] | Prisma.ReelUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ReelCreateOrConnectWithoutUserInput | Prisma.ReelCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ReelCreateManyUserInputEnvelope
  connect?: Prisma.ReelWhereUniqueInput | Prisma.ReelWhereUniqueInput[]
}

export type ReelUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ReelCreateWithoutUserInput, Prisma.ReelUncheckedCreateWithoutUserInput> | Prisma.ReelCreateWithoutUserInput[] | Prisma.ReelUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ReelCreateOrConnectWithoutUserInput | Prisma.ReelCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ReelUpsertWithWhereUniqueWithoutUserInput | Prisma.ReelUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ReelCreateManyUserInputEnvelope
  set?: Prisma.ReelWhereUniqueInput | Prisma.ReelWhereUniqueInput[]
  disconnect?: Prisma.ReelWhereUniqueInput | Prisma.ReelWhereUniqueInput[]
  delete?: Prisma.ReelWhereUniqueInput | Prisma.ReelWhereUniqueInput[]
  connect?: Prisma.ReelWhereUniqueInput | Prisma.ReelWhereUniqueInput[]
  update?: Prisma.ReelUpdateWithWhereUniqueWithoutUserInput | Prisma.ReelUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ReelUpdateManyWithWhereWithoutUserInput | Prisma.ReelUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ReelScalarWhereInput | Prisma.ReelScalarWhereInput[]
}

export type ReelUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ReelCreateWithoutUserInput, Prisma.ReelUncheckedCreateWithoutUserInput> | Prisma.ReelCreateWithoutUserInput[] | Prisma.ReelUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ReelCreateOrConnectWithoutUserInput | Prisma.ReelCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ReelUpsertWithWhereUniqueWithoutUserInput | Prisma.ReelUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ReelCreateManyUserInputEnvelope
  set?: Prisma.ReelWhereUniqueInput | Prisma.ReelWhereUniqueInput[]
  disconnect?: Prisma.ReelWhereUniqueInput | Prisma.ReelWhereUniqueInput[]
  delete?: Prisma.ReelWhereUniqueInput | Prisma.ReelWhereUniqueInput[]
  connect?: Prisma.ReelWhereUniqueInput | Prisma.ReelWhereUniqueInput[]
  update?: Prisma.ReelUpdateWithWhereUniqueWithoutUserInput | Prisma.ReelUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ReelUpdateManyWithWhereWithoutUserInput | Prisma.ReelUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ReelScalarWhereInput | Prisma.ReelScalarWhereInput[]
}

export type EnumMediaTypeFieldUpdateOperationsInput = {
  set?: $Enums.MediaType
}

export type EnumReelStatusFieldUpdateOperationsInput = {
  set?: $Enums.ReelStatus
}

export type ReelCreateNestedOneWithoutViewsInput = {
  create?: Prisma.XOR<Prisma.ReelCreateWithoutViewsInput, Prisma.ReelUncheckedCreateWithoutViewsInput>
  connectOrCreate?: Prisma.ReelCreateOrConnectWithoutViewsInput
  connect?: Prisma.ReelWhereUniqueInput
}

export type ReelUpdateOneRequiredWithoutViewsNestedInput = {
  create?: Prisma.XOR<Prisma.ReelCreateWithoutViewsInput, Prisma.ReelUncheckedCreateWithoutViewsInput>
  connectOrCreate?: Prisma.ReelCreateOrConnectWithoutViewsInput
  upsert?: Prisma.ReelUpsertWithoutViewsInput
  connect?: Prisma.ReelWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ReelUpdateToOneWithWhereWithoutViewsInput, Prisma.ReelUpdateWithoutViewsInput>, Prisma.ReelUncheckedUpdateWithoutViewsInput>
}

export type ReelCreateWithoutUserInput = {
  id?: string
  mediaUrl: string
  mediaType?: $Enums.MediaType
  thumbnailUrl?: string | null
  caption?: string | null
  status?: $Enums.ReelStatus
  moderation?: $Enums.ModerationStatus
  viewsCount?: number
  createdAt?: Date | string
  expiresAt: Date | string
  views?: Prisma.ReelViewCreateNestedManyWithoutReelInput
}

export type ReelUncheckedCreateWithoutUserInput = {
  id?: string
  mediaUrl: string
  mediaType?: $Enums.MediaType
  thumbnailUrl?: string | null
  caption?: string | null
  status?: $Enums.ReelStatus
  moderation?: $Enums.ModerationStatus
  viewsCount?: number
  createdAt?: Date | string
  expiresAt: Date | string
  views?: Prisma.ReelViewUncheckedCreateNestedManyWithoutReelInput
}

export type ReelCreateOrConnectWithoutUserInput = {
  where: Prisma.ReelWhereUniqueInput
  create: Prisma.XOR<Prisma.ReelCreateWithoutUserInput, Prisma.ReelUncheckedCreateWithoutUserInput>
}

export type ReelCreateManyUserInputEnvelope = {
  data: Prisma.ReelCreateManyUserInput | Prisma.ReelCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type ReelUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.ReelWhereUniqueInput
  update: Prisma.XOR<Prisma.ReelUpdateWithoutUserInput, Prisma.ReelUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.ReelCreateWithoutUserInput, Prisma.ReelUncheckedCreateWithoutUserInput>
}

export type ReelUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.ReelWhereUniqueInput
  data: Prisma.XOR<Prisma.ReelUpdateWithoutUserInput, Prisma.ReelUncheckedUpdateWithoutUserInput>
}

export type ReelUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.ReelScalarWhereInput
  data: Prisma.XOR<Prisma.ReelUpdateManyMutationInput, Prisma.ReelUncheckedUpdateManyWithoutUserInput>
}

export type ReelScalarWhereInput = {
  AND?: Prisma.ReelScalarWhereInput | Prisma.ReelScalarWhereInput[]
  OR?: Prisma.ReelScalarWhereInput[]
  NOT?: Prisma.ReelScalarWhereInput | Prisma.ReelScalarWhereInput[]
  id?: Prisma.StringFilter<"Reel"> | string
  userId?: Prisma.StringFilter<"Reel"> | string
  mediaUrl?: Prisma.StringFilter<"Reel"> | string
  mediaType?: Prisma.EnumMediaTypeFilter<"Reel"> | $Enums.MediaType
  thumbnailUrl?: Prisma.StringNullableFilter<"Reel"> | string | null
  caption?: Prisma.StringNullableFilter<"Reel"> | string | null
  status?: Prisma.EnumReelStatusFilter<"Reel"> | $Enums.ReelStatus
  moderation?: Prisma.EnumModerationStatusFilter<"Reel"> | $Enums.ModerationStatus
  viewsCount?: Prisma.IntFilter<"Reel"> | number
  createdAt?: Prisma.DateTimeFilter<"Reel"> | Date | string
  expiresAt?: Prisma.DateTimeFilter<"Reel"> | Date | string
}

export type ReelCreateWithoutViewsInput = {
  id?: string
  mediaUrl: string
  mediaType?: $Enums.MediaType
  thumbnailUrl?: string | null
  caption?: string | null
  status?: $Enums.ReelStatus
  moderation?: $Enums.ModerationStatus
  viewsCount?: number
  createdAt?: Date | string
  expiresAt: Date | string
  user: Prisma.UserCreateNestedOneWithoutReelsInput
}

export type ReelUncheckedCreateWithoutViewsInput = {
  id?: string
  userId: string
  mediaUrl: string
  mediaType?: $Enums.MediaType
  thumbnailUrl?: string | null
  caption?: string | null
  status?: $Enums.ReelStatus
  moderation?: $Enums.ModerationStatus
  viewsCount?: number
  createdAt?: Date | string
  expiresAt: Date | string
}

export type ReelCreateOrConnectWithoutViewsInput = {
  where: Prisma.ReelWhereUniqueInput
  create: Prisma.XOR<Prisma.ReelCreateWithoutViewsInput, Prisma.ReelUncheckedCreateWithoutViewsInput>
}

export type ReelUpsertWithoutViewsInput = {
  update: Prisma.XOR<Prisma.ReelUpdateWithoutViewsInput, Prisma.ReelUncheckedUpdateWithoutViewsInput>
  create: Prisma.XOR<Prisma.ReelCreateWithoutViewsInput, Prisma.ReelUncheckedCreateWithoutViewsInput>
  where?: Prisma.ReelWhereInput
}

export type ReelUpdateToOneWithWhereWithoutViewsInput = {
  where?: Prisma.ReelWhereInput
  data: Prisma.XOR<Prisma.ReelUpdateWithoutViewsInput, Prisma.ReelUncheckedUpdateWithoutViewsInput>
}

export type ReelUpdateWithoutViewsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mediaUrl?: Prisma.StringFieldUpdateOperationsInput | string
  mediaType?: Prisma.EnumMediaTypeFieldUpdateOperationsInput | $Enums.MediaType
  thumbnailUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  caption?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumReelStatusFieldUpdateOperationsInput | $Enums.ReelStatus
  moderation?: Prisma.EnumModerationStatusFieldUpdateOperationsInput | $Enums.ModerationStatus
  viewsCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutReelsNestedInput
}

export type ReelUncheckedUpdateWithoutViewsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  mediaUrl?: Prisma.StringFieldUpdateOperationsInput | string
  mediaType?: Prisma.EnumMediaTypeFieldUpdateOperationsInput | $Enums.MediaType
  thumbnailUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  caption?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumReelStatusFieldUpdateOperationsInput | $Enums.ReelStatus
  moderation?: Prisma.EnumModerationStatusFieldUpdateOperationsInput | $Enums.ModerationStatus
  viewsCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ReelCreateManyUserInput = {
  id?: string
  mediaUrl: string
  mediaType?: $Enums.MediaType
  thumbnailUrl?: string | null
  caption?: string | null
  status?: $Enums.ReelStatus
  moderation?: $Enums.ModerationStatus
  viewsCount?: number
  createdAt?: Date | string
  expiresAt: Date | string
}

export type ReelUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mediaUrl?: Prisma.StringFieldUpdateOperationsInput | string
  mediaType?: Prisma.EnumMediaTypeFieldUpdateOperationsInput | $Enums.MediaType
  thumbnailUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  caption?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumReelStatusFieldUpdateOperationsInput | $Enums.ReelStatus
  moderation?: Prisma.EnumModerationStatusFieldUpdateOperationsInput | $Enums.ModerationStatus
  viewsCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  views?: Prisma.ReelViewUpdateManyWithoutReelNestedInput
}

export type ReelUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mediaUrl?: Prisma.StringFieldUpdateOperationsInput | string
  mediaType?: Prisma.EnumMediaTypeFieldUpdateOperationsInput | $Enums.MediaType
  thumbnailUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  caption?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumReelStatusFieldUpdateOperationsInput | $Enums.ReelStatus
  moderation?: Prisma.EnumModerationStatusFieldUpdateOperationsInput | $Enums.ModerationStatus
  viewsCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  views?: Prisma.ReelViewUncheckedUpdateManyWithoutReelNestedInput
}

export type ReelUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mediaUrl?: Prisma.StringFieldUpdateOperationsInput | string
  mediaType?: Prisma.EnumMediaTypeFieldUpdateOperationsInput | $Enums.MediaType
  thumbnailUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  caption?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumReelStatusFieldUpdateOperationsInput | $Enums.ReelStatus
  moderation?: Prisma.EnumModerationStatusFieldUpdateOperationsInput | $Enums.ModerationStatus
  viewsCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type ReelCountOutputType
 */

export type ReelCountOutputType = {
  views: number
}

export type ReelCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  views?: boolean | ReelCountOutputTypeCountViewsArgs
}

/**
 * ReelCountOutputType without action
 */
export type ReelCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReelCountOutputType
   */
  select?: Prisma.ReelCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ReelCountOutputType without action
 */
export type ReelCountOutputTypeCountViewsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ReelViewWhereInput
}


export type ReelSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  mediaUrl?: boolean
  mediaType?: boolean
  thumbnailUrl?: boolean
  caption?: boolean
  status?: boolean
  moderation?: boolean
  viewsCount?: boolean
  createdAt?: boolean
  expiresAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  views?: boolean | Prisma.Reel$viewsArgs<ExtArgs>
  _count?: boolean | Prisma.ReelCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["reel"]>



export type ReelSelectScalar = {
  id?: boolean
  userId?: boolean
  mediaUrl?: boolean
  mediaType?: boolean
  thumbnailUrl?: boolean
  caption?: boolean
  status?: boolean
  moderation?: boolean
  viewsCount?: boolean
  createdAt?: boolean
  expiresAt?: boolean
}

export type ReelOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "mediaUrl" | "mediaType" | "thumbnailUrl" | "caption" | "status" | "moderation" | "viewsCount" | "createdAt" | "expiresAt", ExtArgs["result"]["reel"]>
export type ReelInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  views?: boolean | Prisma.Reel$viewsArgs<ExtArgs>
  _count?: boolean | Prisma.ReelCountOutputTypeDefaultArgs<ExtArgs>
}

export type $ReelPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Reel"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    views: Prisma.$ReelViewPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    mediaUrl: string
    mediaType: $Enums.MediaType
    thumbnailUrl: string | null
    caption: string | null
    status: $Enums.ReelStatus
    moderation: $Enums.ModerationStatus
    viewsCount: number
    createdAt: Date
    expiresAt: Date
  }, ExtArgs["result"]["reel"]>
  composites: {}
}

export type ReelGetPayload<S extends boolean | null | undefined | ReelDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ReelPayload, S>

export type ReelCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ReelFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ReelCountAggregateInputType | true
  }

export interface ReelDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Reel'], meta: { name: 'Reel' } }
  /**
   * Find zero or one Reel that matches the filter.
   * @param {ReelFindUniqueArgs} args - Arguments to find a Reel
   * @example
   * // Get one Reel
   * const reel = await prisma.reel.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ReelFindUniqueArgs>(args: Prisma.SelectSubset<T, ReelFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ReelClient<runtime.Types.Result.GetResult<Prisma.$ReelPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Reel that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ReelFindUniqueOrThrowArgs} args - Arguments to find a Reel
   * @example
   * // Get one Reel
   * const reel = await prisma.reel.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ReelFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ReelFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ReelClient<runtime.Types.Result.GetResult<Prisma.$ReelPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Reel that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReelFindFirstArgs} args - Arguments to find a Reel
   * @example
   * // Get one Reel
   * const reel = await prisma.reel.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ReelFindFirstArgs>(args?: Prisma.SelectSubset<T, ReelFindFirstArgs<ExtArgs>>): Prisma.Prisma__ReelClient<runtime.Types.Result.GetResult<Prisma.$ReelPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Reel that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReelFindFirstOrThrowArgs} args - Arguments to find a Reel
   * @example
   * // Get one Reel
   * const reel = await prisma.reel.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ReelFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ReelFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ReelClient<runtime.Types.Result.GetResult<Prisma.$ReelPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Reels that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReelFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Reels
   * const reels = await prisma.reel.findMany()
   * 
   * // Get first 10 Reels
   * const reels = await prisma.reel.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const reelWithIdOnly = await prisma.reel.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ReelFindManyArgs>(args?: Prisma.SelectSubset<T, ReelFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReelPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Reel.
   * @param {ReelCreateArgs} args - Arguments to create a Reel.
   * @example
   * // Create one Reel
   * const Reel = await prisma.reel.create({
   *   data: {
   *     // ... data to create a Reel
   *   }
   * })
   * 
   */
  create<T extends ReelCreateArgs>(args: Prisma.SelectSubset<T, ReelCreateArgs<ExtArgs>>): Prisma.Prisma__ReelClient<runtime.Types.Result.GetResult<Prisma.$ReelPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Reels.
   * @param {ReelCreateManyArgs} args - Arguments to create many Reels.
   * @example
   * // Create many Reels
   * const reel = await prisma.reel.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ReelCreateManyArgs>(args?: Prisma.SelectSubset<T, ReelCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Reel.
   * @param {ReelDeleteArgs} args - Arguments to delete one Reel.
   * @example
   * // Delete one Reel
   * const Reel = await prisma.reel.delete({
   *   where: {
   *     // ... filter to delete one Reel
   *   }
   * })
   * 
   */
  delete<T extends ReelDeleteArgs>(args: Prisma.SelectSubset<T, ReelDeleteArgs<ExtArgs>>): Prisma.Prisma__ReelClient<runtime.Types.Result.GetResult<Prisma.$ReelPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Reel.
   * @param {ReelUpdateArgs} args - Arguments to update one Reel.
   * @example
   * // Update one Reel
   * const reel = await prisma.reel.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ReelUpdateArgs>(args: Prisma.SelectSubset<T, ReelUpdateArgs<ExtArgs>>): Prisma.Prisma__ReelClient<runtime.Types.Result.GetResult<Prisma.$ReelPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Reels.
   * @param {ReelDeleteManyArgs} args - Arguments to filter Reels to delete.
   * @example
   * // Delete a few Reels
   * const { count } = await prisma.reel.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ReelDeleteManyArgs>(args?: Prisma.SelectSubset<T, ReelDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Reels.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReelUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Reels
   * const reel = await prisma.reel.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ReelUpdateManyArgs>(args: Prisma.SelectSubset<T, ReelUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Reel.
   * @param {ReelUpsertArgs} args - Arguments to update or create a Reel.
   * @example
   * // Update or create a Reel
   * const reel = await prisma.reel.upsert({
   *   create: {
   *     // ... data to create a Reel
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Reel we want to update
   *   }
   * })
   */
  upsert<T extends ReelUpsertArgs>(args: Prisma.SelectSubset<T, ReelUpsertArgs<ExtArgs>>): Prisma.Prisma__ReelClient<runtime.Types.Result.GetResult<Prisma.$ReelPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Reels.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReelCountArgs} args - Arguments to filter Reels to count.
   * @example
   * // Count the number of Reels
   * const count = await prisma.reel.count({
   *   where: {
   *     // ... the filter for the Reels we want to count
   *   }
   * })
  **/
  count<T extends ReelCountArgs>(
    args?: Prisma.Subset<T, ReelCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ReelCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Reel.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReelAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ReelAggregateArgs>(args: Prisma.Subset<T, ReelAggregateArgs>): Prisma.PrismaPromise<GetReelAggregateType<T>>

  /**
   * Group by Reel.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReelGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ReelGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ReelGroupByArgs['orderBy'] }
      : { orderBy?: ReelGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ReelGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetReelGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Reel model
 */
readonly fields: ReelFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Reel.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ReelClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  views<T extends Prisma.Reel$viewsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Reel$viewsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReelViewPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Reel model
 */
export interface ReelFieldRefs {
  readonly id: Prisma.FieldRef<"Reel", 'String'>
  readonly userId: Prisma.FieldRef<"Reel", 'String'>
  readonly mediaUrl: Prisma.FieldRef<"Reel", 'String'>
  readonly mediaType: Prisma.FieldRef<"Reel", 'MediaType'>
  readonly thumbnailUrl: Prisma.FieldRef<"Reel", 'String'>
  readonly caption: Prisma.FieldRef<"Reel", 'String'>
  readonly status: Prisma.FieldRef<"Reel", 'ReelStatus'>
  readonly moderation: Prisma.FieldRef<"Reel", 'ModerationStatus'>
  readonly viewsCount: Prisma.FieldRef<"Reel", 'Int'>
  readonly createdAt: Prisma.FieldRef<"Reel", 'DateTime'>
  readonly expiresAt: Prisma.FieldRef<"Reel", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Reel findUnique
 */
export type ReelFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Reel
   */
  select?: Prisma.ReelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Reel
   */
  omit?: Prisma.ReelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReelInclude<ExtArgs> | null
  /**
   * Filter, which Reel to fetch.
   */
  where: Prisma.ReelWhereUniqueInput
}

/**
 * Reel findUniqueOrThrow
 */
export type ReelFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Reel
   */
  select?: Prisma.ReelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Reel
   */
  omit?: Prisma.ReelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReelInclude<ExtArgs> | null
  /**
   * Filter, which Reel to fetch.
   */
  where: Prisma.ReelWhereUniqueInput
}

/**
 * Reel findFirst
 */
export type ReelFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Reel
   */
  select?: Prisma.ReelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Reel
   */
  omit?: Prisma.ReelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReelInclude<ExtArgs> | null
  /**
   * Filter, which Reel to fetch.
   */
  where?: Prisma.ReelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Reels to fetch.
   */
  orderBy?: Prisma.ReelOrderByWithRelationInput | Prisma.ReelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Reels.
   */
  cursor?: Prisma.ReelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Reels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Reels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Reels.
   */
  distinct?: Prisma.ReelScalarFieldEnum | Prisma.ReelScalarFieldEnum[]
}

/**
 * Reel findFirstOrThrow
 */
export type ReelFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Reel
   */
  select?: Prisma.ReelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Reel
   */
  omit?: Prisma.ReelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReelInclude<ExtArgs> | null
  /**
   * Filter, which Reel to fetch.
   */
  where?: Prisma.ReelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Reels to fetch.
   */
  orderBy?: Prisma.ReelOrderByWithRelationInput | Prisma.ReelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Reels.
   */
  cursor?: Prisma.ReelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Reels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Reels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Reels.
   */
  distinct?: Prisma.ReelScalarFieldEnum | Prisma.ReelScalarFieldEnum[]
}

/**
 * Reel findMany
 */
export type ReelFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Reel
   */
  select?: Prisma.ReelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Reel
   */
  omit?: Prisma.ReelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReelInclude<ExtArgs> | null
  /**
   * Filter, which Reels to fetch.
   */
  where?: Prisma.ReelWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Reels to fetch.
   */
  orderBy?: Prisma.ReelOrderByWithRelationInput | Prisma.ReelOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Reels.
   */
  cursor?: Prisma.ReelWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Reels from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Reels.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Reels.
   */
  distinct?: Prisma.ReelScalarFieldEnum | Prisma.ReelScalarFieldEnum[]
}

/**
 * Reel create
 */
export type ReelCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Reel
   */
  select?: Prisma.ReelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Reel
   */
  omit?: Prisma.ReelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReelInclude<ExtArgs> | null
  /**
   * The data needed to create a Reel.
   */
  data: Prisma.XOR<Prisma.ReelCreateInput, Prisma.ReelUncheckedCreateInput>
}

/**
 * Reel createMany
 */
export type ReelCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Reels.
   */
  data: Prisma.ReelCreateManyInput | Prisma.ReelCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Reel update
 */
export type ReelUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Reel
   */
  select?: Prisma.ReelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Reel
   */
  omit?: Prisma.ReelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReelInclude<ExtArgs> | null
  /**
   * The data needed to update a Reel.
   */
  data: Prisma.XOR<Prisma.ReelUpdateInput, Prisma.ReelUncheckedUpdateInput>
  /**
   * Choose, which Reel to update.
   */
  where: Prisma.ReelWhereUniqueInput
}

/**
 * Reel updateMany
 */
export type ReelUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Reels.
   */
  data: Prisma.XOR<Prisma.ReelUpdateManyMutationInput, Prisma.ReelUncheckedUpdateManyInput>
  /**
   * Filter which Reels to update
   */
  where?: Prisma.ReelWhereInput
  /**
   * Limit how many Reels to update.
   */
  limit?: number
}

/**
 * Reel upsert
 */
export type ReelUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Reel
   */
  select?: Prisma.ReelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Reel
   */
  omit?: Prisma.ReelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReelInclude<ExtArgs> | null
  /**
   * The filter to search for the Reel to update in case it exists.
   */
  where: Prisma.ReelWhereUniqueInput
  /**
   * In case the Reel found by the `where` argument doesn't exist, create a new Reel with this data.
   */
  create: Prisma.XOR<Prisma.ReelCreateInput, Prisma.ReelUncheckedCreateInput>
  /**
   * In case the Reel was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ReelUpdateInput, Prisma.ReelUncheckedUpdateInput>
}

/**
 * Reel delete
 */
export type ReelDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Reel
   */
  select?: Prisma.ReelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Reel
   */
  omit?: Prisma.ReelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReelInclude<ExtArgs> | null
  /**
   * Filter which Reel to delete.
   */
  where: Prisma.ReelWhereUniqueInput
}

/**
 * Reel deleteMany
 */
export type ReelDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Reels to delete
   */
  where?: Prisma.ReelWhereInput
  /**
   * Limit how many Reels to delete.
   */
  limit?: number
}

/**
 * Reel.views
 */
export type Reel$viewsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReelView
   */
  select?: Prisma.ReelViewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReelView
   */
  omit?: Prisma.ReelViewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReelViewInclude<ExtArgs> | null
  where?: Prisma.ReelViewWhereInput
  orderBy?: Prisma.ReelViewOrderByWithRelationInput | Prisma.ReelViewOrderByWithRelationInput[]
  cursor?: Prisma.ReelViewWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ReelViewScalarFieldEnum | Prisma.ReelViewScalarFieldEnum[]
}

/**
 * Reel without action
 */
export type ReelDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Reel
   */
  select?: Prisma.ReelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Reel
   */
  omit?: Prisma.ReelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReelInclude<ExtArgs> | null
}
