
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `VipPlan` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model VipPlan
 * 
 */
export type VipPlanModel = runtime.Types.Result.DefaultSelection<Prisma.$VipPlanPayload>

export type AggregateVipPlan = {
  _count: VipPlanCountAggregateOutputType | null
  _avg: VipPlanAvgAggregateOutputType | null
  _sum: VipPlanSumAggregateOutputType | null
  _min: VipPlanMinAggregateOutputType | null
  _max: VipPlanMaxAggregateOutputType | null
}

export type VipPlanAvgAggregateOutputType = {
  durationDays: number | null
  priceGBP: runtime.Decimal | null
  costCoins: number | null
  bonusCoins: number | null
  sortOrder: number | null
}

export type VipPlanSumAggregateOutputType = {
  durationDays: number | null
  priceGBP: runtime.Decimal | null
  costCoins: number | null
  bonusCoins: number | null
  sortOrder: number | null
}

export type VipPlanMinAggregateOutputType = {
  id: string | null
  label: string | null
  durationDays: number | null
  priceGBP: runtime.Decimal | null
  costCoins: number | null
  bonusCoins: number | null
  active: boolean | null
  sortOrder: number | null
}

export type VipPlanMaxAggregateOutputType = {
  id: string | null
  label: string | null
  durationDays: number | null
  priceGBP: runtime.Decimal | null
  costCoins: number | null
  bonusCoins: number | null
  active: boolean | null
  sortOrder: number | null
}

export type VipPlanCountAggregateOutputType = {
  id: number
  label: number
  durationDays: number
  priceGBP: number
  costCoins: number
  bonusCoins: number
  active: number
  sortOrder: number
  _all: number
}


export type VipPlanAvgAggregateInputType = {
  durationDays?: true
  priceGBP?: true
  costCoins?: true
  bonusCoins?: true
  sortOrder?: true
}

export type VipPlanSumAggregateInputType = {
  durationDays?: true
  priceGBP?: true
  costCoins?: true
  bonusCoins?: true
  sortOrder?: true
}

export type VipPlanMinAggregateInputType = {
  id?: true
  label?: true
  durationDays?: true
  priceGBP?: true
  costCoins?: true
  bonusCoins?: true
  active?: true
  sortOrder?: true
}

export type VipPlanMaxAggregateInputType = {
  id?: true
  label?: true
  durationDays?: true
  priceGBP?: true
  costCoins?: true
  bonusCoins?: true
  active?: true
  sortOrder?: true
}

export type VipPlanCountAggregateInputType = {
  id?: true
  label?: true
  durationDays?: true
  priceGBP?: true
  costCoins?: true
  bonusCoins?: true
  active?: true
  sortOrder?: true
  _all?: true
}

export type VipPlanAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which VipPlan to aggregate.
   */
  where?: Prisma.VipPlanWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VipPlans to fetch.
   */
  orderBy?: Prisma.VipPlanOrderByWithRelationInput | Prisma.VipPlanOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.VipPlanWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VipPlans from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VipPlans.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned VipPlans
  **/
  _count?: true | VipPlanCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: VipPlanAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: VipPlanSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: VipPlanMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: VipPlanMaxAggregateInputType
}

export type GetVipPlanAggregateType<T extends VipPlanAggregateArgs> = {
      [P in keyof T & keyof AggregateVipPlan]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateVipPlan[P]>
    : Prisma.GetScalarType<T[P], AggregateVipPlan[P]>
}




export type VipPlanGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.VipPlanWhereInput
  orderBy?: Prisma.VipPlanOrderByWithAggregationInput | Prisma.VipPlanOrderByWithAggregationInput[]
  by: Prisma.VipPlanScalarFieldEnum[] | Prisma.VipPlanScalarFieldEnum
  having?: Prisma.VipPlanScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: VipPlanCountAggregateInputType | true
  _avg?: VipPlanAvgAggregateInputType
  _sum?: VipPlanSumAggregateInputType
  _min?: VipPlanMinAggregateInputType
  _max?: VipPlanMaxAggregateInputType
}

export type VipPlanGroupByOutputType = {
  id: string
  label: string
  durationDays: number
  priceGBP: runtime.Decimal
  costCoins: number | null
  bonusCoins: number
  active: boolean
  sortOrder: number
  _count: VipPlanCountAggregateOutputType | null
  _avg: VipPlanAvgAggregateOutputType | null
  _sum: VipPlanSumAggregateOutputType | null
  _min: VipPlanMinAggregateOutputType | null
  _max: VipPlanMaxAggregateOutputType | null
}

export type GetVipPlanGroupByPayload<T extends VipPlanGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<VipPlanGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof VipPlanGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], VipPlanGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], VipPlanGroupByOutputType[P]>
      }
    >
  >



export type VipPlanWhereInput = {
  AND?: Prisma.VipPlanWhereInput | Prisma.VipPlanWhereInput[]
  OR?: Prisma.VipPlanWhereInput[]
  NOT?: Prisma.VipPlanWhereInput | Prisma.VipPlanWhereInput[]
  id?: Prisma.StringFilter<"VipPlan"> | string
  label?: Prisma.StringFilter<"VipPlan"> | string
  durationDays?: Prisma.IntFilter<"VipPlan"> | number
  priceGBP?: Prisma.DecimalFilter<"VipPlan"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  costCoins?: Prisma.IntNullableFilter<"VipPlan"> | number | null
  bonusCoins?: Prisma.IntFilter<"VipPlan"> | number
  active?: Prisma.BoolFilter<"VipPlan"> | boolean
  sortOrder?: Prisma.IntFilter<"VipPlan"> | number
  subscriptions?: Prisma.VipSubscriptionListRelationFilter
}

export type VipPlanOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  label?: Prisma.SortOrder
  durationDays?: Prisma.SortOrder
  priceGBP?: Prisma.SortOrder
  costCoins?: Prisma.SortOrderInput | Prisma.SortOrder
  bonusCoins?: Prisma.SortOrder
  active?: Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
  subscriptions?: Prisma.VipSubscriptionOrderByRelationAggregateInput
  _relevance?: Prisma.VipPlanOrderByRelevanceInput
}

export type VipPlanWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.VipPlanWhereInput | Prisma.VipPlanWhereInput[]
  OR?: Prisma.VipPlanWhereInput[]
  NOT?: Prisma.VipPlanWhereInput | Prisma.VipPlanWhereInput[]
  label?: Prisma.StringFilter<"VipPlan"> | string
  durationDays?: Prisma.IntFilter<"VipPlan"> | number
  priceGBP?: Prisma.DecimalFilter<"VipPlan"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  costCoins?: Prisma.IntNullableFilter<"VipPlan"> | number | null
  bonusCoins?: Prisma.IntFilter<"VipPlan"> | number
  active?: Prisma.BoolFilter<"VipPlan"> | boolean
  sortOrder?: Prisma.IntFilter<"VipPlan"> | number
  subscriptions?: Prisma.VipSubscriptionListRelationFilter
}, "id">

export type VipPlanOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  label?: Prisma.SortOrder
  durationDays?: Prisma.SortOrder
  priceGBP?: Prisma.SortOrder
  costCoins?: Prisma.SortOrderInput | Prisma.SortOrder
  bonusCoins?: Prisma.SortOrder
  active?: Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
  _count?: Prisma.VipPlanCountOrderByAggregateInput
  _avg?: Prisma.VipPlanAvgOrderByAggregateInput
  _max?: Prisma.VipPlanMaxOrderByAggregateInput
  _min?: Prisma.VipPlanMinOrderByAggregateInput
  _sum?: Prisma.VipPlanSumOrderByAggregateInput
}

export type VipPlanScalarWhereWithAggregatesInput = {
  AND?: Prisma.VipPlanScalarWhereWithAggregatesInput | Prisma.VipPlanScalarWhereWithAggregatesInput[]
  OR?: Prisma.VipPlanScalarWhereWithAggregatesInput[]
  NOT?: Prisma.VipPlanScalarWhereWithAggregatesInput | Prisma.VipPlanScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"VipPlan"> | string
  label?: Prisma.StringWithAggregatesFilter<"VipPlan"> | string
  durationDays?: Prisma.IntWithAggregatesFilter<"VipPlan"> | number
  priceGBP?: Prisma.DecimalWithAggregatesFilter<"VipPlan"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  costCoins?: Prisma.IntNullableWithAggregatesFilter<"VipPlan"> | number | null
  bonusCoins?: Prisma.IntWithAggregatesFilter<"VipPlan"> | number
  active?: Prisma.BoolWithAggregatesFilter<"VipPlan"> | boolean
  sortOrder?: Prisma.IntWithAggregatesFilter<"VipPlan"> | number
}

export type VipPlanCreateInput = {
  id?: string
  label: string
  durationDays: number
  priceGBP: runtime.Decimal | runtime.DecimalJsLike | number | string
  costCoins?: number | null
  bonusCoins?: number
  active?: boolean
  sortOrder?: number
  subscriptions?: Prisma.VipSubscriptionCreateNestedManyWithoutPlanInput
}

export type VipPlanUncheckedCreateInput = {
  id?: string
  label: string
  durationDays: number
  priceGBP: runtime.Decimal | runtime.DecimalJsLike | number | string
  costCoins?: number | null
  bonusCoins?: number
  active?: boolean
  sortOrder?: number
  subscriptions?: Prisma.VipSubscriptionUncheckedCreateNestedManyWithoutPlanInput
}

export type VipPlanUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  durationDays?: Prisma.IntFieldUpdateOperationsInput | number
  priceGBP?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  costCoins?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  bonusCoins?: Prisma.IntFieldUpdateOperationsInput | number
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
  subscriptions?: Prisma.VipSubscriptionUpdateManyWithoutPlanNestedInput
}

export type VipPlanUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  durationDays?: Prisma.IntFieldUpdateOperationsInput | number
  priceGBP?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  costCoins?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  bonusCoins?: Prisma.IntFieldUpdateOperationsInput | number
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
  subscriptions?: Prisma.VipSubscriptionUncheckedUpdateManyWithoutPlanNestedInput
}

export type VipPlanCreateManyInput = {
  id?: string
  label: string
  durationDays: number
  priceGBP: runtime.Decimal | runtime.DecimalJsLike | number | string
  costCoins?: number | null
  bonusCoins?: number
  active?: boolean
  sortOrder?: number
}

export type VipPlanUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  durationDays?: Prisma.IntFieldUpdateOperationsInput | number
  priceGBP?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  costCoins?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  bonusCoins?: Prisma.IntFieldUpdateOperationsInput | number
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
}

export type VipPlanUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  durationDays?: Prisma.IntFieldUpdateOperationsInput | number
  priceGBP?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  costCoins?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  bonusCoins?: Prisma.IntFieldUpdateOperationsInput | number
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
}

export type VipPlanOrderByRelevanceInput = {
  fields: Prisma.VipPlanOrderByRelevanceFieldEnum | Prisma.VipPlanOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type VipPlanCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  label?: Prisma.SortOrder
  durationDays?: Prisma.SortOrder
  priceGBP?: Prisma.SortOrder
  costCoins?: Prisma.SortOrder
  bonusCoins?: Prisma.SortOrder
  active?: Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
}

export type VipPlanAvgOrderByAggregateInput = {
  durationDays?: Prisma.SortOrder
  priceGBP?: Prisma.SortOrder
  costCoins?: Prisma.SortOrder
  bonusCoins?: Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
}

export type VipPlanMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  label?: Prisma.SortOrder
  durationDays?: Prisma.SortOrder
  priceGBP?: Prisma.SortOrder
  costCoins?: Prisma.SortOrder
  bonusCoins?: Prisma.SortOrder
  active?: Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
}

export type VipPlanMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  label?: Prisma.SortOrder
  durationDays?: Prisma.SortOrder
  priceGBP?: Prisma.SortOrder
  costCoins?: Prisma.SortOrder
  bonusCoins?: Prisma.SortOrder
  active?: Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
}

export type VipPlanSumOrderByAggregateInput = {
  durationDays?: Prisma.SortOrder
  priceGBP?: Prisma.SortOrder
  costCoins?: Prisma.SortOrder
  bonusCoins?: Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
}

export type VipPlanNullableScalarRelationFilter = {
  is?: Prisma.VipPlanWhereInput | null
  isNot?: Prisma.VipPlanWhereInput | null
}

export type VipPlanCreateNestedOneWithoutSubscriptionsInput = {
  create?: Prisma.XOR<Prisma.VipPlanCreateWithoutSubscriptionsInput, Prisma.VipPlanUncheckedCreateWithoutSubscriptionsInput>
  connectOrCreate?: Prisma.VipPlanCreateOrConnectWithoutSubscriptionsInput
  connect?: Prisma.VipPlanWhereUniqueInput
}

export type VipPlanUpdateOneWithoutSubscriptionsNestedInput = {
  create?: Prisma.XOR<Prisma.VipPlanCreateWithoutSubscriptionsInput, Prisma.VipPlanUncheckedCreateWithoutSubscriptionsInput>
  connectOrCreate?: Prisma.VipPlanCreateOrConnectWithoutSubscriptionsInput
  upsert?: Prisma.VipPlanUpsertWithoutSubscriptionsInput
  disconnect?: Prisma.VipPlanWhereInput | boolean
  delete?: Prisma.VipPlanWhereInput | boolean
  connect?: Prisma.VipPlanWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.VipPlanUpdateToOneWithWhereWithoutSubscriptionsInput, Prisma.VipPlanUpdateWithoutSubscriptionsInput>, Prisma.VipPlanUncheckedUpdateWithoutSubscriptionsInput>
}

export type VipPlanCreateWithoutSubscriptionsInput = {
  id?: string
  label: string
  durationDays: number
  priceGBP: runtime.Decimal | runtime.DecimalJsLike | number | string
  costCoins?: number | null
  bonusCoins?: number
  active?: boolean
  sortOrder?: number
}

export type VipPlanUncheckedCreateWithoutSubscriptionsInput = {
  id?: string
  label: string
  durationDays: number
  priceGBP: runtime.Decimal | runtime.DecimalJsLike | number | string
  costCoins?: number | null
  bonusCoins?: number
  active?: boolean
  sortOrder?: number
}

export type VipPlanCreateOrConnectWithoutSubscriptionsInput = {
  where: Prisma.VipPlanWhereUniqueInput
  create: Prisma.XOR<Prisma.VipPlanCreateWithoutSubscriptionsInput, Prisma.VipPlanUncheckedCreateWithoutSubscriptionsInput>
}

export type VipPlanUpsertWithoutSubscriptionsInput = {
  update: Prisma.XOR<Prisma.VipPlanUpdateWithoutSubscriptionsInput, Prisma.VipPlanUncheckedUpdateWithoutSubscriptionsInput>
  create: Prisma.XOR<Prisma.VipPlanCreateWithoutSubscriptionsInput, Prisma.VipPlanUncheckedCreateWithoutSubscriptionsInput>
  where?: Prisma.VipPlanWhereInput
}

export type VipPlanUpdateToOneWithWhereWithoutSubscriptionsInput = {
  where?: Prisma.VipPlanWhereInput
  data: Prisma.XOR<Prisma.VipPlanUpdateWithoutSubscriptionsInput, Prisma.VipPlanUncheckedUpdateWithoutSubscriptionsInput>
}

export type VipPlanUpdateWithoutSubscriptionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  durationDays?: Prisma.IntFieldUpdateOperationsInput | number
  priceGBP?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  costCoins?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  bonusCoins?: Prisma.IntFieldUpdateOperationsInput | number
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
}

export type VipPlanUncheckedUpdateWithoutSubscriptionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  durationDays?: Prisma.IntFieldUpdateOperationsInput | number
  priceGBP?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  costCoins?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  bonusCoins?: Prisma.IntFieldUpdateOperationsInput | number
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
}


/**
 * Count Type VipPlanCountOutputType
 */

export type VipPlanCountOutputType = {
  subscriptions: number
}

export type VipPlanCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  subscriptions?: boolean | VipPlanCountOutputTypeCountSubscriptionsArgs
}

/**
 * VipPlanCountOutputType without action
 */
export type VipPlanCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VipPlanCountOutputType
   */
  select?: Prisma.VipPlanCountOutputTypeSelect<ExtArgs> | null
}

/**
 * VipPlanCountOutputType without action
 */
export type VipPlanCountOutputTypeCountSubscriptionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.VipSubscriptionWhereInput
}


export type VipPlanSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  label?: boolean
  durationDays?: boolean
  priceGBP?: boolean
  costCoins?: boolean
  bonusCoins?: boolean
  active?: boolean
  sortOrder?: boolean
  subscriptions?: boolean | Prisma.VipPlan$subscriptionsArgs<ExtArgs>
  _count?: boolean | Prisma.VipPlanCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["vipPlan"]>



export type VipPlanSelectScalar = {
  id?: boolean
  label?: boolean
  durationDays?: boolean
  priceGBP?: boolean
  costCoins?: boolean
  bonusCoins?: boolean
  active?: boolean
  sortOrder?: boolean
}

export type VipPlanOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "label" | "durationDays" | "priceGBP" | "costCoins" | "bonusCoins" | "active" | "sortOrder", ExtArgs["result"]["vipPlan"]>
export type VipPlanInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  subscriptions?: boolean | Prisma.VipPlan$subscriptionsArgs<ExtArgs>
  _count?: boolean | Prisma.VipPlanCountOutputTypeDefaultArgs<ExtArgs>
}

export type $VipPlanPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "VipPlan"
  objects: {
    subscriptions: Prisma.$VipSubscriptionPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    label: string
    durationDays: number
    priceGBP: runtime.Decimal
    costCoins: number | null
    bonusCoins: number
    active: boolean
    sortOrder: number
  }, ExtArgs["result"]["vipPlan"]>
  composites: {}
}

export type VipPlanGetPayload<S extends boolean | null | undefined | VipPlanDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$VipPlanPayload, S>

export type VipPlanCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<VipPlanFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: VipPlanCountAggregateInputType | true
  }

export interface VipPlanDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['VipPlan'], meta: { name: 'VipPlan' } }
  /**
   * Find zero or one VipPlan that matches the filter.
   * @param {VipPlanFindUniqueArgs} args - Arguments to find a VipPlan
   * @example
   * // Get one VipPlan
   * const vipPlan = await prisma.vipPlan.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends VipPlanFindUniqueArgs>(args: Prisma.SelectSubset<T, VipPlanFindUniqueArgs<ExtArgs>>): Prisma.Prisma__VipPlanClient<runtime.Types.Result.GetResult<Prisma.$VipPlanPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one VipPlan that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {VipPlanFindUniqueOrThrowArgs} args - Arguments to find a VipPlan
   * @example
   * // Get one VipPlan
   * const vipPlan = await prisma.vipPlan.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends VipPlanFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, VipPlanFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__VipPlanClient<runtime.Types.Result.GetResult<Prisma.$VipPlanPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first VipPlan that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VipPlanFindFirstArgs} args - Arguments to find a VipPlan
   * @example
   * // Get one VipPlan
   * const vipPlan = await prisma.vipPlan.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends VipPlanFindFirstArgs>(args?: Prisma.SelectSubset<T, VipPlanFindFirstArgs<ExtArgs>>): Prisma.Prisma__VipPlanClient<runtime.Types.Result.GetResult<Prisma.$VipPlanPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first VipPlan that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VipPlanFindFirstOrThrowArgs} args - Arguments to find a VipPlan
   * @example
   * // Get one VipPlan
   * const vipPlan = await prisma.vipPlan.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends VipPlanFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, VipPlanFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__VipPlanClient<runtime.Types.Result.GetResult<Prisma.$VipPlanPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more VipPlans that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VipPlanFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all VipPlans
   * const vipPlans = await prisma.vipPlan.findMany()
   * 
   * // Get first 10 VipPlans
   * const vipPlans = await prisma.vipPlan.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const vipPlanWithIdOnly = await prisma.vipPlan.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends VipPlanFindManyArgs>(args?: Prisma.SelectSubset<T, VipPlanFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VipPlanPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a VipPlan.
   * @param {VipPlanCreateArgs} args - Arguments to create a VipPlan.
   * @example
   * // Create one VipPlan
   * const VipPlan = await prisma.vipPlan.create({
   *   data: {
   *     // ... data to create a VipPlan
   *   }
   * })
   * 
   */
  create<T extends VipPlanCreateArgs>(args: Prisma.SelectSubset<T, VipPlanCreateArgs<ExtArgs>>): Prisma.Prisma__VipPlanClient<runtime.Types.Result.GetResult<Prisma.$VipPlanPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many VipPlans.
   * @param {VipPlanCreateManyArgs} args - Arguments to create many VipPlans.
   * @example
   * // Create many VipPlans
   * const vipPlan = await prisma.vipPlan.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends VipPlanCreateManyArgs>(args?: Prisma.SelectSubset<T, VipPlanCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a VipPlan.
   * @param {VipPlanDeleteArgs} args - Arguments to delete one VipPlan.
   * @example
   * // Delete one VipPlan
   * const VipPlan = await prisma.vipPlan.delete({
   *   where: {
   *     // ... filter to delete one VipPlan
   *   }
   * })
   * 
   */
  delete<T extends VipPlanDeleteArgs>(args: Prisma.SelectSubset<T, VipPlanDeleteArgs<ExtArgs>>): Prisma.Prisma__VipPlanClient<runtime.Types.Result.GetResult<Prisma.$VipPlanPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one VipPlan.
   * @param {VipPlanUpdateArgs} args - Arguments to update one VipPlan.
   * @example
   * // Update one VipPlan
   * const vipPlan = await prisma.vipPlan.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends VipPlanUpdateArgs>(args: Prisma.SelectSubset<T, VipPlanUpdateArgs<ExtArgs>>): Prisma.Prisma__VipPlanClient<runtime.Types.Result.GetResult<Prisma.$VipPlanPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more VipPlans.
   * @param {VipPlanDeleteManyArgs} args - Arguments to filter VipPlans to delete.
   * @example
   * // Delete a few VipPlans
   * const { count } = await prisma.vipPlan.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends VipPlanDeleteManyArgs>(args?: Prisma.SelectSubset<T, VipPlanDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more VipPlans.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VipPlanUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many VipPlans
   * const vipPlan = await prisma.vipPlan.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends VipPlanUpdateManyArgs>(args: Prisma.SelectSubset<T, VipPlanUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one VipPlan.
   * @param {VipPlanUpsertArgs} args - Arguments to update or create a VipPlan.
   * @example
   * // Update or create a VipPlan
   * const vipPlan = await prisma.vipPlan.upsert({
   *   create: {
   *     // ... data to create a VipPlan
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the VipPlan we want to update
   *   }
   * })
   */
  upsert<T extends VipPlanUpsertArgs>(args: Prisma.SelectSubset<T, VipPlanUpsertArgs<ExtArgs>>): Prisma.Prisma__VipPlanClient<runtime.Types.Result.GetResult<Prisma.$VipPlanPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of VipPlans.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VipPlanCountArgs} args - Arguments to filter VipPlans to count.
   * @example
   * // Count the number of VipPlans
   * const count = await prisma.vipPlan.count({
   *   where: {
   *     // ... the filter for the VipPlans we want to count
   *   }
   * })
  **/
  count<T extends VipPlanCountArgs>(
    args?: Prisma.Subset<T, VipPlanCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], VipPlanCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a VipPlan.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VipPlanAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends VipPlanAggregateArgs>(args: Prisma.Subset<T, VipPlanAggregateArgs>): Prisma.PrismaPromise<GetVipPlanAggregateType<T>>

  /**
   * Group by VipPlan.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VipPlanGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends VipPlanGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: VipPlanGroupByArgs['orderBy'] }
      : { orderBy?: VipPlanGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, VipPlanGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetVipPlanGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the VipPlan model
 */
readonly fields: VipPlanFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for VipPlan.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__VipPlanClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  subscriptions<T extends Prisma.VipPlan$subscriptionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.VipPlan$subscriptionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VipSubscriptionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the VipPlan model
 */
export interface VipPlanFieldRefs {
  readonly id: Prisma.FieldRef<"VipPlan", 'String'>
  readonly label: Prisma.FieldRef<"VipPlan", 'String'>
  readonly durationDays: Prisma.FieldRef<"VipPlan", 'Int'>
  readonly priceGBP: Prisma.FieldRef<"VipPlan", 'Decimal'>
  readonly costCoins: Prisma.FieldRef<"VipPlan", 'Int'>
  readonly bonusCoins: Prisma.FieldRef<"VipPlan", 'Int'>
  readonly active: Prisma.FieldRef<"VipPlan", 'Boolean'>
  readonly sortOrder: Prisma.FieldRef<"VipPlan", 'Int'>
}
    

// Custom InputTypes
/**
 * VipPlan findUnique
 */
export type VipPlanFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VipPlan
   */
  select?: Prisma.VipPlanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VipPlan
   */
  omit?: Prisma.VipPlanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VipPlanInclude<ExtArgs> | null
  /**
   * Filter, which VipPlan to fetch.
   */
  where: Prisma.VipPlanWhereUniqueInput
}

/**
 * VipPlan findUniqueOrThrow
 */
export type VipPlanFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VipPlan
   */
  select?: Prisma.VipPlanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VipPlan
   */
  omit?: Prisma.VipPlanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VipPlanInclude<ExtArgs> | null
  /**
   * Filter, which VipPlan to fetch.
   */
  where: Prisma.VipPlanWhereUniqueInput
}

/**
 * VipPlan findFirst
 */
export type VipPlanFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VipPlan
   */
  select?: Prisma.VipPlanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VipPlan
   */
  omit?: Prisma.VipPlanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VipPlanInclude<ExtArgs> | null
  /**
   * Filter, which VipPlan to fetch.
   */
  where?: Prisma.VipPlanWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VipPlans to fetch.
   */
  orderBy?: Prisma.VipPlanOrderByWithRelationInput | Prisma.VipPlanOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for VipPlans.
   */
  cursor?: Prisma.VipPlanWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VipPlans from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VipPlans.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of VipPlans.
   */
  distinct?: Prisma.VipPlanScalarFieldEnum | Prisma.VipPlanScalarFieldEnum[]
}

/**
 * VipPlan findFirstOrThrow
 */
export type VipPlanFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VipPlan
   */
  select?: Prisma.VipPlanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VipPlan
   */
  omit?: Prisma.VipPlanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VipPlanInclude<ExtArgs> | null
  /**
   * Filter, which VipPlan to fetch.
   */
  where?: Prisma.VipPlanWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VipPlans to fetch.
   */
  orderBy?: Prisma.VipPlanOrderByWithRelationInput | Prisma.VipPlanOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for VipPlans.
   */
  cursor?: Prisma.VipPlanWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VipPlans from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VipPlans.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of VipPlans.
   */
  distinct?: Prisma.VipPlanScalarFieldEnum | Prisma.VipPlanScalarFieldEnum[]
}

/**
 * VipPlan findMany
 */
export type VipPlanFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VipPlan
   */
  select?: Prisma.VipPlanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VipPlan
   */
  omit?: Prisma.VipPlanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VipPlanInclude<ExtArgs> | null
  /**
   * Filter, which VipPlans to fetch.
   */
  where?: Prisma.VipPlanWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VipPlans to fetch.
   */
  orderBy?: Prisma.VipPlanOrderByWithRelationInput | Prisma.VipPlanOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing VipPlans.
   */
  cursor?: Prisma.VipPlanWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VipPlans from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VipPlans.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of VipPlans.
   */
  distinct?: Prisma.VipPlanScalarFieldEnum | Prisma.VipPlanScalarFieldEnum[]
}

/**
 * VipPlan create
 */
export type VipPlanCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VipPlan
   */
  select?: Prisma.VipPlanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VipPlan
   */
  omit?: Prisma.VipPlanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VipPlanInclude<ExtArgs> | null
  /**
   * The data needed to create a VipPlan.
   */
  data: Prisma.XOR<Prisma.VipPlanCreateInput, Prisma.VipPlanUncheckedCreateInput>
}

/**
 * VipPlan createMany
 */
export type VipPlanCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many VipPlans.
   */
  data: Prisma.VipPlanCreateManyInput | Prisma.VipPlanCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * VipPlan update
 */
export type VipPlanUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VipPlan
   */
  select?: Prisma.VipPlanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VipPlan
   */
  omit?: Prisma.VipPlanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VipPlanInclude<ExtArgs> | null
  /**
   * The data needed to update a VipPlan.
   */
  data: Prisma.XOR<Prisma.VipPlanUpdateInput, Prisma.VipPlanUncheckedUpdateInput>
  /**
   * Choose, which VipPlan to update.
   */
  where: Prisma.VipPlanWhereUniqueInput
}

/**
 * VipPlan updateMany
 */
export type VipPlanUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update VipPlans.
   */
  data: Prisma.XOR<Prisma.VipPlanUpdateManyMutationInput, Prisma.VipPlanUncheckedUpdateManyInput>
  /**
   * Filter which VipPlans to update
   */
  where?: Prisma.VipPlanWhereInput
  /**
   * Limit how many VipPlans to update.
   */
  limit?: number
}

/**
 * VipPlan upsert
 */
export type VipPlanUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VipPlan
   */
  select?: Prisma.VipPlanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VipPlan
   */
  omit?: Prisma.VipPlanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VipPlanInclude<ExtArgs> | null
  /**
   * The filter to search for the VipPlan to update in case it exists.
   */
  where: Prisma.VipPlanWhereUniqueInput
  /**
   * In case the VipPlan found by the `where` argument doesn't exist, create a new VipPlan with this data.
   */
  create: Prisma.XOR<Prisma.VipPlanCreateInput, Prisma.VipPlanUncheckedCreateInput>
  /**
   * In case the VipPlan was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.VipPlanUpdateInput, Prisma.VipPlanUncheckedUpdateInput>
}

/**
 * VipPlan delete
 */
export type VipPlanDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VipPlan
   */
  select?: Prisma.VipPlanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VipPlan
   */
  omit?: Prisma.VipPlanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VipPlanInclude<ExtArgs> | null
  /**
   * Filter which VipPlan to delete.
   */
  where: Prisma.VipPlanWhereUniqueInput
}

/**
 * VipPlan deleteMany
 */
export type VipPlanDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which VipPlans to delete
   */
  where?: Prisma.VipPlanWhereInput
  /**
   * Limit how many VipPlans to delete.
   */
  limit?: number
}

/**
 * VipPlan.subscriptions
 */
export type VipPlan$subscriptionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VipSubscription
   */
  select?: Prisma.VipSubscriptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VipSubscription
   */
  omit?: Prisma.VipSubscriptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VipSubscriptionInclude<ExtArgs> | null
  where?: Prisma.VipSubscriptionWhereInput
  orderBy?: Prisma.VipSubscriptionOrderByWithRelationInput | Prisma.VipSubscriptionOrderByWithRelationInput[]
  cursor?: Prisma.VipSubscriptionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.VipSubscriptionScalarFieldEnum | Prisma.VipSubscriptionScalarFieldEnum[]
}

/**
 * VipPlan without action
 */
export type VipPlanDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VipPlan
   */
  select?: Prisma.VipPlanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VipPlan
   */
  omit?: Prisma.VipPlanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VipPlanInclude<ExtArgs> | null
}
